### ISSUE TITLE
Fail to save content types with dynamic zone components at 4.5.0

### ISSUE THREAD

**Issue by pooledge** [strapi/strapi#14840]
### Required System information

- Node.js version: 16.15.0
- NPM version: 8.10.0
- Strapi version: 4.5.0
- Database: MySQL 5.7.40-1.el7
- Operating system: macOS

### Describe the bug
After upgrading from 4.4.7 I am no longer able to save content types that include a dynamic zone with some components, that further nest other, repeatable components.

In my example, I have a `course` content type with a dynamic zone containing 3 components from the category `course`. Now one them, called `questionnaire chapter` further includes a repeatable component `question`. Whenever `questionnaire chapter` is being added to the dyn zone and edited, update is failing with the following log:

```
[2022-11-12 23:07:58.197] error: UPDATE
            `components_course_questionnaire_chapters_components` as a,
            (
              SELECT `id`, ROW_NUMBER() OVER (PARTITION BY `entity_id` ORDER BY `order`) AS src_order
              FROM `components_course_questionnaire_chapters_components`
              WHERE `entity_id` = 1
            ) AS b
          SET `order` = b.src_order
          WHERE b.id = a.id - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(PARTITION BY `entity_id` ORDER BY `order`) AS src_order
              FROM `com' at line 3
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(PARTITION BY `entity_id` ORDER BY `order`) AS src_order
              FROM `com' at line 3
    at Query.Sequence._packetToError (/PATH/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/PATH/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/PATH/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/PATH/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/PATH/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/PATH/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/PATH/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/PATH/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (/PATH/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/PATH/node_modules/mysql/lib/Connection.js:198:25)
    at /PATH/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/PATH/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/PATH/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/PATH/node_modules/knex/lib/client.js:146:12)
    at /PATH/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/PATH/node_modules/knex/lib/execution/transaction.js:358:12)
```
### Additionally
for some reason, `question` component is not present in the list of the components I may use for nesting

### I've tried with no avail
- to completely remove and recreate `questionnaire chapter` and `question` components
- remove `questionnaire chapter` from dyn zone

### Temporary fix
was to revert to 4.4.7

Thank you for looking into this!

**Comment by davidbalik** [comment]
Hi,
I have same problem on MySQL 5.7.34.

**Comment by pooledge** [comment]
Hi, I am on 5.7.40-1.el7

**Comment by petersg83** [comment]
Thank you,
Indeed there is a problem with mysql versions before 8 (not supporting ROW_NUMBER). I'm working on a fix.
Thank you for pointing this out!

**Comment by pwilms** [comment]
Same issue here 

"
aurora_version = 2.08.3
innodb_version = 5.7.12
version = 5.7.12
"

**Comment by arslion** [comment]
Same issue when updating Administration Panels > Users Roles

MySql Version: 5.7.40
Strapi Version: 4.5.1

```
 error: UPDATE
            `admin_users_roles_links` as a,
            (
              SELECT `id`, ROW_NUMBER() OVER (PARTITION BY `user_id` ORDER BY `role_order`) AS src_order, ROW_NUMBER() OVER (PARTITION BY `role_id` ORDER BY `user_order`) AS inv_order
              FROM `admin_users_roles_links`
              WHERE `user_id` = 2 OR `role_id` IN (2)
            ) AS b
          SET `role_order` = b.src_order, `user_order` = b.inv_order
          WHERE b.id = a.id - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(PARTITION BY `user_id` ORDER BY `role_order`) AS src_order, ROW_NUMBER() OVER (' at line 3
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(PARTITION BY `user_id` ORDER BY `role_order`) AS src_order, ROW_NUMBER() OVER (' at line 3

```

**Comment by Pablo-Aldana** [comment]
In case helps I'm having also an issue after upgrading to 4.5.0 on one of my components where I have many to many relationships as well as nested components and when trying to save now I get the following error

```db.getConnection(...).raw is not a function```

I'm using Postgres

**Comment by Eliaprz** [comment]
Same issue after upgrading 4.5.1 with Mysql :

`error: UPDATE
            `components_sections_expertise_rich_sections_components` as a,
            (
              SELECT `id`, ROW_NUMBER() OVER (PARTITION BY `entity_id` ORDER BY `order`) AS src_order
              FROM `components_sections_expertise_rich_sections_components`
              WHERE `entity_id` = 1
            ) AS b
          SET `order` = b.src_order
          WHERE b.id = a.id - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(PARTITION BY `entity_id` ORDER BY `order`) AS src_order
              FROM `com' at line 3
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(PARTITION BY `entity_id` ORDER BY `order`) AS src_order
              FROM `com' at line 3`

Strapi : 4.5.1
Mysql : 5.7

**Comment by arslion** [comment]
> Same issue after upgrading 4.5.1 with Mysql :
> 
> ```
> error: UPDATE
>             `components_sections_expertise_rich_sections_components` as a,
>             (
>               SELECT `id`, ROW_NUMBER() OVER (PARTITION BY `entity_id` ORDER BY `order`) AS src_order
>               FROM `components_sections_expertise_rich_sections_components`
>               WHERE `entity_id` = 1
>             ) AS b
>           SET `order` = b.src_order
>           WHERE b.id = a.id - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(PARTITION BY `entity_id` ORDER BY `order`) AS src_order
>               FROM `com' at line 3
> Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(PARTITION BY `entity_id` ORDER BY `order`) AS src_order
>               FROM `com' at line 3
> ```
> 
> Strapi : 4.5.1 Mysql : 5.7

@Eliaprz Pls update to Strapi Version 4.5.2. It’s fixed

**Comment by Eliaprz** [comment]
I just did it and it works fine :)

Thank you for your feedback !

**Comment by VictorienTardif** [comment]
I'm sorry but I use MySQL 8 and Strapi 4.6.0 and I still have this error... I did delete cache and build and everything.
It happens when I try to save an item in another locale. 

Here is the full error I get evrytime:

```
error: UPDATE news_items_localizations_links as a
SET news_item_order = b.src_order
FROM (
SELECT id, ROW_NUMBER() OVER (PARTITION BY news_item_id ORDER BY news_item_order) AS src_order
FROM news_items_localizations_links
WHERE news_item_id = 47
) AS b
WHERE b.id = a.id - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM (
SELECT id, ROW_NUMBER() OVER (PARTITION BY news_item_i' at line 3
```

I'm stuck with this.
Can you please help me?

Thx.

**Comment by VictorienTardif** [comment]
I did some tests and it has nothing to do with `ROW_NUMBER()` and supported window function or not.
A simple query like `SELECT id, ROW_NUMBER() OVER w AS 'row_number' FROM news_items WINDOW w AS (ORDER BY id);` works like a charm. 

So I guess there is a true SQL syntax error on the query performed when I try to save an item in a different locale.

**Comment by petersg83** [comment]
Hello @VictorienTardif it seems like another issue (even if it's the area of code), could you open a new one please?

**Comment by VictorienTardif** [comment]
> Hello @VictorienTardif it seems like another issue (even if it's the area of code), could you open a new one please?

Sure https://github.com/strapi/strapi/issues/15753
