### ISSUE TITLE
TypeError: S is not a function. After update to 4.11.1

### ISSUE THREAD

**Issue by IlirEdis** [strapi/strapi#17024]
I just updated to 4.11.1 from 4.10.7 and i cant access Content Mananger:
In the console i get this error:

<img width="1041" alt="Screenshot 2023-06-19 at 15 39 09" src="https://github.com/strapi/strapi/assets/128377763/f4b1b1ff-2c90-4a30-95b8-15cbf3e95b02">

and when i click it behaves like this:

https://github.com/strapi/strapi/assets/128377763/851e0b7e-10db-4039-b8df-f45f301bc0bf

Any help would be appreciated.

**Comment by alex-whatagraph** [comment]
Same issue here. Running Node v16.19.1, MySQL 8.0

**Comment by Boegie19** [comment]
Duplicate of https://github.com/strapi/strapi/issues/16998

**Comment by Boegie19** [comment]
This seems to be an issue with the SEO plugin what has its own repo and is not part of this repo

**Comment by IlirEdis** [comment]
Yes, seo plugin needs and update and sitemap plugin, i deleted it completely since im not using it here.
Btw i can't delete my `node-modules` folder and do `npm install` from scratch because i get this error:

```
npm ERR! code 1
npm ERR! path /Users/ilirbajrami/Desktop/Works (prej 1.qershor.2023)/EDIS/Graphics and UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild --release
npm ERR! TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR!   ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR! rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.16.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.16.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
npm ERR! gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/ilirbajrami/Desktop/Works (prej 1.qershor.2023)/EDIS/Graphics and UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/ilirbajrami/Library/Caches/node-gyp/18.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/ilirbajrami/Library/Caches/node-gyp/18.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/ilirbajrami/Library/Caches/node-gyp/18.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/ilirbajrami/Desktop/Works (prej 1.qershor.2023)/EDIS/Graphics and UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! /bin/sh: -c: line 0: syntax error near unexpected token `('
npm ERR! /bin/sh: -c: line 0: `LD_LIBRARY_PATH=/Users/ilirbajrami/Desktop/Works (prej 1.qershor.2023)/EDIS/Graphics and UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3/build/Release/lib.host:/Users/ilirbajrami/Desktop/Works (prej 1.qershor.2023)/EDIS/Graphics and UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps; mkdir -p /Users/ilirbajrami/Desktop/Works (prej 1.qershor.2023)/EDIS/Graphics and UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3; node copy.js "/Users/ilirbajrami/Desktop/Works (prej 1.qershor.2023)/EDIS/Graphics and UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3" ""'
npm ERR! make: *** [ba23eeee118cd63e16015df367567cb043fed872.intermediate] Error 2
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 22.5.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/ilirbajrami/Desktop/Works (prej 1.qershor.2023)/EDIS/Graphics and UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok
```

I must use my old `node-modules`. It works when i revert them back.

**Comment by jpcmf** [comment]
Thank you all! I’m experiencing the same issue.

**Comment by alex-whatagraph** [comment]
> This seems to be an issue with the SEO plugin what has its own repo and is not part of this repo

Thanks. That fixed the issue

**Comment by joshuaellis** [comment]
Looks like it's a plugin causing this issue so i'm going to close it.

**Comment by Boegie19** [comment]
@joshuaellis I would leave it open for a bit with a won't fix tag since else people will open a new issue every few hours

on an other note for it also seo plugin is strapis resposibility so somone should be put on that to fix it.

**Comment by joshuaellis** [comment]
> on an other note for it also seo plugin is strapis resposibility so somone should be put on that to fix it. 

didn't realise that lol, thank you for letting me know. @Mcastres would you be able to look into this? #16998 might have some more info for you.

**Comment by nnnext** [comment]
Updated the SEO Plugin to the latest version right now and is working now. Actual Strapi 4.11.3 and SEO 1.9.2

**Comment by ststaynov** [comment]
> s to be an issue with the SEO plugin what has its own repo and is not part of this repo

This does not seem to fix the issue on my side :/
