### ISSUE TITLE
`useRBAC` must be used within `Auth` since v5.11 (production only)

### ISSUE THREAD

**Issue by dhoko** [strapi/strapi#23203]
### Node Version

20.18.3

### NPM/Yarn/PNPM Version

10.8.2

### Strapi Version

5.11.2

### Operating System

MacOS

### Database

SQLite

### Javascript or Typescript

Typescript

### Bug Description

👋 

I have a custom plugin and I inject a component inside the Strapi editor sidebar. I added some permissions inside, so I use the hook `useRBAC`. It used to work (_it started to work during the beta v5_).

BUt via the 5.11 upgrade, it's broken but _only on production_. If you build your plugin and use `npm run develop` you don't get the issue.

I tried to use `Page.Protect` as it's something you use inside a few plugins. It doesn't change anything except the error message `Protect must be used within Auth`

I tried to inject the `AuthProvider` for my plugin but you don't expose it. I tried to fix the module admin to expose it, but then I was unable to build strapi :/ 

> I have the same issue for an injected component and a custom page for the plugin

tl;dr: I can't use permissions anymore as I can't make them work with the 5.11.

### Steps to Reproduce

1. Create a plugin
2. Copy the component inside a file
3. Inject this component via `injectComponent` inside `bootstrap`
4. Build the plugin
5. Build strapi
6. Run `npm run start -- start`

Ex injection code:
```js
    app.getPlugin('content-manager').injectComponent('editView', 'right-links', {
      name: 'seed-translations-document',
      Component: ButtonSeedTranslationsDocument,
    });
```

### Expected Behavior

Same as when we run develop, we can load the plugin and it works.
Same as when we used to have the 5.10.x, we can load the plugin and it works.

### Logs

```shell
- `Protect` must be used within `Auth` if I use `Page.Protect permissions={xxx}`
- `useRBAC` must be used within `Auth` if I use `useRBAC`
```

### Code Snippets

```js
import { Box, Button, Divider, Typography } from '@strapi/design-system';
import { Page, useAuth, useRBAC } from '@strapi/strapi/admin';
import { PERMISSIONS_VIEWS } from '../../../../permissions';


function Main() {
  console.log(PERMISSIONS_VIEWS.sendTranslations)
  return (
    <>
      <Box width={'100%'}>
        <Button onClick={() => alert("coucou")}  width={'100%'}>
          ha que
        </Button>
      </Box>
    </>
  );
}

function MainWithAuth() {
  const dew = useAuth('ButtonSeedTranslationsDocument', state => state.permissions)

  return (
    <>
      <Box width={'100%'}>
        <Button onClick={() => alert("coucou")}  width={'100%'}>
          ha que
        </Button>
      </Box>
    </>
  );
}

function MainWithRBAC() {
  const { isLoading, allowedActions } = useRBAC(PERMISSIONS_VIEWS.sendTranslations);

  return (
    <>
      <Box width={'100%'}>
        <Button onClick={() => alert("coucou")}  width={'100%'}>
          ha que
        </Button>
      </Box>
    </>
  );
}

export default function Render() {

  return <Main />
  // `ButtonSeedTranslationsDocument` must be used within `Auth`
  // return (<MainWithAuth/>);
  
  // `useRBAC` must be used within `Auth`
  // return (<MainWithRBAC/>);


  // `Protect` must be used within `Auth`
  // return (
  //     <Page.Protect permissions={PERMISSIONS_VIEWS.sendTranslations}>
  //       <Main/>
  //     </Page.Protect>
  // );
  
  //`Protect` must be used within `Auth`
  // return (
  //     <Page.Protect permissions={PERMISSIONS_VIEWS.sendTranslations}>
  //       <MainWithAuth/>
  //     </Page.Protect>
  // );
  
  // `Protect` must be used within `Auth`
  // return (
  //     <Page.Protect permissions={PERMISSIONS_VIEWS.sendTranslations}>
  //       <MainWithRBAC/>
  //     </Page.Protect>
  // );
}

```

> I added the variants I tried. 

### Permissions

```JSON
[
    {
        "action": "plugin::proton-crowdin.settings-read",
        "subject": null
    },
    {
        "action": "plugin::proton-crowdin.translations-update-pme",
        "subject": null
    },
    {
        "action": "plugin::proton-crowdin.translations-update-vpn",
        "subject": null
    }
]
```

### Media

<img width="954" alt="Image" src="https://github.com/user-attachments/assets/1206dfe8-d7ad-49d5-8fab-c1be8d21f889" />

### Additional information

I found a few bug reports ex https://github.com/strapi/strapi/issues/22382 All our plugins are for strapi v5 and with the latest strapi version as a dep. 

```
-----strapi root
    "@strapi/email": "5.11.2",
    "@strapi/plugin-cloud": "5.11.2",
    "@strapi/plugin-documentation": "5.11.2",
    "@strapi/plugin-users-permissions": "5.11.2",
    "@strapi/sdk-plugin": "5.3.2",
    "@strapi/strapi": "5.11.2",

-----proton-admin
    "@strapi/design-system": "^2.0.0-rc.18",
    "@strapi/icons": "^2.0.0-rc.18",
    "@strapi/sdk-plugin": "5.3.2",
    "@strapi/strapi": "5.11.2",
    "@strapi/typescript-utils": "5.11.2",
-----proton-crowdin
    "@strapi/design-system": "^2.0.0-rc.18",
    "@strapi/icons": "^2.0.0-rc.18",
    "@strapi/sdk-plugin": "5.3.2",
    "@strapi/strapi": "5.11.2",
    "@strapi/typescript-utils": "5.11.2",
-----proton-fields
    "@strapi/design-system": "^2.0.0-rc.18",
    "@strapi/icons": "^2.0.0-rc.18",
    "@strapi/sdk-plugin": "5.3.2",
    "@strapi/strapi": "5.11.2",
    "@strapi/typescript-utils": "5.11.2",

```
we have another plugin strapi-v5-plugin-populate-deep@4.0.5 (a v5 plugin). I tried to disable them but still the same issue.

```sh
 Project information

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Thu Mar 20 2025 17:50:00 GMT+0100 (Central Euro… │
│ Launched in        │ 826 ms                                           │
│ Environment        │ development                                      │
│ Process PID        │ 26269                                            │
│ Version            │ 5.11.2 (node v20.18.3)                           │
│ Edition            │ Community                                        │
│ Database           │ sqlite                                           │
│ Database name      │ .tmp/data.db                                     │
└────────────────────┴──────────────────────────────────────────────────┘
```

> Edit NODE_ENV=production doesn't change anything.

command: `npm run start -- start` because it's impossible to replicate using `npm run develop` even with NODE_ENV=production. I tried to use the strictMode from React but it doesn't change anything using the dev server :/

We found the bug via Strapi Cloud. We can replicate _if_ we use build then use `npm run start -- start`.

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

**Comment by mateusz-kleszcz** [comment]
I have the same issue with the`useRBAC` hook in my plugin.

**Comment by jsjexpert** [comment]
I'm seeing the same thing with the useAuth hook. It seems that plugins are no longer being rendered within the Auth context.
Works fine in 5.8.1 - 5.10.4 but starting in 5.11.0 
Works in 5.11.0 + in with `strapi develop` but not with `strapi build`

**Comment by dhoko** [comment]
I upgraded to the 5.12.1 and still the same issue :/ 


```
Error: `useRBAC` must be used within `Auth`
    at http://localhost:1337/admin/strapi-srjfhFaO.js:2517:6831
    at CDr (http://localhost:1337/admin/strapi-srjfhFaO.js:2517:6022)
    at i (http://localhost:1337/admin/strapi-srjfhFaO.js:2517:6798)
    at fWa (http://localhost:1337/admin/strapi-srjfhFaO.js:2531:1096)
    at fs (http://localhost:1337/admin/Sources-BN09usf1-Bmfo8ClN.js:1:77498)
    at NF (http://localhost:1337/admin/strapi-srjfhFaO.js:199:388)
    at rOn (http://localhost:1337/admin/strapi-srjfhFaO.js:215:10247)
    at $dt (http://localhost:1337/admin/strapi-srjfhFaO.js:217:12239)
    at hAe (http://localhost:1337/admin/strapi-srjfhFaO.js:234:2185)
    at rft (http://localhost:1337/admin/strapi-srjfhFaO.js:230:22701)
```

**Comment by dhoko** [comment]
We upgraded to 5.13 and the issue is still there, but it changed there is a regression as it doesn't check its context anymore:


```
TypeError: w is not a function
    at http://localhost:1337/admin/Sources-B-YNmeO9-Bbw0YPTg.js:1:1429
    at a3 (http://localhost:1337/admin/strapi-CYYEwMM1.js:217:23600)
    at Mdr (http://localhost:1337/admin/strapi-CYYEwMM1.js:230:13306)
    at Ndr (http://localhost:1337/admin/strapi-CYYEwMM1.js:230:13044)
    at kdr (http://localhost:1337/admin/strapi-CYYEwMM1.js:230:12950)
    at Ddr (http://localhost:1337/admin/strapi-CYYEwMM1.js:230:12822)
    at vfr (http://localhost:1337/admin/strapi-CYYEwMM1.js:230:25521)
    at Kk (http://localhost:1337/admin/strapi-CYYEwMM1.js:230:25169)
    at x2t (http://localhost:1337/admin/strapi-CYYEwMM1.js:230:19813)
    at ZL (http://localhost:1337/admin/strapi-CYYEwMM1.js:147:22098)
```

Tweaking the source from 
```js
// current 
    const isLoadingAuth = useAuth('useRBAC', (state)=>state.isLoading);
// updated
    const isLoadingAuth = useAuth('useRBAC', (state)=>state.isLoading, true);
```
 brings back the issue cf:


```
Error: `useRBAC` must be used within `Auth`
    at http://localhost:1337/admin/strapi-DYqa4-wl.js:2547:6562
    at xQr (http://localhost:1337/admin/strapi-DYqa4-wl.js:2547:6034)
    at i (http://localhost:1337/admin/strapi-DYqa4-wl.js:2547:6524)
    at yui (http://localhost:1337/admin/strapi-DYqa4-wl.js:2574:28524)
    at xs (http://localhost:1337/admin/Sources-5MONrKWe-DiChgR19.js:1:79095)
    at wH (http://localhost:1337/admin/strapi-DYqa4-wl.js:199:390)
    at tdr (http://localhost:1337/admin/strapi-DYqa4-wl.js:215:10315)
    at t2t (http://localhost:1337/admin/strapi-DYqa4-wl.js:217:12302)
    at pLe (http://localhost:1337/admin/strapi-DYqa4-wl.js:234:2187)
    at L2t (http://localhost:1337/admin/strapi-DYqa4-wl.js:230:22779)
```

It's impossible to import the AuthProvider so we're still stuck :/ 

Current state, as it doens't validate its context `const checkUserHasPermissions = useAuth('useRBAC', (state)=>state.checkUserHasPermissions);` is undefined so it fails inside the useEffect a few line after.

**Comment by dimitrisganotis** [comment]
Any update on this?

**Comment by dhoko** [comment]
Still there with the `5.16.1`

**Comment by dhoko** [comment]
Still an issue with `5.31.1 (node v22.14.0)`

**Comment by mathieugrwn** [comment]
Hi,

I'm trying to use this feature in one of my plugins, but I'm encountering the same problem.

Are there any plans for a fix at the moment?

**Comment by joseantoniosagredo** [comment]
I fix this error with this:
https://github.com/strapi/strapi/issues/24331#issuecomment-3501328186

I hope this helps you.
