### ISSUE TITLE
Error when adding a relation in Strapi

### ISSUE THREAD

**Issue by hsnbsst** [strapi/strapi#17260]
Bug report
Required System information
Node.js version: v16.19.0
NPM version: 8.19.3
Strapi version: 4.11.4
Database: MariaDB 10.4.21
Operating system: macOS
Is your project Javascript or Typescript: (Please specify)
Describe the bug
I encountered the following errors when trying to add a relation:

vbnet
Copy code
TypeError: ur.normalize is not a function
    at startsWith

TypeError: ur.normalize is not a function
    at startsWith
Steps to reproduce the behavior
1. Attempt to add a relation.
2. Receive an error indicating that something went wrong.

Screenshots
![Ekran Resmi 2023-07-11 11 08 36](https://github.com/strapi/strapi/assets/25246736/672f5ab3-de6b-478e-8942-6d0dbae4152c)
![Ekran Resmi 2023-07-11 11 08 45](https://github.com/strapi/strapi/assets/25246736/35826966-1983-49df-b534-8c0bded8709d)

Code snippets
------

Additional context
-----

**Comment by pointout** [comment]
I have the same issue.
mysql 8.0
node 18.16
strapi 4.11.4 (4.11.3 is working)

I have the issue with "relatedproducts" in schema:
```
{
  "kind": "collectionType",
  "collectionName": "products",
  "info": {
    "singularName": "product",
    "pluralName": "products",
    "displayName": "Product",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "name_de": {
      "type": "string",
      "required": true
    },
    "name_en": {
      "type": "string"
    },
    "orderno": {
      "type": "integer",
      "required": true,
      "unique": true
    },
    "slug_de": {
      "type": "string"
    },
    "slug_en": {
      "type": "string"
    },
    "lexiconarticles": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::lexiconarticle.lexiconarticle",
      "mappedBy": "products"
    },
   [...]
    "relatedproducts": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::product.product"
    },
    [...]
  }
}
```
But not with "related_elxiconarticles" in schema: 
```
{
  "kind": "collectionType",
  "collectionName": "lexiconarticles",
  "info": {
    "singularName": "lexiconarticle",
    "pluralName": "lexiconarticles",
    "displayName": "Lexiconarticle",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "name_de": {
      "type": "string",
      "required": true,
      "unique": false
    },
    "name_en": {
      "type": "string",
      "unique": false
    },
    "firstname": {
      "type": "string"
    },
    [...]
    "related_lexiconarticles": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::lexiconarticle.lexiconarticle"
    },
    [...]
  }
}
```
Relations to other collection types also working.

**Comment by Eventyret** [comment]
Hey there @pointout @hsnbsst ! 👋

Thanks for reaching out and bringing up the issue you're facing. No worries, we're here to help you troubleshoot and optimize your Strapi project! 😎

To tackle the problem you're experiencing, let's start by cleaning up the cache. It's a good practice to delete the cache and .build folders in your project directory. By doing so, we ensure that any cached data or outdated build artifacts are cleared out. It's like giving your project a fresh start! 💨✨

In addition to cleaning the cache, it's also recommended to delete the node_modules directory. This step helps ensure that you have a clean slate for your project's dependencies. Once you've deleted node_modules, you can use either yarn install or npm install to reinstall the necessary packages. This process ensures that you have the latest and compatible dependencies for your project. It's like tidying up your project's shelves! 🧹📦

After clearing the cache and reinstalling the dependencies, give your project another try. Check if the issue still persists. If it does, please let us know, and we'll be more than happy to dive deeper and assist you in resolving the problem. We're here to help you get your Strapi project running smoothly! 🏃‍♂️🔧

Thanks for reaching out and helping us make Strapi "Strap-tacular"! 👍🥳 

That way we ruled out any caching issues.

**Comment by pointout** [comment]
I deleted .cache, build and node_modules folder. Installed and built strapi new and started in dev mode and opend the admin in a private browser window. The error remains.

**Comment by empty-space** [comment]
Hi
Faced the same issue

**Comment by Miami3** [comment]
Hi there,
Issue still present after clearing the cache

**Comment by danieltorres1109** [comment]
I have the same problem.
Node.js version: Node 18.13.0
Strapi Version: 4.11.4

If you are as urgent as me, go from version "4.11.4" to "4.11.3".

change:
"@strapi/strapi": "4.11.3",
"@strapi/plugin-users-permissions": "4.11.3",
"@strapi/plugin-i18n": "4.11.3",

rm -rf node_modules

rm yarn.lock

yarn install

It's work for me dancing_men

**Comment by hsnbsst** [comment]
Issue still present after clearing the cache

**Comment by MonsterDeveloper** [comment]
Same here. Version 4.11.5

**Comment by judocode** [comment]
Appears present in both 4.11.4 and 4.11.5. Reverting back to 4.11.3 works

**Comment by MonsterDeveloper** [comment]
@judocode I wanted to downgrade as well, but in 4.11.3 there's another issue that makes Strapi unusable: #17289 

@Eventyret and by the way, why is the severity of this issue low? Unability to add relations is a serious problem, as almost every entity has at least one relation.

**Comment by Eventyret** [comment]
> @judocode I wanted to downgrade as well, but in 4.11.3 there's another issue that makes Strapi unusable: #17289 
> 
> @Eventyret and by the way, why is the severity of this issue low? Unability to add relations is a serious problem, as almost every entity has at least one relation.

Because at first it was just a few reports before it's been verified etc. More people that reports it it gets a higher severity ☺️
Currently retesting and re-validating everything as we speak so please bear with me ☺️

**Comment by thehackermonkey** [comment]
Just had the same issue with 4.7.1 not sure if related but the timing is weird.

**Comment by derrickmehaffy** [comment]
Can I have a few of you share your package.jsons?

**Comment by derrickmehaffy** [comment]
Tested every relationship type on v4.11.5 and could not reproduce: 
![image](https://github.com/strapi/strapi/assets/8593673/4f4964bd-44e4-45d2-87e8-0c7dcd94a91a)

**Comment by pointout** [comment]
> Can I have a few of you share your package.jsons?

```
{
  "name": "woka-cms-5-mysql",
  "private": true,
  "version": "1.0.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-graphql": "^4.11.4",
    "@strapi/plugin-i18n": "4.11.4",
    "@strapi/plugin-users-permissions": "4.11.4",
    "@strapi/provider-upload-aws-s3": "^4.11.4",
    "@strapi/strapi": "4.11.4",
    "@strapi/utils": "^4.11.4",
    "ecb-exchange-rates": "^0.0.7",
    "mysql": "2.18.1",
    "slugify": "^1.6.6",
    "strapi-plugin-duplicate-button": "^1.1.9",
    "strapi-plugin-website-builder": "^2.2.2"
  },
  "author": {
    "name": "Roman Walters"
  },
  "strapi": {
    "uuid": "xxxxxxxxxxx"
  },
  "engines": {
    "node": ">=12.x.x <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

```

**Comment by pointout** [comment]
As I have the issue only with one collection type, it may depend on schema, lifecycles, existing data? 
@derrickmehaffy I invited you to my repository to take a further insight.

**Comment by judocode** [comment]
This PR fixes it, although not sure if it is the "right" solution: https://github.com/strapi/strapi/pull/17315

**Comment by haseeb-siddiqui-arbisoft** [comment]
Same issue on `4.11.4` and `4.11.5`

**Comment by Eventyret** [comment]
> > Can I have a few of you share your package.jsons?
> 
> ```
> {
>   "name": "woka-cms-5-mysql",
>   "private": true,
>   "version": "1.0.0",
>   "description": "A Strapi application",
>   "scripts": {
>     "develop": "strapi develop",
>     "start": "strapi start",
>     "build": "strapi build",
>     "strapi": "strapi"
>   },
>   "dependencies": {
>     "@strapi/plugin-graphql": "^4.11.4",
>     "@strapi/plugin-i18n": "4.11.4",
>     "@strapi/plugin-users-permissions": "4.11.4",
>     "@strapi/provider-upload-aws-s3": "^4.11.4",
>     "@strapi/strapi": "4.11.4",
>     "@strapi/utils": "^4.11.4",
>     "ecb-exchange-rates": "^0.0.7",
>     "mysql": "2.18.1",
>     "slugify": "^1.6.6",
>     "strapi-plugin-duplicate-button": "^1.1.9",
>     "strapi-plugin-website-builder": "^2.2.2"
>   },
>   "author": {
>     "name": "Roman Walters"
>   },
>   "strapi": {
>     "uuid": "xxxxxxxxxxx"
>   },
>   "engines": {
>     "node": ">=12.x.x <=18.x.x",
>     "npm": ">=6.0.0"
>   },
>   "license": "MIT"
> }
> ```

Will it work if you remove the plugins ? just remove one by one if you can test that for us please.

**Comment by mohcenparsa** [comment]
> 
Still have this issue even after delecting cach, build and node_modules folder

**Comment by pointout** [comment]
> Will it work if you remove the plugins ? just remove one by one if you can test that for us please.

@Eventyret The bug does not seem to be related to a plugin as I can repoduce it on a fresh strapi installation doing what @judocode described. I have 3 collectiontypes: One with a number field (big integer), the second with a text field, the third with a relation to the first and another relation to the second collection type. If I select in the relation field of the third collection type the text field of the second collection type, there is no problem. As soon as I select in the relation filed to the first collection a number of the first collection, I get the error.

**Comment by hasebsiddiqui** [comment]
@pointout  The bug is fixed and will be released in version `4.12`. For now, as a workaround for this bug add a `short text` field in the first collection.

**Comment by messo96** [comment]
For me, the issue was solved by filling all values in all instances of the collection type (also in other languages i18n).

**Comment by imqdcn** [comment]
> 

This works for me. and i delete all the collection type content. then rebuild it.

**Comment by hsnbsst** [comment]
bende i still have the same problem

**Comment by delta-source** [comment]
A downgrade from 4.11.7 to 4.11.3 also fixed this for me.

**Comment by iErcann** [comment]
Same on v4.11.4
`main.e3301b6c.js:29 TypeError: yn.normalize is not a function
    at startsWith (main.e3301b6c.js:2924:38194)
    at main.e3301b6c.js:2924:49053
    at es (main.e3301b6c.js:27:20346)
    at wd (main.e3301b6c.js:29:1570)
    at Sf (main.e3301b6c.js:29:46488)
    at af (main.e3301b6c.js:29:40190)
    at sh (main.e3301b6c.js:29:40118)
    at jd (main.e3301b6c.js:29:39972)
    at ud (main.e3301b6c.js:29:36275)
    at bf (main.e3301b6c.js:29:37078)
sl @ main.e3301b6c.js:29`

I will try to downgrade to see.

**Comment by pointout** [comment]
Had to delete `.cache`, `build` and `node_modules` folders before `npm install` and `npm run build`, but then it worked with 4.12.0
Thanks!

**Comment by yangxin9527** [comment]
I can't adding a relation with  "comment" and "user", and report an error like this pr. I changed it to 4.11.3. Although the background can add releation,  but the RestApi post  still doesn't work. 
So I went to permission management and opened the user's find /findOne permission and check it on .now anything is ok

我是关联评论关联不上，用户，在后台设置就会报错，我改成4.11.3虽然后台能关联，但restapi接口还是关联不上。于是我去权限管理，打开用户的find /findOne 就可以了

**Comment by Nekall** [comment]
I had the same problem in 4.11.7, I also downgraded to 4.11.3 (deleted the cache and reinstalled) and it worked. 
I hope it'll be fixed soon.

NB: I had two errors: 
 - Nn.normalize is not a function
 - _n.normalize is not a function

I tried to play with the translation module, but nothing worked.

**Comment by dangolsusan** [comment]
@hsnbsst 

Were you able to solve this issue? I am also working on strapi v4.11.4 and i am facing the same issue.

**Comment by Bhakti-Dhanani** [comment]
││   error: create index                                                                          ││   "components_feature_innerpage_subcomponenet_traditional_crms_component_type_index" on        ││   "public"."components_feature_innerpage_subcomponenet_traditional_crms_components"            ││   ("component_type") - relation                                                                ││   "components_feature_innerpage_subcomponenet_traditional_crms_com" already exists             ││   at Parser.parseErrorMessage (/home/wappnet-20/projects/landing-site-backend/node_modules/p   ││   g-protocol/dist/parser.js:285:98)                                                            ││   at Parser.handlePacket (/home/wappnet-20/projects/landing-site-backend/node_modules/pg-pro   ││   tocol/dist/parser.js:122:29)                                                                 ││   at Parser.parse (/home/wappnet-20/projects/landing-site-backend/node_modules/pg-protocol/d   ││   ist/parser.js:35:38)                                                                         ││   at Socket.<anonymous> (/home/wappnet-20/projects/landing-site-backend/node_modules/pg-prot   ││   ocol/dist/index.js:11:42)                                                                    ││   at Socket.emit (node:events:524:28)                                                          ││   at Socket.emit (node:domain:489:12)                                                          ││   at addChunk (node:internal/streams/readable:561:12)                                          ││   at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)                       ││   at Readable.push (node:internal/streams/readable:392:5)                                      ││   at TCP.onStreamRead (node:internal/stream_base_commons:191:23)                               ││

**Comment by dangolsusan** [comment]
The below steps worked for me.
step 1: Go to Content-Type Builder
step 2: Go go the collection where you're seeing the issue.
step 3: Go to **Configure the view**

<img width="466" height="224" alt="Image" src="https://github.com/user-attachments/assets/83f815aa-4e05-47c7-9e92-242354ba3871" />

step 4: Go to the field and click the edit icon.

<img width="592" height="138" alt="Image" src="https://github.com/user-attachments/assets/e3594716-e48b-4b8d-b5d1-69d61a5b9cf8" />

step 5: Change the Entity title option from provider to other field.

<img width="539" height="334" alt="Image" src="https://github.com/user-attachments/assets/fa4826a2-2f8f-4a89-9857-29b916d887d3" />
