### PR TITLE
fix: json fields not parsed properly

### LINKED ISSUE #20655: Strapi v5 rc: admin ui read entry issue (config2.doc || "").split is not a function
### Required System information

- Node.js version: 20
- NPM version: 10
- Strapi version: 5.0.0-rc.0
- Database: Any db provider (SQLite, MySQL, Postgres)
- Operating system: Mac
- Is your project Javascript or Typescript: yes also happens in js

### Describe the bug

The problem began when we migrated from Strapi v4 to v5. Our data, stored as JSON, was easily handled in the old Strapi dashboard UI. However, after creating a new Strapi project in v5 and setting up a test API with a 'name' attribute of type JSON, the data stored in this column is now stringified. This causes an issue when trying to read and render it in the admin dashboard of the new version, resulting in exceptions as shown in the screenshot. Interestingly, the REST API operations continue to function correctly; the problem lies specifically in the admin dashboard's handling of these values.

### Steps to reproduce the behavior

1. Create a new v5 project with any database provider
2. from admin add a new collection type like test and have one attribute name type JSON
3. add some JSON values and save and update this from the database to meet our one old data as is JSON not stringified because Strapi now when you save it will be stringified in DB. From the database update this new entry to have a pure JSON object (as we already have our data as JSON not stringified so we need to read with any modification from the old system db) imaging you have the data seeded

### Expected behavior

Admin UI can render value as in old v4

### Code snippets

`
{
  "kind": "collectionType",
  "collectionName": "tests",
  "info": {
    "singularName": "test",
    "pluralName": "tests",
    "displayName": "test"
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "json"
    }
  }
}`

DB
Saved from Admin UI
row sql `1	u9n4ruiare28wxgcoh1sc6yx	"{\"test\": 134}"	2024-06-28 09:38:32.286	2024-06-28 09:38:32.286	2024-06-28 09:38:32.281	1	1	`

Update the name column value by converting it to a JSON  object to meet our existing data in the old system
`1	u9n4ruiare28wxgcoh1sc6yx	{"test": 134}	2024-06-28 09:38:32.286	2024-06-28 09:38:32.286	2024-06-28 09:38:32.281	1	1`	

### Screenshots

Screenshot 2024-06-28 at 9 38 31 AM
Screenshot 2024-06-28 at 9 38 44 AM
Data saved from Admin UI
Screenshot 2024-06-28 at 9 39 17 AM
Update name value to pure JSON object
Screenshot 2024-06-28 at 9 39 44 AM
Screenshot 2024-06-28 at 9 41 02 AM

### PR DESCRIPTION
**Pull request by remidej**
### What does it do?

Makes sure the JSON fields are parsed properly when read from the database. It turns out sometimes, probably because of v4 to v5 migrations, they were stringified twice, so [they needed to be parsed twice](https://stackoverflow.com/questions/31662849/parse-json-object-that-stringify-twice).

I also made a fix on the frontend to support both string and object types, as both could be sent for users migrating.

### How to test it?

- Write JSON in a JSON field in the edit view, the experience should be normal
- Save and refresh, your changes should be retrieved
- Query the content using the content API, you should see your JSON input in object form, not as a string

### Related issue(s)/PR(s)

replaces #20829
fixes #20655

### CODE REVIEW

**Comment by Marc-Roig** [comment]
I am also curious to find out what caused this too, should we test the migration to avoid this data issue in db?

**Comment by remidej** [comment]
@Marc-Roig you're right I looked more into the root cause, and think I patched it now. The frontend is now sending the data as a string, but we were stringifying at the db level regardless when saving

**Review by Marc-Roig — APPROVED** [review]
lets goo!! 🚀

**Comment by shamglam** [comment]
@remidej we have a custom field of type json, and the input component of the custom field isn't receiving anything in the value property. 
Could this be related? Currently running on rc7

**Comment by remidej** [comment]
@shamglam could you share the code of your custom field input? I don't think it's related to this PR but we can check

**Comment by remidej** [comment]
It looks like this is a breaking change we failed to document. Value, setValue and error can now be retrieved from a hook, [like it's done there](https://github.com/strapi/strapi/blob/baabf9edef4d0079bdbe0f891dcba743afc5a571/packages/plugins/color-picker/admin/src/components/ColorPickerInput.tsx#L79).

I think we should be able to provide backward compatibility though. I'll share that with the team. Thanks for your report!

**Comment by shamglam** [comment]
@remidej - while we're at this - I've updated the code according to the link you provided, had a small question 
when calling onChange(name, val); - do i need to call JSON.stringify for the val object if the field type is json.

**Comment by remidej** [comment]
@shamglam both stringified and non-stringified forms should be supported, so you can keep it as an object if that's what you're working with
