### ISSUE TITLE
Unable to start Strapi on version 12.4 - Missing moment package

### ISSUE THREAD

**Issue by dorelljames** [strapi/strapi#1408]
<!-- ⚠️ If you do not respect this template your issue will be closed. -->

<!-- ⚠️ Before writing your issue make sure you are using:-->
<!-- Node 9.x.x -->
<!-- npm 5.x.x -->
<!-- The latest version of Strapi. -->

**Informations**
- **Node.js version**: v9.11.2
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.4
- **Database**: MongoDB
- **Operating system**: CentOS 6.5 

Edit: Also verified not working on macOS Sierra 10.12.6 with Node.js version 8.9.0 and npm version 5.7.1 and MongoDB.

**What is the current behavior?** Strapi can't start via `strapi start` command. 
See below: 
```
[2018-06-18T06:51:50.859Z] debug Server wasn't able to start properly.
{ Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at VERSION (/Users/dorelljames/.nvm/versions/node/v8.9.0/lib/node_modules/strapi/node_modules/moment-timezone/moment-timezone.js:12:28)
    at Object.<anonymous> (/Users/dorelljames/.nvm/versions/node/v8.9.0/lib/node_modules/strapi/node_modules/moment-timezone/moment-timezone.js:17:2)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dorelljames/.nvm/versions/node/v8.9.0/lib/node_modules/strapi/node_modules/moment-timezone/index.js:1:93)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10) code: 'MODULE_NOT_FOUND' }
```

**Steps to reproduce the problem** 

1. Install latest strapi `npm install strapi@alpha -g` and make sure you are on version `3.0.0-alpha.12.4`. 
2. Start a new project: `strapi new myProject`
3. Follow instructions and use MongoDB.
4. After successful installation. Start strapi via `strapi start`. Observed. 



**What is the expected behavior?**  Strapi should start normally. 



**Suggested solutions** Adding moment package via `npm install moment --save` inside `node_modules/strapi` resolved the issue.

```
 ~/code/strapi/api3/node_modules/strapi   6597e119 v0.33.5  npm install moment --save                                                                                                                                                                1 ↵  9179  14:58:54
npm notice created a lockfile as package-lock.json. You should commit this file.
+ moment@2.22.2
added 1 package from 6 contributors in 1.608s
 ~/code/strapi/api3/node_modules/strapi   6597e119 v0.33.5  ..                                                                                                                                                                                         ✔  9180  14:59:01
 ~/code/strapi/api3/node_modules  ..                                                                                                                                                                                                                     ✔  9181  14:59:05
~/code/strapi/api3  strapi start                                                                                                                                                                                                                        ✔  9181  14:59:06
[2018-06-18T06:59:11.467Z] info Server started in /Users/dorelljames/Projects/code/strapi/api3
[2018-06-18T06:59:11.468Z] info Your server is running at http://localhost:1337
[2018-06-18T06:59:11.468Z] debug Time: Mon Jun 18 2018 14:59:11 GMT+0800 (+08)
[2018-06-18T06:59:11.468Z] debug Launched in: 2412 ms
[2018-06-18T06:59:11.468Z] debug Environment: development
[2018-06-18T06:59:11.468Z] debug Process PID: 5069
[2018-06-18T06:59:11.468Z] debug Version: 3.0.0-alpha.12.4 (node v8.9.0)
[2018-06-18T06:59:11.468Z] info To shut down your server, press <CTRL> + C at any time
[2018-06-18T06:59:13.935Z] info File changed: /Users/dorelljames/Projects/code/strapi/api3/plugins/users-permissions/config/actions.json
```


<!-- ⚠️ Make sure to browse the opened and closed issues before submitting your issue. -->

**Comment by lauriejim** [comment]
Hello, I just tried and I have no issue... 
@Icemic what is your OS ?

**Comment by Icemic** [comment]
@lauriejim macOS 10.13.2 with Node 10.4.1, and I am using `nvm` to manage multiple nodejs.

**Comment by lauriejim** [comment]
If you install strapi again it doesn't fix the missing deps ?

**Comment by dorelljames** [comment]
@lauriejim I can no longer reproduce the problem now (at this very moment) using my other Mac machine with the same steps I provided above. That's really odd. Perhaps some dependency not still pulled and updated properly?  

@Icemic thanks for confirming the issue. I think re-installing Strapi fixes it.
