### ISSUE TITLE
MigrationError: Migration core::5.0.0-discard-drafts (up) failed: Original error: `con.batchInsert` is not a function

### ISSUE THREAD

**Issue by jackbuehner** [strapi/strapi#21395]
### Required System information

- Node.js version: v18.20.4
- NPM version: 10.7.0
- Strapi version: 5.0.0
- Database: PostgreSQL
- Operating system: Windows 10 21H2 (LTSC)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When I upgrade to Strapi 5.0.0 and run Strapi for the first time, I get a migration error:

```
[2024-09-20 00:00:01.604] error: Migration core::5.0.0-discard-drafts (up) failed: Original error: con.batchInsert is not a function
MigrationError: Migration core::5.0.0-discard-drafts (up) failed: Original error: con.batchInsert is not a function
    at C:\Users\jackb\Workspace\content-manager\node_modules\umzug\lib\umzug.js:169:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Umzug.runCommand (C:\Users\jackb\Workspace\content-manager\node_modules\umzug\lib\umzug.js:125:20)
    at async Object.up (C:\Users\jackb\Workspace\content-manager\node_modules\@strapi\database\dist\index.js:6531:7)
    at async Object.up (C:\Users\jackb\Workspace\content-manager\node_modules\@strapi\database\dist\index.js:6555:11)
    at async Object.sync (C:\Users\jackb\Workspace\content-manager\node_modules\@strapi\database\dist\index.js:2246:9)
    at async Strapi.bootstrap (C:\Users\jackb\Workspace\content-manager\node_modules\@strapi\core\dist\Strapi.js:351:5)
    at async Strapi.load (C:\Users\jackb\Workspace\content-manager\node_modules\@strapi\core\dist\Strapi.js:315:5)
    at async Strapi.start (C:\Users\jackb\Workspace\content-manager\node_modules\@strapi\core\dist\Strapi.js:207:9)
[2024-09-20 00:00:01.606] info: Shutting down Strapi
```

### Steps to reproduce the behavior

1. Upgrade from Strapi 4.25.10.
2. Make a testing/development copy of the database from 4.25.10 and configure Strapi to use the copy.
3. Start Strapi.
4. After several minutes, the migration fails.

### Expected behavior

The migration should not fail.

### Additional context

This is probably related to https://github.com/strapi/strapi/issues/21352.

**Comment by bwcr** [comment]
Got the same problem here actually

**Comment by Abdealikw** [comment]
I am also facing the same issue. I upgarded from v4.24.2 to v5.0.0

**Comment by agazibaric** [comment]
Got the same issue. Trying to upgrade from v4.25.8 to v5.0.0.

**Comment by zjjtm** [comment]
According to the official upgrade tutorial, I have never succeeded even once. Has any of you successfully upgraded? Can anyone provide a more detailed upgrade tutorial?

**Comment by alaindimabuyo** [comment]
@zjjtm didnt succeed as well i dont why this closed

**Comment by bwcr** [comment]
> @zjjtm didnt succeed as well i dont why this closed

There has been patch update that fixes this exact issue. You might want to update it to 5.0.1

**Comment by alaindimabuyo** [comment]
@bwcr im on 5.0.6

**Comment by bwcr** [comment]
> @bwcr im on 5.0.6 
> 
> 

Have you correctly followed the migration guide?

https://docs.strapi.io/dev-docs/migration/v4-to-v5/step-by-step

**Comment by zjjtm** [comment]
> > @zjjtm didnt succeed as well i dont why this closed
> 
> There has been patch update that fixes this exact issue. You might want to update it to 5.0.1

Actually we did followed the migration guide, and it alway faces this problem: https://github.com/strapi/strapi/issues/21462

Obviously there are still so many problems with the v5 version, I don’t know why the official is so eager to release it. We have given up on upgrading to version v5.

Another solution is that we start a new project via v5, then rebuild all current collections based on v4, I believe this process is relatively easy. The difficulty is how to migrate the content from v4 to v5.

**Comment by lokeshchoudharyprogrammer** [comment]
**resolve error "con.batchInsert is not a function.**
> node_modules\@strapi\core\dist\services\document-service\utils\unidirectional-relations.js


**Use knex.insert() instead of con.batchInsert()**

` await con.insert(newRelations).into(joinTable.name).transacting(trx); `

**Comment by prokopsimek** [comment]
I am facing the same issue on v5.1.1

**Comment by trendpro** [comment]
I am facing the same issue on v5.3.0

**Comment by Mikeez** [comment]
Same issue 5.4.0 - Migrating from latest v4

**Comment by fanzypantz** [comment]
Got the same issue on my v5.8.1 from 4.25.20 migration path

**Comment by amilcarex** [comment]
Got the same issue on my v5.11.3 from v4.25.20 migration path

**Comment by agazibaric** [comment]
For me, it worked on version v5.10.4, but not on the latest one at the time, which was v5.11.0.
