### ISSUE TITLE
Just updated to the latest version and got the bug below

### ISSUE THREAD

**Issue by sbatururimi** [strapi/strapi#23488]
```
TypeError: checkUserHasPermissions is not a function
    at http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-MYKTQSXF.js?v=bf1d1142:85:7
    at commitHookEffectListMount (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=bf1d1142:16915:34)
    at commitPassiveMountOnFiber (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=bf1d1142:18156:19)
    at commitPassiveMountEffects_complete (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=bf1d1142:18129:17)
    at commitPassiveMountEffects_begin (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=bf1d1142:18119:15)
    at commitPassiveMountEffects (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=bf1d1142:18109:11)
    at flushPassiveEffectsImpl (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=bf1d1142:19490:11)
    at flushPassiveEffects (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=bf1d1142:19447:22)
    at performSyncWorkOnRoot (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=bf1d1142:18868:11)
    at flushSyncCallbacks (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=bf1d1142:9119:30)
```

**Comment by jmnyarega** [comment]
As far as I can tell, `checkUserHasPermissions` was introduced in v5.

And yes, `checkUserHasPermissions` is a function in v5:
https://github.com/strapi/strapi/blob/990615b2ed4dd2f0589b4fda91418246d7b9450e/packages/core/admin/admin/src/features/Auth.tsx#L200


It seems you are experiencing this error because you have defined a custom variable named `checkUserHasPermissions` in your source code, which overrides the Strapi function. Consequently, the error message indicates that it is not a function.

**Comment by pfinkbeiner** [comment]
@jmnyarega at least in my project I havent overwritten the variable, but I had the same error. After I updated my strapi from 5.12.5 to 5.13.0 the issue seems to be resolved.

**Comment by 0zyxel0** [comment]
I had the same experience upgrading my strapi from 5.12.6 to  5.13.0. When opening the Admin panel I get this error When opening the content type builder
`
```
TypeError: Cannot read properties of undefined (reading 'filter')
    at Protect (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-KVU3XSPC.js?v=0457c8bd:288:47)
    at renderWithHooks (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=0457c8bd:11548:26)
    at mountIndeterminateComponent (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=0457c8bd:14926:21)
    at beginWork (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=0457c8bd:15914:22)
    at beginWork$1 (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=0457c8bd:19753:22)
    at performUnitOfWork (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=0457c8bd:19198:20)
    at workLoopSync (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=0457c8bd:19137:13)
    at renderRootSync (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=0457c8bd:19116:15)
    at recoverFromConcurrentError (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=0457c8bd:18736:28)
    at performConcurrentWorkOnRoot (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=0457c8bd:18684:30)
```
      `

And if I try to open Content Manager I will get this error from the browser

![Image](https://github.com/user-attachments/assets/480d19d4-2af6-4fb9-9676-2684a670ea8e)

**Comment by jmnyarega** [comment]
@0zyxel0, I don't have a solution for this issue. Please check this (https://github.com/strapi/strapi/issues/23099); it may provide some ideas.

**Comment by 0zyxel0** [comment]
@alexandrebodin hi, yes it was still an issue. But as a work around, We just migrated the whole codebase to a newly created strapi, since the updater does not work with the cli method. 

We did re-create everything but so far everything still works. I can check with other previous versions and update it to the latest version of strapi and get back if we will encounter the same.

npm version : 10.8.2
node version : v20.19.1
os: windows 11

**Comment by alexandrebodin** [comment]
@0zyxel0 Happy to hear you found a workaround 🙏 

We have seen issue with deeply nested version and node_modules using mistmatched versions? usually entirely deleting the node_modules and clear npm cache (or .pnpm or pnpm) and re-install solves the issue in case you want to try again. 

I'll close this issue for now as this is not a specific bug we can fix. I'll keep an eye on hear if someone is encountering the same pbls multiple times

**Comment by Shruti778** [comment]
Hello guys, 
Is there any update, I face same issue when I switch strapi v4 to v5.
Entirely deleting the node_modules and clear npm cache (or .pnpm or pnpm) and re-install not solved my problem. I am still facing the same issue.
Any update on this?

**Comment by alexandrebodin** [comment]
@Shruti778 Can you open a new issue & share as many details as possible in there 🙏

**Comment by kaanmertkoc** [comment]
> Hello guys, Is there any update, I face same issue when I switch strapi v4 to v5. Entirely deleting the node_modules and clear npm cache (or .pnpm or pnpm) and re-install not solved my problem. I am still facing the same issue. Any update on this?

Hey i have 5 different strapi instance live and serving over millions of users using self host. Two of them are on version 4 and i dont plan to ever update it. 

Fortunately rest of them were created using v5 so they are safe but i think going from v4 to v5 is almost impossible on self host due to very fundamental changes on API & DB level. 

Don't get me wrong i love Strapi very much! But if you are on v4 my best advice you is stay on there unless you really need v5 features imo.

**Comment by at-woutervanderschagt** [comment]
Also having this issue with strapi 5.30.0 :)

**Comment by kevinvugts** [comment]
Same..
