### ISSUE TITLE
in strapi 4.5.1 many to many relationship to the same content type gives error on save

### ISSUE THREAD

**Issue by violabg** [strapi/strapi#14918]
## Bug report
I added a manager field on the user permission content, which is a many to many relationship to the same content, so I have 2 new fields users and manager.
I has always worked but after updating to version 4.5.1 if I remove a manager and try to save I get this error:

```UPDATE "up_users_users_links" as a
              SET "user_order" = b.src_order, "user_order" = b.inv_order
              FROM (
                SELECT "id", ROW_NUMBER() OVER (PARTITION BY "inv_user_id" ORDER BY "user_order") AS src_order, ROW_NUMBER() OVER (PARTITION BY "user_id" ORDER BY "user_order") AS inv_order
                FROM "up_users_users_links"
                WHERE "inv_user_id" = $1 OR "user_id" IN ($2)
              ) AS b
              WHERE b.id = a.id - multiple assignments to same column "user_order"
error: UPDATE "up_users_users_links" as a
              SET "user_order" = b.src_order, "user_order" = b.inv_order
              FROM (
                SELECT "id", ROW_NUMBER() OVER (PARTITION BY "inv_user_id" ORDER BY "user_order") AS src_order, ROW_NUMBER() OVER (PARTITION BY "user_id" ORDER BY "user_order") AS inv_order
                FROM "up_users_users_links"
                WHERE "inv_user_id" = $1 OR "user_id" IN ($2)
              ) AS b
              WHERE b.id = a.id - multiple assignments to same column "user_order"
    at Parser.parseErrorMessage (/var/www/mc-intra-api/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/var/www/mc-intra-api/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/var/www/mc-intra-api/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/var/www/mc-intra-api/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

### Required System information

- Node.js version: 14 latest
- NPM version: 
- Strapi version: 4.5.1 
- Database: postgress
- Operating system: ubuntu

### Steps to reproduce the behavior

1. add a relationship field to the user permissions, of type many to many (managers to users)
2. add a manager to the user and save
3. go back to the user and save
4. the error above is printed on the console

### Expected behavior

should be able to remove field and save, as we were prior to version 4.5.1

**Comment by derrickmehaffy** [comment]
Could be related to the other relational issues we had in v4.5.0

**Comment by derrickmehaffy** [comment]
Can't reproduce in v4.5.1

![image](https://user-images.githubusercontent.com/8593673/202538606-6decdf29-ea27-4ff0-83dd-e563ba945164.png)
![image](https://user-images.githubusercontent.com/8593673/202538624-9a8b97ae-9892-4eac-813d-1fd7e8854a70.png)
![image](https://user-images.githubusercontent.com/8593673/202538638-7e1798d2-06b8-406e-8690-a2a5188eba4d.png)
![image](https://user-images.githubusercontent.com/8593673/202538655-32349b72-2bbd-424e-a0b7-ae4fcdbe8ff9.png)

**Comment by violabg** [comment]
The first time you add one or more value and save it works, It happens when you try to update the field.
Did you try that?

**Comment by flashcatz** [comment]
I got a similar error when I updated to 4.5.1.
So I downgraded to 4.5.7 and 4.5.0 and the error went away.

**Comment by razvanilin** [comment]
I had issues with updating manyToMany relationships and I traced the issue to an invalid SQL query. The issue was that the query was not compatible with MySQL 5.7.36 (the version I was running)

I updated to Mysql 8 and works perfectly now

**Comment by violabg** [comment]
I have tried with an empty DB, to exclude that was caused by corrupted data, but the problem persist.
this is my DB version

PostgreSQL 12.12 (Ubuntu 12.12-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit

**Comment by razvanilin** [comment]
If not too much of a hassle, I'd try to update to Postgres 14 to see if the issue persists. In my case, I was getting an update error very similar to yours, but it was saying specifically that the syntax might be incompatible with the MySQL version. Seems that the Postgres driver doesn't say much at why the query fails

**Comment by violabg** [comment]
> If not too much of a hassle, I'd try to update to Postgres 14 to see if the issue persists. In my case, I was getting an update error very similar to yours, but it was saying specifically that the syntax might be incompatible with the MySQL version. Seems that the Postgres driver doesn't say much at why the query fails

I did
PostgreSQL 14.6 (Ubuntu 14.6-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit

but didn't solve it

**Comment by violabg** [comment]
https://user-images.githubusercontent.com/3963176/202738329-601a1461-0bbc-4444-82f3-41202c9ebbad.mp4

**Comment by violabg** [comment]
https://user-images.githubusercontent.com/3963176/202738913-3216c32d-1dcf-42c8-8cf9-c37bff10a71c.mp4

**Comment by petersg83** [comment]
I think you have an error in you schema.
```js
 "managers": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "plugin::users-permissions.user",
      "inversedBy": "users"
    },
    "users": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "plugin::users-permissions.user",
      "inversedBy": "managers" // <- should be "mappedBy": "managers"
    }
```
You can check the examples there : https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#model-attributes

**Comment by Pablo-Aldana** [comment]
In case helps I'm having also an issue after upgrading to 4.5.0 on one of my components where I have many to many relationships as well as nested components and when trying to save now I get the following error

```db.getConnection(...).raw is not a function```

**Comment by violabg** [comment]
> I think you have an error in you schema.
> 
> ```js
>  "managers": {
>       "type": "relation",
>       "relation": "manyToMany",
>       "target": "plugin::users-permissions.user",
>       "inversedBy": "users"
>     },
>     "users": {
>       "type": "relation",
>       "relation": "manyToMany",
>       "target": "plugin::users-permissions.user",
>       "inversedBy": "managers" // <- should be "mappedBy": "managers"
>     }
> ```
> 
> You can check the examples there : https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#model-attributes
> 
> Becareful when changing the schema, depending on which side of the relation has the `inversedBy`, the join table name can change. You could lose your relations. I advice to do a backup before just in case

I changed the schema as you suggest (even if it generated by strapi) but still getting error

```bash
error: UPDATE "up_users_managers_links" as a
              SET "user_order" = b.src_order, "user_order" = b.inv_order
              FROM (
                SELECT "id", ROW_NUMBER() OVER (PARTITION BY "user_id" ORDER BY "user_order") AS src_order, ROW_NUMBER() OVER (PARTITION BY "inv_user_id" ORDER BY "user_order") AS inv_order
                FROM "up_users_managers_links"
                WHERE "user_id" = $1 OR "inv_user_id" IN ($2)
              ) AS b
              WHERE b.id = a.id - multiple assignments to same column "user_order"
error: UPDATE "up_users_managers_links" as a
              SET "user_order" = b.src_order, "user_order" = b.inv_order
              FROM (
                SELECT "id", ROW_NUMBER() OVER (PARTITION BY "user_id" ORDER BY "user_order") AS src_order, ROW_NUMBER() OVER (PARTITION BY "inv_user_id" ORDER BY "user_order") AS inv_order
                FROM "up_users_managers_links"
                WHERE "user_id" = $1 OR "inv_user_id" IN ($2)
              ) AS b
              WHERE b.id = a.id - multiple assignments to same column "user_order"
    at Parser.parseErrorMessage (/var/www/mc-intra-api/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/var/www/mc-intra-api/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/var/www/mc-intra-api/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/var/www/mc-intra-api/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

from the original schema whit "inversedBy": "managers"

```bash
error: UPDATE "up_users_users_links" as a
              SET "user_order" = b.src_order, "user_order" = b.inv_order
              FROM (
                SELECT "id", ROW_NUMBER() OVER (PARTITION BY "inv_user_id" ORDER BY "user_order") AS src_order, ROW_NUMBER() OVER (PARTITION BY "user_id" ORDER BY "user_order") AS inv_order
                FROM "up_users_users_links"
                WHERE "inv_user_id" = $1 OR "user_id" IN ($2)
              ) AS b
              WHERE b.id = a.id - multiple assignments to same column "user_order"
error: UPDATE "up_users_users_links" as a
              SET "user_order" = b.src_order, "user_order" = b.inv_order
              FROM (
                SELECT "id", ROW_NUMBER() OVER (PARTITION BY "inv_user_id" ORDER BY "user_order") AS src_order, ROW_NUMBER() OVER (PARTITION BY "user_id" ORDER BY "user_order") AS inv_order
                FROM "up_users_users_links"
                WHERE "inv_user_id" = $1 OR "user_id" IN ($2)
              ) AS b
              WHERE b.id = a.id - multiple assignments to same column "user_order"
    at Parser.parseErrorMessage (/var/www/mc-intra-api/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/var/www/mc-intra-api/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/var/www/mc-intra-api/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/var/www/mc-intra-api/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by violabg** [comment]
I have just created a new strapi v4.5.1 project, with no content types, just user permission, with a new empty DB (PostgreSQL 14.6 (Ubuntu 14.6-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit)
and having the same issue, so I guess it is related to posgres db, the error is the same, I'm going to past it just in case, but it should be easy to reproduce if you are using postres

```bash
error: UPDATE "up_users_users_links" as a
              SET "user_order" = b.src_order, "user_order" = b.inv_order
              FROM (
                SELECT "id", ROW_NUMBER() OVER (PARTITION BY "inv_user_id" ORDER BY "user_order") AS src_order, ROW_NUMBER() OVER (PARTITION BY "user_id" ORDER BY "user_order") AS inv_order
                FROM "up_users_users_links"
                WHERE "inv_user_id" = $1 OR "user_id" IN ($2)
              ) AS b
              WHERE b.id = a.id - multiple assignments to same column "user_order"
error: UPDATE "up_users_users_links" as a
              SET "user_order" = b.src_order, "user_order" = b.inv_order
              FROM (
                SELECT "id", ROW_NUMBER() OVER (PARTITION BY "inv_user_id" ORDER BY "user_order") AS src_order, ROW_NUMBER() OVER (PARTITION BY "user_id" ORDER BY "user_order") AS inv_order
                FROM "up_users_users_links"
                WHERE "inv_user_id" = $1 OR "user_id" IN ($2)
              ) AS b
              WHERE b.id = a.id - multiple assignments to same column "user_order"
    at Parser.parseErrorMessage (/Users/paolo/Sites/aaaa/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/paolo/Sites/aaaa/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/paolo/Sites/aaaa/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/paolo/Sites/aaaa/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by flashcatz** [comment]
> I had issues with updating manyToMany relationships and I traced the issue to an invalid SQL query. The issue was that the query was not compatible with MySQL 5.7.36 (the version I was running)
> 
> I updated to Mysql 8 and works perfectly now

Thanks.
It works for me.

**Comment by violabg** [comment]
> Can't reproduce in v4.5.1
> 
> ![image](https://user-images.githubusercontent.com/8593673/202538606-6decdf29-ea27-4ff0-83dd-e563ba945164.png) ![image](https://user-images.githubusercontent.com/8593673/202538624-9a8b97ae-9892-4eac-813d-1fd7e8854a70.png) ![image](https://user-images.githubusercontent.com/8593673/202538638-7e1798d2-06b8-406e-8690-a2a5188eba4d.png) ![image](https://user-images.githubusercontent.com/8593673/202538655-32349b72-2bbd-424e-a0b7-ae4fcdbe8ff9.png)

I have just created a new strapi v4.5.1 project, with no content types, just user permission, with a new empty DB (PostgreSQL 14.6 (Ubuntu 14.6-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit)
and having the same issue, so I guess it is related to posgres db, the error is the same, I'm going to past it just in case, but it should be easy to reproduce if you are using postres

@derrickmehaffy
Did you use Postgres as database?
did you watch the attached video that show how to reproduce the bug?

**Comment by derrickmehaffy** [comment]
I did not but I'll give that a test, thanks for the additional info!

**Comment by violabg** [comment]
Still marked as can reproduce? This is a big problem for our application, since we are not able to save data anymore.

**Comment by Marc-Roig** [comment]
@violabg thank you for the info you provided, we were able to reproduce the issue and we have a PR open to fix this! :) 
The fix should be available in the next release.

**Comment by Marc-Roig** [comment]
@violabg Sorry, unfortunately we merged the fix https://github.com/strapi/strapi/pull/15003 after 4.5.3 release 😞 , it will be released next week on dec 14th.
