### ISSUE TITLE
strapi filtering is not working as intended

### ISSUE THREAD

**Issue by ProfXponent** [strapi/strapi#17351]
## Bug report

This seems like a regression of some kind, as this query was one of my test queries.

https://docs.strapi.io/dev-docs/api/rest/filters-locale-publication#complex-filtering

### Required System information

- Node.js version: 18.16.1
- NPM version: 9.5.1
- Strapi version: 4.11.5
- Database: sqlite
- Operating system: node:18-alpine
- Is your project Javascript or Typescript: js

### Describe the bug

strapi is throwing errors on valid queries that were previously working

### Steps to reproduce the behavior

start with strapi nextjs starter with dataset imported

filter obj

```
{
    '$and': [
        {'category': {'$eq': 'ai'}},
        {'authorsBio': {'$contains': 'Paul'}}
    ]
}
```

query string

```
api/articles?filters[$and][0][category][$eq]=ai&filters[$and][1][authorsBio][$contains]=Paul
```

error

```
Error: Only $and, $or and $not can only be used as root level operators. Found $eq.
```

### Expected behavior

filtered response from strapi api

### Additional context

swagger docs also seem to create an incorrect query string

```
/api/articles?filters%5B%24and%5D[category][$eq]=ai&filters%5B%24and%5D[authorsBio][$contains]=Paul
```

which results in the following error

```
error: value.map is not a function
TypeError: value.map is not a function
```

**Comment by innerdvations** [comment]
I can't find any version of Strapi where it behaved differently. I tried downgrading to several lower versions, and even as low as 4.4.1 seems to produce the same error. Do you know what version produced the expected results?

If the example query is changed to reference a specific field on the relation, for example `?filters[$and][0][category][name][$eq]=ai&filters[$and][1][authorsBio][name][$contains]=Paul` -- it works in 4.11.5 as well as older versions.

@derrickmehaffy I didn't look at the swagger docs, maybe that is being generated incorrectly? Or do you know if filtering on a relation without specifying the attribute was available in a much older version (like v3)?

The error is slightly confusing, because it's not the true "root" but it is referring to the root of the subquery for that relation. For example, `?filters[authorsBio][$or][0][name][$contains]=Paul&filters[authorsBio][$or][0][name][$contains]=Megan` is valid because the root of authorsBio requires $and, $or, or $not.

**Comment by derrickmehaffy** [comment]
> I can't find any version of Strapi where it behaved differently. I tried downgrading to several lower versions, and even as low as 4.4.1 seems to produce the same error. Do you know what version produced the expected results?
> 
> If the example query is changed to reference a specific field on the relation, for example `?filters[$and][0][category][name][$eq]=ai&filters[$and][1][authorsBio][name][$contains]=Paul` -- it works in 4.11.5 as well as older versions.
> 
> @derrickmehaffy I didn't look at the swagger docs, maybe that is being generated incorrectly? Or do you know if filtering on a relation without specifying the attribute was available in a much older version (like v3)?
> 
> The error is slightly confusing, because it's not the true "root" but it is referring to the root of the subquery for that relation. For example, `?filters[authorsBio][$or][0][name][$contains]=Paul&filters[authorsBio][$or][1][name][$contains]=Megan` is valid because the root of authorsBio requires $and, $or, or $not.

Swagger does generate the filters wrong since we don't follow the OpenAPI requirements. OpenAPI/Swagger expects that filters work with `filters=yourfilterparamshere` but since we use LHS bracket syntax OpenAPI doesn't work with those.

**Comment by ProfXponent** [comment]
> I can't find any version of Strapi where it behaved differently. I tried downgrading to several lower versions, and even as low as 4.4.1 seems to produce the same error. Do you know what version produced the expected results?
> 
> If the example query is changed to reference a specific field on the relation, for example `?filters[$and][0][category][name][$eq]=ai&filters[$and][1][authorsBio][name][$contains]=Paul` -- it works in 4.11.5 as well as older versions.
> 
> @derrickmehaffy I didn't look at the swagger docs, maybe that is being generated incorrectly? Or do you know if filtering on a relation without specifying the attribute was available in a much older version (like v3)?
> 
> The error is slightly confusing, because it's not the true "root" but it is referring to the root of the subquery for that relation. For example, `?filters[authorsBio][$or][0][name][$contains]=Paul&filters[authorsBio][$or][1][name][$contains]=Megan` is valid because the root of authorsBio requires $and, $or, or $not.

you're right, this was a regression in my generated client that had some logic for resolving relationships, thanks for taking a look

**Comment by Boegie19** [comment]
Closed since the issue seems to be resolved
