### ISSUE TITLE
Strapi v5 rc: admin ui read entry issue (config2.doc || "").split is not a function

### ISSUE THREAD

**Issue by nasraldin** [strapi/strapi#20655]
### Required System information

- Node.js version: 20
- NPM version: 10
- Strapi version: 5.0.0-rc.0
- Database: Any db provider (SQLite, MySQL, Postgres)
- Operating system: Mac
- Is your project Javascript or Typescript: yes also happens in js

### Describe the bug

The problem began when we migrated from Strapi v4 to v5. Our data, stored as JSON, was easily handled in the old Strapi dashboard UI. However, after creating a new Strapi project in v5 and setting up a test API with a 'name' attribute of type JSON, the data stored in this column is now stringified. This causes an issue when trying to read and render it in the admin dashboard of the new version, resulting in exceptions as shown in the screenshot. Interestingly, the REST API operations continue to function correctly; the problem lies specifically in the admin dashboard's handling of these values.

### Steps to reproduce the behavior

1. Create a new v5 project with any database provider
2. from admin add a new collection type like test and have one attribute name type JSON
3. add some JSON values and save and update this from the database to meet our one old data as is JSON not stringified because Strapi now when you save it will be stringified in DB. From the database update this new entry to have a pure JSON object (as we already have our data as JSON not stringified so we need to read with any modification from the old system db) imaging you have the data seeded

### Expected behavior

Admin UI can render value as in old v4

### Code snippets

`
{
  "kind": "collectionType",
  "collectionName": "tests",
  "info": {
    "singularName": "test",
    "pluralName": "tests",
    "displayName": "test"
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "json"
    }
  }
}`

DB
Saved from Admin UI
row sql `1	u9n4ruiare28wxgcoh1sc6yx	"{\"test\": 134}"	2024-06-28 09:38:32.286	2024-06-28 09:38:32.286	2024-06-28 09:38:32.281	1	1	`

Update the name column value by converting it to a JSON  object to meet our existing data in the old system
`1	u9n4ruiare28wxgcoh1sc6yx	{"test": 134}	2024-06-28 09:38:32.286	2024-06-28 09:38:32.286	2024-06-28 09:38:32.281	1	1`	

### Screenshots

<img width="1417" alt="Screenshot 2024-06-28 at 9 38 31 AM" src="https://github.com/strapi/strapi/assets/9030671/95ef570e-a640-4fda-8965-f71c186aa68a">
<img width="1161" alt="Screenshot 2024-06-28 at 9 38 44 AM" src="https://github.com/strapi/strapi/assets/9030671/1745121a-9204-4fbb-86ad-c13dcd41af68">
Data saved from Admin UI
<img width="992" alt="Screenshot 2024-06-28 at 9 39 17 AM" src="https://github.com/strapi/strapi/assets/9030671/4b86a2e6-68ed-4396-a8d6-99eda6082088">
Update name value to pure JSON object
<img width="1002" alt="Screenshot 2024-06-28 at 9 39 44 AM" src="https://github.com/strapi/strapi/assets/9030671/6c49672a-7c34-4c14-90b3-58d4c4c02d73">
<img width="1486" alt="Screenshot 2024-06-28 at 9 41 02 AM" src="https://github.com/strapi/strapi/assets/9030671/bbe2e592-ee80-474b-aec8-de0c6b4eb67f">

**Comment by nasraldin** [comment]
I hope this is given high priority, as many users encountering issues while migrating their systems from old to new will face this problem. There's no issue when reading through REST or GraphQL APIs, as they can read JSON. However, the problem lies in the admin UI, where JSON is stringified and often saved as a JSON column.

**Comment by AMISH-KHAN** [comment]
I am having this same issue I hope this get fixed soon

**Comment by iamobj** [comment]
+1

**Comment by gfritzdev** [comment]
+1

**Comment by derrickmehaffy** [comment]
Marking as confirmed based on volume of community members seeing this issue (not just here but on Discord as well)

**Comment by nasraldin** [comment]
Hello Team, any updates?

**Comment by nasraldin** [comment]
Is fix released, it semes still exist I have updated to 5.0.0-rc.6 and test but get same issue

**Comment by nasraldin** [comment]
<img width="1377" alt="Screenshot 2024-07-24 at 12 35 33 PM" src="https://github.com/user-attachments/assets/3094a277-385e-4bb9-805b-f83ac1ecc529">

**Comment by itsallaboutthecheddar** [comment]
I fixed this by writing a script to remove the problematic string from the db that was causing strapi not to start, hope this helps someone

`
    // Fix each user's active_sessions
    for (const user of users) {
      try {
        let fixedJson;

        if (typeof user.active_sessions === 'string') {
          try {
            // Try to parse existing JSON
            JSON.parse(user.active_sessions);
            fixedJson = user.active_sessions; // Already valid JSON
          } catch (e) {
            // Not valid JSON, create new structure
            fixedJson = JSON.stringify({
              count: parseInt(user.active_sessions) || 0,
              lastUpdated: new Date().toISOString()
            });
          }
        } else if (typeof user.active_sessions === 'number') {
          fixedJson = JSON.stringify({
            count: user.active_sessions,
            lastUpdated: new Date().toISOString()
          });
        } else if (typeof user.active_sessions === 'object') {
          fixedJson = JSON.stringify(user.active_sessions);
        } else {
          fixedJson = JSON.stringify({
            count: 0,
            lastUpdated: new Date().toISOString()
          });
        }

        // Update the user with fixed JSON, casting to JSONB
        await pool.query(
          'UPDATE up_users SET active_sessions = $1::jsonb WHERE id = $2',
          [fixedJson, user.id]
        );
        console.log(`Fixed active_sessions for user ${user.id}`);
      } catch (error) {
        console.error(`Error fixing user ${user.id}:`, error);
        // Set to default value if error
        const defaultJson = JSON.stringify({
          count: 0,
          lastUpdated: new Date().toISOString()
        });
        await pool.query(
          'UPDATE up_users SET active_sessions = $1::jsonb WHERE id = $2',
          [defaultJson, user.id]
        );
        console.log(`Set default active_sessions for user ${user.id} due to error`);
      }
    }
`

**Comment by Marc-Roig** [comment]
@remidej we should create a migration to address this if its still an issue
