### ISSUE TITLE
@strapi/strapi/lib/services/error missing imports in v4.13 -> v4.20.0

### ISSUE THREAD

**Issue by FlorianUhlmann** [strapi/strapi#19551]
I am updating von strapi  v4.13 -> v4.20.0

my v.4.13 code imports "formatApplicationError"
when updating to v4.20.0 i get a compile error "cannot find module.
I cannot find a hint in the docu, etc. how to import @strapi/strapi/lib/services/errors in v4.20.0

Is there somewhere an upgrade guide?

----------------------------------------
Cannot find module '@strapi/strapi/lib/services/errors' from 'src/middlewares/errors.js'
 
    Require stack:
      src/middlewares/errors.js
      node_modules/@strapi/utils/dist/index.js
      node_modules/@strapi/database/dist/index.js
      node_modules/@strapi/strapi/dist/Strapi.js
      node_modules/@strapi/strapi/dist/index.js
      tests/helpers/strapi.ts
      tests/helpers/index.ts
      tests/plugins/user-permissions.test.ts
 
      3 |   formatApplicationError,
      4 |   formatHttpError,
> 5 | } = require("@strapi/strapi/lib/services/errors");
        |     ^
      6 |

--------------------------------

Here is the original code snippet

const {
  formatApplicationError,
} = require("@strapi/strapi/lib/services/errors");

module.exports = (config, { strapi }) => {
  return async (ctx, next) => {
    try {
      await next();

      if (!ctx.response._explicitStatus) {
        return ctx.notFound();
      }
    } catch (error) {
      if (
        error?.constructor?.name === "ForbiddenError" 
      ) {
        const { status, body } = formatApplicationError(error);
        ctx.status = status;
        ctx.body = body;
        return;
      }
      
      throw error;
    }
  };
};

**Comment by FlorianUhlmann** [comment]
rewritten the issue in a refined bug ticket
