### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl

### ISSUE THREAD

**Issue by Yurgeman** [strapi/strapi#10108]
### Describe the bug

```
yarn run v1.22.10
$ strapi develop
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
  Referenced from: /Users/yura/git/gps/negabarit_teams/strapi/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/yura/git/gps/negabarit_teams/strapi/node_modules/strapi-plugin-responsive-image/node_modules/sharp/build/Release/../../vendor/8.10.0/lib/libvips-cpp.42.dylib

dyld: Symbol not found: _g_once_impl
  Referenced from: /Users/yura/git/gps/negabarit_teams/strapi/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/yura/git/gps/negabarit_teams/strapi/node_modules/strapi-plugin-responsive-image/node_modules/sharp/build/Release/../../vendor/8.10.0/lib/libvips-cpp.42.dylib

✨  Done in 3.48s.
```

### Expected behavior

After upgrade Strapi from 3.5.4 to 3.6.0. And as expected, the `node_modules` folder and the` yarn.lock` file were deleted

```
 strapi                               3.5.4  →   3.6.0     
 strapi-admin                         3.5.4  →   3.6.0     
 strapi-connector-bookshelf           3.5.4  →   3.6.0     
 strapi-plugin-content-manager        3.5.4  →   3.6.0     
 strapi-plugin-content-type-builder   3.5.4  →   3.6.0     
 strapi-plugin-documentation          3.5.4  →   3.6.0     
 strapi-plugin-email                  3.5.4  →   3.6.0     
 strapi-plugin-graphql                3.5.4  →   3.6.0     
 strapi-plugin-sentry                ^3.5.4  →  ^3.6.0     
 strapi-plugin-upload                 3.5.4  →   3.6.0     
 strapi-plugin-users-permissions      3.5.4  →   3.6.0     
 strapi-provider-email-nodemailer    ^3.5.4  →  ^3.6.0     
 strapi-utils                         3.5.4  →   3.6.0  
```
Then `yarn install` & `yarn build --clean` - Ok 
Then `yarn develop` ... and oops, an error popped up

### System

- Node.js version: v14.15.5
- NPM version:6.14.11
- Strapi version:  3.6.0  
- Database: Postgres
- Operating system: macOS Big Sur on Apple MacBook Pro (Apple M1)

**Comment by derrickmehaffy** [comment]
(Can't reproduce this on Linux so I assume it's an Apple ARM issue?)

@pwizla / @markkaylor / @mfrachet / @kasonde can you guys try to reproduce this?

**Comment by pwizla** [comment]
Can't reproduce on my Mac 😅 (M1-based MBP running macOS 11.2.3 "Big Sur")

**Comment by kasonde** [comment]
I can't reproduce this on my mac either. 
> Expected in: /Users/yura/git/gps/negabarit_teams/strapi/node_modules/strapi-plugin-responsive-image/node_modules/sharp/build/Release/../../vendor/8.10.0/lib/libvips-cpp.42.dylib 

@Yurgeman have you considered the state of your application without this plugin?

**Comment by Yurgeman** [comment]
@kabaros  Without this app, strap works perfectly

**Comment by Yurgeman** [comment]
the problem occurred after upgrading to version 3.6.0.
the 3.6.1 version is the same

**Comment by Yurgeman** [comment]
the problem is solved by updating the dependencies. [strapi-plugin-responsive-image](https://github.com/nicolashmln/strapi-plugin-responsive-image)
I made a fork and updated the dependencies - everything worked

```
"sharp": "^0.28.1",
"strapi-plugin-upload": "^3.6.1",
 "strapi-utils": "^3.6.1",
"styled-components": "^5.2.3"
```

**Comment by Yurgeman** [comment]
> the problem is solved by updating the dependencies. [strapi-plugin-responsive-image](https://github.com/nicolashmln/strapi-plugin-responsive-image)
> I made a fork and updated the dependencies - everything worked
> 
> ```
> "sharp": "^0.28.1",
> "strapi-plugin-upload": "^3.6.1",
> "strapi-utils": "^3.6.1",
> "styled-components": "^5.2.3"
> ```

This does not solve the problem with the left menu [#10](https://github.com/nicolashmln/strapi-plugin-responsive-image/issues/10)

**Comment by kasonde** [comment]
> This does not solve the problem with the left menu #10 

Okay. I'll close this issue for now as it seems to be a problem with a plugin that is not created by Strapi. The creator/maintainer of the plugin may be able to help you through the issue you have referenced as well.

**Comment by lulato** [comment]
I am using an Intel Mac on Catalina. I am getting this error from the quick install link
