### ISSUE TITLE
strapi v5 - tries to load .postcssrc.yml from parent folder

### ISSUE THREAD

**Issue by gsouf** [strapi/strapi#23045]
### Node Version

20

### NPM/Yarn/PNPM Version

yarn 1

### Strapi Version

5.10.4

### Operating System

Linux (RedHat/CentOS)

### Database

Other

### Javascript or Typescript

Javascript

### Bug Description

Hi,
I just migrated strapi from v4 to v5. After upgrading to v5, the build phase is failing. If one of the parent directory has a file `.postcssrc.yml` then vite will try to load it, but it will fail has strapi might miss postcss dependencies. 

The problem is that I do not have access to vite config, and I can't configure this behavior.

### Steps to Reproduce

Create a folder, add a `.postcssrc.yml` file with the following content:

```
plugins:
  postcss-import: {}
  postcss-cssnext: {}
```

Create a subfolder with a strapi v5 app in it. 

run `strapi develop`

### Expected Behavior

should run

### Logs

```shell
Error: Loading PostCSS Plugin failed: Cannot find module 'postcss-cssnext'
```

### Additional information

There are various ways to workaround - notably sticking to webpack - removing the postcssrc file - installing postcss dependencies... but they are not acceptable solutions. 

Strapi's vite should be configured (or configurable) so that it does not search for postcss in the parent directory. Unfortunately I'm not familiar with vite, and I'd expect this to work out of the box.

Thanks

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

**Comment by ntd0609** [comment]
@gsouf 
I share you my way resolve this issue

from  here : [admin-panel-customization/bundlers](https://docs-v5.strapi.io/cms/admin-panel-customization/bundlers)
It mean : default [Vite shared-options](https://vite.dev/config/shared-options.html) bundle
Vite has information about 
```
[plugin css.postcss]
Note if an inline config is provided, Vite will not search for other PostCSS config sources.
```
-----------
### admin/vite.config.js
my config : 
```
const { mergeConfig } = require("vite");

module.exports = (config) => {
  // Important: always return the modified config
  return mergeConfig(config, {
    css: {
      postcss: {}
    },
    resolve: {
      alias: {
        "@": "/src"
      }
    }
  });
};
```

**Comment by gsouf** [comment]
activity

**Comment by gsouf** [comment]
activity
