### PR TITLE
Fix: knex withSchema.raw error

### LINKED ISSUE #14832: Cannot save content after upgrading to 4.5.0
### Required System information

- Node.js version: 16.15.0
- Yarn version: 1.22.19
- Strapi version: 4.5.0
- Database: Postgres
- Operating system: MacOs

### Describe the bug

When saving any record of certain content types, I get the following error:

```
TypeError: db.getConnection(...).raw is not a function
    at cleanOrderColumns (/Users/francesco/projects/cpo-strapi/node_modules/@strapi/database/lib/entity-manager/regular-relations.js:248:10)
    at deleteRelations (/Users/francesco/projects/cpo-strapi/node_modules/@strapi/database/lib/entity-manager/regular-relations.js:166:13)
```

Other content types work as expected

Everything was working just fine with previous version (4.4.3)

### Steps to reproduce the behavior

Edit content and try to save it

### Expected behavior

Record should be saved

### PR DESCRIPTION
**Pull request by jhoward1994**
We received a bug report with v4.5.0 for Postgres DBs that are using the `schema` option in `config/database.js`

### What does it do?
fixes #14832

### How to test it?
Follow instructions in #14832 

### Related issue(s)/PR(s)
#14832
closes #14887 - Thank you for the work @zodman 🙏, I just had to make a couple of tweaks

Note: we have decided to not handle multiple PG schemas in this fix to avoid inconsistency. Theres are other places in the codebase where a similar fix will be required. They will all be handled together

<!--
1. We seem to have been using withSchema wrong in `getConnection`.
2. according to the knex docs we should have been using `connection['schema'].withSchema(schema)` not `connection.withSchema(schema)`
3. However even if used correctly that would return a `SchemaBuilder` object as documented at - https://knexjs.org/guide/schema-builder.html
4. SchemaBuilder doesn’t have the functions we use with `getConnection()` such as `[select, insert, del]` etc
5. I therefore think `withSchema` is irrelevant to use in `getConnection` according to the ways the function is used throughout the codebase
6. I have modified `getConnection` to always return the `Knex Query Builder` as this is how it is used throughout the codebase
7. I can now save and modify content type relations using a Postgres DB with schema defined in `examples/getstarted/config/database.js`

@derrickmehaffy @alexandrebodin WDYT?
--!>

<!--
14-11-2022
We are using connection.withSchema(schemaName).raw() from knex in these cases. The connection returned from knex.withSchema contains no raw function. 

The issue is indeed related to the new raw query we introduced. [knex raw query](https://github.com/strapi/strapi/blob/relations-reordering/fractional-orderer/packages/core/database/lib/entity-manager/regular-relations.js#L229)

I am going to raise an issue on Knex to discuss this. In the meantime this change seems to fix the issue.

@alexandrebodin do you know of any side effects this could cause? I've tested the change but am not 100% sure of all the ways our users use PG Schemas
--!>

### CODE REVIEW

File: packages/core/database/lib/index.js [hunk 1]
```diff
@@ -48,9 +48,7 @@ class Database {
   }
 
   getConnection(tableName) {
-    const schema = this.connection.getSchemaName();
-    const connection = tableName ? this.connection(tableName) : this.connection;
-    return schema ? connection.withSchema(schema) : connection;
+    return tableName ? this.connection(tableName) : this.connection;
```
Comment (petersg83) [inline packages/core/database/lib/index.js:51]: Based on what we discussed, I think we should not change the code here and instead use `connection` instead of `getConnection`. WDYT?

**Review by petersg83 — CHANGES_REQUESTED** [review]

File: packages/core/database/lib/entity-manager/regular-relations.js [hunk 2]
```diff
@@ -242,21 +241,27 @@ const cleanOrderColumns = async ({ id, attribute, db, inverseRelIds, transaction
...
-            WHERE b.id = a.id`,
-          [joinTable.name, ...updateBinding, ...selectBinding, joinTable.name, ...whereBinding]
+              SET ${update.join(', ')}
+              FROM (
+                SELECT ${select.join(', ')}
+                FROM ??
+                WHERE ${where.join(' OR ')}
+              ) AS b
+              WHERE b.id = a.id`,
+          [joinTableName, ...updateBinding, ...selectBinding, joinTableName, ...whereBinding]
```
Comment (petersg83) [inline packages/core/database/lib/entity-manager/regular-relations.js:261]: I don't think it works. I think you need to do `??.??` and `[schemaName, joinTableName, ...]` as each argument is either an identifier or a value. `${schemaName}.${joinTableName}` would be 2 identifiers at the same time. Did you try it?

I think you can either: 
- directly put the value in the query, not using the arguments
- don't handle the schema for now, we will do it in another PR anyway as there are other parts of the app that needs to be fixed with the schema

I would suggest the second options so we can also take the time to do it (not doing it during the rush)

Comment (petersg83) [reply packages/core/database/lib/entity-manager/regular-relations.js:261]: Apparently that works indeed! https://knexjs.org/guide/ref.html#ref
Capture d’écran 2022-11-16 à 11 56 05

Good to know. However I would still not do that in that PR for the moment as it would be add some inconsistency

**Review by petersg83 — APPROVED** [review]
LGTM :)

**Comment by zodman** [comment]
@petersg83 then you drop support for running strapi in different schema ?

I have strapi setup in supabase, where the default schema is `public`,  and strapi behind schema `cms`,  what options have?

```
  searchPath: ['postgres', 'cms'],
```

?

**Comment by petersg83** [comment]
@zodman 
No, we discovered yesterday that we have issues with postgres schema since a long time ago. So we will fix all of them for the next patch release (instead of this one).
What Strapi version do you use?

**Comment by zodman** [comment]
@petersg83  2.5.0

**Comment by petersg83** [comment]
Can you check again ? This one doesn't exist :P

**Comment by zodman** [comment]
@petersg83 
```
│ Version            │ 4.5.0 (node v16.15.1)                            │
│ Edition            │ Community            

```

**Comment by alexghattas** [comment]
> @zodman No, we discovered yesterday that we have issues with postgres schema since a long time ago. So we will fix all of them for the next patch release (instead of this one). What Strapi version do you use?

@petersg83 do you have a current fix for this? Do we need to downgrade it? Change something else? This currently leaves our Strapi in a state where we cannot edit any articles in production, any guidance would be greatly appreciated!

**Comment by petersg83** [comment]
Hello @alexghattas :) It's should be fixed in 4.5.2 :)
