### ISSUE TITLE
Strapi 5.20.0 introduces issues with useRBAC hook

### ISSUE THREAD

**Issue by kevinvugts** [strapi/strapi#24074]
### Node Version

20.0.0

### NPM/Yarn/PNPM Version

1.22.22

### Strapi Version

5.20.0

### Operating System

MacOS

### Database

MySQL

### Javascript or Typescript

Typescript

### Bug Description

Since last release (5.20.0) the useRBAC() hook stopped working and errors out on the checkUserHasPermissions function from the useAuth() state. 

``` const { allowedActions, isLoading } = useRBAC(PERMISSIONS);```

Worked in version 5.19.0, broken since last release.

### Steps to Reproduce

1. import useRBAC from "@strapi/strapi/admin"
2. use the hook "  const { allowedActions, isLoading } = useRBAC(PERMISSIONS);"
3. Put in permissions as an array as described by the hook
4. run the app and see the error in console "m is not a function"

Where m is referring to "state.checkUserHasPermissions"

### Expected Behavior

To not break in between minor versions 5.19.0 > 5.20.0

### Logs

```shell

```

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

**Comment by markkaylor** [comment]
Hello @kevinvugts thanks for reporting this issue. I'm struggling to reproduce the issue. Following your instructions I did this to test:

- Create a component for testing
```tsx
import { Button } from '@strapi/design-system'
import { useRBAC } from '@strapi/strapi/admin'

const PERMISSIONS = [
  {
    action: 'plugin::content-manager.explorer.create',
    subject: 'api::test.test',
    properties: {},
    conditions: [],
  }
]


export const Test = () => {
  const { allowedActions } = useRBAC(PERMISSIONS)

  return (
    <Button onClick={() => console.log(allowedActions)}>I'm the TEST!!!!!</Button>
  )
}
```
- Inject the component into the content manager edit view injection zone
```ts
app.getPlugin('content-manager').injectComponent('editView', 'right-links', {
      name: 'Test',
      Component: Test,
    });
```
Then I tested this with a super-admin that has the permissions passed to useRBAC

https://github.com/user-attachments/assets/a5848b54-cda6-4d80-ae04-8633f9a9ca40

Then I tested with an editor that DOES not have the permissions passed to useRBAC

https://github.com/user-attachments/assets/ee2281e0-a186-468b-9628-bd14c1ac1df3

I do not have any error similar to the one you are reporting. The logs demonstrate the permission system and hook appear to be working as expected. 

Could you please provide code examples, screenshots, and/or a video that would help me reproduce the issue?

**Comment by oiorain** [comment]
👋 Hello, and apologies for the confusion!

As part of an automated issue cleanup, this issue was mistakenly closed. That action was unintentional — we're in the process of reviewing and reopening affected issues like this one.

🙏Thank you for your patience, and sorry again for any disruption.

**Comment by kevinvugts** [comment]
@oiorain 

No worries! I am closing this issue as it resolved itself after deep cleaning yarn's cache. 
Sometimes it still happens, but after clearing the cache everything resolves itself.

Thanks anyways!
