### PR TITLE
chore(upload): promote the new media library out of future/

### PR DESCRIPTION
**Pull request by Adzouz**
### What does it do?

Second and final step of the Media Library GA work: the `future/` tree stops being "future" and becomes the plugin's default admin tree, and everything pre-revamp moves into `legacy/`.

```
packages/core/upload/admin/src/
├── App.tsx  components/  hooks/  pages/Assets/
├── services/  store/  types/  utils/          ← was future/, promoted verbatim
├── pages/SettingsPage/         ← ships in both modes, stays
├── legacy/
│   ├── pages/App/
│   ├── components/  hooks/  utils/  ai/
├── constants.ts  enums.ts  pluginId.ts
├── utils/typeFromMime.ts  translations/       ← shared by both trees
```

- **`future/*` promoted to the root of `admin/src`**, unchanged. 167 files.
- **`ai/`, `components/`, `hooks/`, `pages/`, `utils/` moved to `legacy/`.** This is the pre-revamp stack.
- **`utils/typeFromMime.ts` stays at the root** — both trees use it.
- **Imports rewritten mechanically.** Every relative specifier was resolved against the old tree, mapped through the move table, and recomputed from the new location: 223 specifiers across 147 files. Everything else in the moved files is byte-identical.
- **e2e mirrors the same split**: `tests/e2e/tests/media-library/future/*` → the domain root, `cancel-deletion.spec.ts` → `tests/e2e/tests/media-library/legacy/`. No CI change needed — both jobs already pass `domains: media-library`.
- **Stale naming the move exposed**, all of it internal to the upload plugin:
  - `BetaMediaLibrary` → `MediaLibrary`
  - a `useTracking` doc comment that pointed at `src/future`

**Scope note — `legacy/` is wider than the legacy Media Library page.** It also holds the Content Manager **media field picker** (`MediaLibraryDialog`, `MediaLibraryInput`) and the ~109 files it shares with the old page. The picker ships in the default configuration and was never part of the revamp, so `legacy/` here means *not yet rewritten*, not *unused*. Only 21 files are reachable from the legacy page alone; the rest are picker infrastructure and cannot move independently while the picker imports them.

The alternative — a third top-level folder for the picker — was considered and dropped: the picker is itself due to be rewritten into the new tree, so a dedicated folder would mean moving those files twice. This way `legacy/` shrinks with each rewrite.

**`legacy/` is not deletable wholesale, and the layout says so.** Of its 138 source files, only **21 leave** when the flag is removed — `legacy/pages/App/**` including `ConfigureTheView`, plus six strays (`ai/components/*`, `components/BulkMoveDialog`, `components/FolderCard/FolderCardCheckbox`, `hooks/useBulkEdit`, `hooks/useBulkMove`, `hooks/useAiAvailability`). The other 117 are picker infrastructure. There are no orphans.

`pages/SettingsPage/` therefore sits **outside** `legacy/`: it is registered unconditionally, the revamp does not replace it, and it must survive the day the legacy tree goes.

**Two import lines were doing most of the coupling.** `legacy/utils/index.ts` is a barrel, so a single `import { getTrad }` from it pulled all 20 legacy utils and, behind `urlsToAssets`, the legacy `UploadAssetDialog`. `constants.ts`, `index.ts`, `SettingsPage.tsx` and `useAIMetadataJob.ts` now use the root `utils/translations` helper instead — the same one-liner the new tree already had, so nothing is duplicated:

| graph | before | after |
| --- | --- | --- |
| new Media Library (`App.tsx`) | 125 files, **32 in `legacy/`** | 93 files, **0 in `legacy/`** |
| settings page | 46 files, **33 in `legacy/`** | 13 files, **2 in `legacy/`** |

`useAIMetadataJob.ts` moved to `pages/SettingsPage/` — it was the only file in `legacy/` used exclusively by the settings page. The two that remain, `legacy/hooks/useSettings` and `legacy/hooks/useTracking`, are genuinely shared with the picker (`useTracking` has 13 importers), and `useTracking` cannot move to root anyway: the new tree already has its own `hooks/useTracking.ts`. Those resolve when the picker is rewritten, not before.

**The settings page keeps the legacy tracking hook, on purpose.** It fires one event, `didGenerateMetadataRetroactively`. The root `hooks/useTracking.ts` stamps `mediaLibraryVersion: 'v2'` so analytics can tell the new Media Library page's events from the old one's; this page is neither — it is registered unconditionally and renders identically in both modes. Tagging it `v2` would make apps running `useLegacyMediaLibrary: true` emit `v2` settings events, defeating the filter the tag exists for. Swapping hooks would also move this page from react-query to RTK Query for its settings read, which is a behavioural change rather than a rename.
### Why is it needed?

The new Media Library became the default in #27606, but it still lived under a directory called `future/` while the thing it replaced occupied the canonical paths. Anyone opening `admin/src/components/` landed in the old stack by default.

This is the follow-up half of that work: default code sits at the default path, superseded code is named as such, and what is left in `legacy/` is a visible, shrinking list of what still needs rewriting.

### How to test it?

Nothing changes at runtime — this is a move plus import rewrites. What needs checking is that both Media Libraries and the media field still load.

```bash
yarn build
cd examples/getstarted && yarn develop
```

1. **Media Library** (default) — assets list, folders, upload, details drawer, drag & drop.
2. **Legacy Media Library** — set `useLegacyMediaLibrary: true` in `config/features.js`, restart, confirm the old page renders and there is still exactly one Media Library entry in the menu.
3. **Media field picker** — open any entry with a media field, add an asset through the dialog. This is the surface that moved into `legacy/` while still shipping by default.

Automated, all run locally on this branch:

```bash
yarn test:front                                    # all green
yarn nx build @strapi/upload                       # dist/ shows legacy/, no future/
E2E_MEDIA_LIBRARY=current yarn test:e2e --domains media-library    # 32 passed, 12 skipped
USE_LEGACY_MEDIA_LIBRARY=true E2E_MEDIA_LIBRARY=legacy \
  yarn test:e2e --domains media-library                           # 1 passed, 43 skipped
yarn test:e2e --domains content-manager                           # 131 passed (exercises the picker)
```

### Related issue(s)/PR(s)

- Follow-up to #27606 (`feat(upload): make the new Media Library the default`), which shipped the flag flip. CMS-1576 covers both halves and is already closed by that PR, so no magic word here.
- **Conflicts with #27275** — it adds `tests/e2e/tests/media-library/future/media-library-organize.spec.ts` and edits the page object, both of which move here. Whichever lands second needs a rebase.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by jhoward1994** [comment]
### `tests/e2e/tests/admin/home.spec.ts:8`

This import still points at the deleted `future/` path and breaks the entire CE/EE E2E  matrix (Playwright fails at collection with `Cannot find module '../media-library/future/page-objects/AssetsPage'`, which aborts every shard/browser

that's why the domain-scoped `e2e media library` jobs pass but the full matrix is red). The page object moved to `tests/e2e/tests/media-library/page-objects/AssetsPage.ts`,  so this needs to be:

 ```ts
 import { AssetsPage } from '../media-library/page-objects/AssetsPage';
 ```

**Comment by giu1io** [comment]
@Adzouz E2E are broken ☹️ 

**1. All 24 e2e shards (CE + EE × chromium/firefox/webkit) — caused by this PR**

`tests/e2e/tests/admin/home.spec.ts:8` still imports the pre-move path:

```ts
import { AssetsPage } from '../media-library/future/page-objects/AssetsPage';
```

The file now lives at `tests/e2e/tests/media-library/page-objects/AssetsPage.ts`, and `media-library/future/` is gone on the branch. `home.spec.ts` isn't in the PR's changed files, so it got missed by the rename.

Playwright fails at collection time, so every shard aborts with **0 tests run** — that's why they all fail identically, and why the two media-library-specific jobs (which don't load `home.spec.ts`) pass.

One-line fix:

```ts
import { AssetsPage } from '../media-library/page-objects/AssetsPage';
```

I grepped the branch — that's the only stale `media-library/future` reference left.

**Review by giu1io — DISMISSED** [review]
## QA — passed ✅

### What QA covered

| Area                                          | Result                                                   |
| --------------------------------------------- | -------------------------------------------------------- |
| Promoted Media Library as default             | loads, navigates, drawer opens                           |
| Legacy library behind `useLegacyMediaLibrary` | returns correctly when flag flipped                      |
| **Data survival across the gate flip**        | **byte-for-byte across 9 tables**                        |
| Restart over pre-existing data                | assets/folders survive and re-render                     |
| CE build (EE forced off)                      | boots clean, 333 chunks, no unresolved `strapi-admin/ee` |
| CM media field picker                         | renders from `legacy/`, attaches and persists            |
| Media Library settings                        | loads, saves, takes effect                               |
| Upload progress dialog                        | renders, survives navigation, rejects blocked type       |
| Asset download                                | object URL created and revoked                           |
| Upload permission                             | create enforced server-side (403, no row)                |

The restructure is mechanically sound: every dynamic-import target resolves at runtime,
which is the failure mode static review can't close (a wrong target is a blank pane at
navigation, not a build error). Package provenance was proven into the pinned checkout
for every app — no published package resolved.

**Comment by Adzouz** [comment]
Hey @giu1io, I made two other adjustments:
- the Settings page will remain in the default folder since it won't change
- removed calls to the legacy utils to better isolate legacy folder

File: packages/core/upload/admin/src/pages/SettingsPage/SettingsPage.tsx [hunk 1]
```diff
@@ -32,13 +32,13 @@ import { AIMetadataJob } from '../../../../shared/contracts/ai-metadata-jobs';
 import { GetAIMetadataPendingCount, CreateAIMetadataJob } from '../../../../shared/contracts/files';
 import { UpdateSettings } from '../../../../shared/contracts/settings';
 import { PERMISSIONS } from '../../constants';
-import { useAIMetadataJob } from '../../hooks/useAIMetadataJob';
-import { useSettings } from '../../hooks/useSettings';
-import { useTracking } from '../../hooks/useTracking';
-import { getTrad } from '../../utils';
+import { useSettings } from '../../legacy/hooks/useSettings';
+import { useTracking } from '../../legacy/hooks/useTracking';
```
Comment (giu1io) [inline packages/core/upload/admin/src/pages/SettingsPage/SettingsPage.tsx:35]: **The settings page is out of `legacy/`, but still reaches back into it for two hooks.**

```ts
import { useSettings } from '../../legacy/hooks/useSettings';
import { useTracking } from '../../legacy/hooks/useTracking';
```

`useAIMetadataJob` got pulled across in the follow-up commit; these two didn't. The CLAUDE.md you added is honest about it ("even though its imports still reach into `legacy/`"), so this is a known state, not an oversight.

`useTracking` in particular is interesting: there's a non-legacy `hooks/useTracking.ts` at the root whose own comment says events from `legacy/` omit a flag so analytics can filter new-library usage. Worth checking that the settings page is emitting under the identity you want, since it's no longer conceptually part of `legacy/`.

_Generated by Claude, edited by me._

File: packages/core/upload/admin/src/pages/SettingsPage/SettingsPage.tsx [hunk 2]
```diff
@@ -32,13 +32,13 @@ import { AIMetadataJob } from '../../../../shared/contracts/ai-metadata-jobs';
...
+import { getTranslationKey } from '../../utils/translations';
 
 import { init } from './init';
 import { initialState, reducer } from './reducer';
+import { useAIMetadataJob } from './useAIMetadataJob';
```
Comment (giu1io) [inline packages/core/upload/admin/src/pages/SettingsPage/SettingsPage.tsx:40]: **Stale TODO at the top of this file** (line 1 — not in the diff, so commenting here instead).

```ts
// TODO: find a better naming convention for the file that was an index file before
```

This file is no longer an index file, and the move already renamed it to `SettingsPage.tsx` — which *is* the better naming convention the TODO was asking for. It's resolved; the comment just wasn't noticed during the move.

The same line sits at the top of `tests/SettingsPage.test.tsx`. Worth dropping both.

_Generated by Claude, edited by me._

**Review by giu1io — COMMENTED** [review]
2 minor comments added. Thanks 🙏

File: packages/core/upload/admin/src/pages/SettingsPage/SettingsPage.tsx (hunk 1 above)
Comment (Adzouz) [reply packages/core/upload/admin/src/pages/SettingsPage/SettingsPage.tsx:35]: Good question, and I want to answer it rather than leave it implicit — I'm keeping both hooks where they are, deliberately.

This page fires exactly one event, `didGenerateMetadataRetroactively` (line 415). The only functional difference between the two wrappers is that the root one stamps `mediaLibraryVersion: 'v2'`, and its own doc comment says what that is for:

> Events from `legacy/` omit it, so analytics can filter new usage from the old plan while both trees emit the SAME event names.

So the tag answers "which Media Library **page** produced this event". The settings page is not either one — it is registered unconditionally in `index.ts`, it renders identically whichever library is selected, and the revamp does not replace it. Stamping it `v2` would mean an app running `useLegacyMediaLibrary: true` emits `v2` settings events, which corrupts exactly the filter the tag exists for. Untagged in both modes is the consistent reading.

There is a second reason not to swap: the two wrappers read settings from different places — `useSettings` (react-query) versus `useGetUploadSettingsQuery` (RTK Query). Switching would be a behavioural change to how this page fetches, not a rename.

`useAIMetadataJob` moved because it was used by this page and nothing else. `useSettings` and `useTracking` are genuinely shared — `useTracking` has 13 importers across `EditAssetDialog`, `UploadAssetDialog`, `AssetDialog` and `EditFolderDialog` — so moving them would relabel picker code rather than decouple anything. `useTracking` also cannot come to the root at all while the new tree has its own `hooks/useTracking.ts` under that name.

Net: the file's physical location changed, the identity its event should carry did not. Both resolve when the picker is rewritten. I have added this to the PR description so it is not buried in a thread.

File: packages/core/upload/admin/src/pages/SettingsPage/SettingsPage.tsx (hunk 2 above)
Comment (Adzouz) [reply packages/core/upload/admin/src/pages/SettingsPage/SettingsPage.tsx:40]: Good catch — removed from both files in 49703ec.

One thing worth flagging: that exact line is on **29 files** in this package. The other 27 are all under `legacy/` — `AssetDialog`, `BrowseStep`, `TableList`, `FilterList`, `UploadProgress`, `SortPicker`, `App.tsx` and friends. All equally stale, none of them index files any more.

I have only removed the two this PR actually touches. Sweeping the other 27 would add unrelated files to a diff that is already ~430 renames, and it would be invisible noise in the review. Happy to do it as a one-line follow-up PR if you want it gone.

File: packages/core/upload/admin/src/CLAUDE.md [hunk 3]
```diff
@@ -0,0 +1,34 @@
+# Media Library (admin)
```
Comment (jhoward1994) [inline packages/core/upload/admin/src/CLAUDE.md]: This is the only nested CLAUDE.md file. Should we really add this ?

Comment (jhoward1994) [reply packages/core/upload/admin/src/CLAUDE.md]: Same thought for the docs at `packages/core/upload/admin/src/docs/`. I can see how thats helpful but I dont think it's a process we're following in any other package ? should we start doing that here ?

Comment (Adzouz) [reply packages/core/upload/admin/src/CLAUDE.md]: You're right it's not the purpose of this PR, I'll remove them and will keep that locally or in the brain instead

**Comment by Adzouz** [comment]
@jhoward1994 Files removed + PR on the brain opened 🙏

**Review by jhoward1994 — APPROVED** [review]
