### ISSUE TITLE
Cannot install strapi-plugin-generate-data when updagraded to strapi 4.5.2.

### ISSUE THREAD

**Issue by abhishek1020N** [strapi/strapi#15018]
### Required System information

- Node.js version: 16.15.0
- NPM version: 8.5.5
- Strapi version: 4.5.2
- Database: pg 12
- Operating system: windows 10

### Describe the bug
When upgraded to strapi 4.5.2 npm i strapi-plugin-generate-data throws error. error TS2307: Cannot find module '@strapi/design-system/Box' or its corresponding type declarations

**note: npm i strapi-plugin-generate-data works with strapi 4.5.1.**

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by kasonde** [comment]
Please open this on the plugin creator's Github issues in order for them to be aware of their plugins incompatibility with newer versions of Strapi.
