### PR TITLE
Fix ML

### LINKED ISSUE #8603: MediaLibrary error after upgrading to 3.3.0
Just upgraded to 3.3.0  from 3.2.5. Everything seem to work, except Media Library. Opening it from the admin UI generates an error. My provider is `strapi-provider-upload-aws-s3`.

Node v12.18.2
npm v6.14.5
PostgreSQL 12

Here is the error:

```
2020-11-09T18:00:42: [2020-11-09T18:00:42.263Z] debug GET /upload/files/count? (26 ms) 200
2020-11-09T18:00:42: [2020-11-09T18:00:42.268Z] error TypeError: Target.query is not a function
    at app/node_modules/bookshelf/lib/eager.js:62:23
    at app/node_modules/bookshelf/node_modules/lodash/lodash.js:3543:27
    at app/node_modules/bookshelf/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (app/node_modules/bookshelf/node_modules/lodash/lodash.js:2990:24)
    at app/node_modules/bookshelf/node_modules/lodash/lodash.js:4894:18
    at baseMap (app/node_modules/bookshelf/node_modules/lodash/lodash.js:3542:7)
    at Function.map (app/node_modules/bookshelf/node_modules/lodash/lodash.js:9580:14)
    at EagerRelation.morphToFetch (app/node_modules/bookshelf/lib/eager.js:56:9)
    at EagerRelation.eagerFetch (app/node_modules/bookshelf/lib/eager.js:25:19)
    at EagerRelation.<anonymous> (app/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at app/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
    at EagerRelation._eagerLoadHelper (app/node_modules/bookshelf/lib/eager.js:83:23)
    at Sync.<anonymous> (app/node_modules/bookshelf/lib/eager.js:31:31)
From previous event:
    at EagerRelation.eagerFetch (app/node_modules/bookshelf/lib/eager.js:31:8)
    at EagerRelation.<anonymous> (app/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at Child._handleEager (app/node_modules/bookshelf/lib/collection.js:527:73)
    at Child.<anonymous> (app/node_modules/bookshelf/lib/collection.js:179:27)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
From previous event:
    at Child.<anonymous> (app/node_modules/bookshelf/lib/collection.js:177:12)
From previous event:
    at Child.fetchAll (app/node_modules/bookshelf/lib/model.js:878:10)
    at Object.find (app/node_modules/strapi-connector-bookshelf/lib/queries.js:66:8)
    at fn (app/node_modules/strapi-database/lib/queries/helpers.js:31:54)
    at Object.find (app/node_modules/strapi-database/lib/queries/helpers.js:15:24)
    at async find (app/node_modules/strapi-plugin-upload/controllers/upload/admin.js:39:19)
    at async app/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
2020-11-09T18:00:42: [2020-11-09T18:00:42.269Z] debug GET /upload/files?_limit=10&_start=0&_sort=updated_at:DESC (35 ms) 500
```

EDIT:  Pardon me, I added the line before and after the error exposing the successful /upload/count before the failed /upload/files.

### PR DESCRIPTION
**Pull request by alexandrebodin**
Signed-off-by: Alexandre Bodin <bodin.alex@gmail.com>

### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

fix #8603

### CODE REVIEW

**Review by derrickmehaffy — APPROVED** [review]

**Review by lauriejim — APPROVED** [review]
LGMT
