### ISSUE TITLE
Error when update from v5.11 to v5.12

### ISSUE THREAD

**Issue by brucexmas** [strapi/strapi#23298]
```
TypeError: defPropValFN is not a function
    at shouldForwardProp (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-PO76HLLD.js?v=c00db254:5145:72)
    at http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-HYQFDUV4.js?v=c00db254:1203:172
    at O2 (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-HYQFDUV4.js?v=c00db254:1211:6)
    at renderWithHooks (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-AWHRF5BE.js?v=c00db254:11548:26)
    at updateForwardRef (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-AWHRF5BE.js?v=c00db254:14325:28)
    at beginWork (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-AWHRF5BE.js?v=c00db254:15946:22)
    at beginWork$1 (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-AWHRF5BE.js?v=c00db254:19753:22)
    at performUnitOfWork (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-AWHRF5BE.js?v=c00db254:19198:20)
    at workLoopSync (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-AWHRF5BE.js?v=c00db254:19137:13)
    at renderRootSync (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-AWHRF5BE.js?v=c00db254:19116:15)
```
