### ISSUE TITLE
Admin Page Blank: _typeof is not a function

### ISSUE THREAD

**Issue by birunidev** [strapi/strapi#9482]
# Workaround

See: https://github.com/strapi/strapi/issues/9482#issuecomment-783797102

# Workaround

Hello everyone 👋 

I want to report a bug that I faced this morning. I tried installing strapi yesterday using npx create-strapi-app and it worked just fine. then this morning I tried again using the same way and I face this issue.

![Screenshot_1](https://user-images.githubusercontent.com/50983566/108787476-730b2d80-75a8-11eb-8d40-eb116d140eda.png)

## Bug report
Admin Page Blank: _typeof is not a function

### Describe the bug

The admin page is blank but the index page is fine. 

### Steps to reproduce the behavior

1. Install strapi
2. Go to /admin
3. See error

### Expected behavior

After installing strapi usually, the admin page will let you create an account for admin but now it's just blank page

When I see the browser console I saw this error

![strapi error](https://user-images.githubusercontent.com/50983566/108787324-1740a480-75a8-11eb-91d8-18878fa70f35.png)

- Node.js version: v.12.19.0
- NPM version: 6.14.8
- Strapi version: 3.5.0
- Database: sqlite3
- Operating system: Windows 10

**Comment by erenbertr** [comment]
Getting same error after upgrading from 3.4.0 to 3.5.0 with node v14.15.3. Tried locally (mac) also on server (ubuntu).

I removed node_modules, .cache and build folder and run develop command (also build && start) but nothing works for now. The api is working but I can't access to admin panel.

**Comment by GreenCamper** [comment]
Same error here, trying Strapi quick start guide for the first time.
New blank folder on local machine.
Node.js version: v14.15.5
NPM version: 6.14.11
Strapi version: 3.5.0
Database: sqlite3
Operating system: macOS 10.15.6

**Comment by erenbertr** [comment]
Maybe this is also related with https://github.com/babel/babel/issues/12853

**Comment by derrickmehaffy** [comment]
I was able to confirm this on all operating systems (Linux, Mac, Windows) on both v3.5.0 and v3.4.6

**Comment by hzoo** [comment]
@erenbertr should be the case! We're finishing up a release now, hopefully should fix it soon

**Comment by derrickmehaffy** [comment]
I'm testing a yarn resolutions workaround right now

**Comment by derrickmehaffy** [comment]
> @erenbertr should be the case! We're finishing up a release now, hopefully should fix it soon

Thank you @hzoo

**Comment by hzoo** [comment]
But yes that should work too ^

```
"resolutions": {
  "**/@babel/core": "7.12.17"
}
```

https://github.com/formium/tsdx/issues/977

**Comment by derrickmehaffy** [comment]
### Workaround

In your project's package.json set the following resolutions (if you are using yarn)

```
"resolutions": {
    "@babel/runtime": "7.12.5"
  },
```
  
Here is an example package.json:

```json
{
  "name": "test-node",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "strapi": "3.5.0",
    "strapi-admin": "3.5.0",
    "strapi-utils": "3.5.0",
    "strapi-plugin-content-type-builder": "3.5.0",
    "strapi-plugin-content-manager": "3.5.0",
    "strapi-plugin-users-permissions": "3.5.0",
    "strapi-plugin-email": "3.5.0",
    "strapi-plugin-upload": "3.5.0",
    "strapi-connector-bookshelf": "3.5.0",
    "knex": "<0.20.0",
    "sqlite3": "5.0.0"
  },
  "resolutions": {
    "@babel/runtime": "7.12.5"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "8dee434d-3aa0-415a-9e04-15bda07b9e4d"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": "^6.0.0"
  },
  "license": "MIT"
}
```

After that rerun a yarn install and rebuild your admin panel

**Comment by derrickmehaffy** [comment]
Related babel PR: https://github.com/babel/babel/pull/12855 for fix

**Comment by hzoo** [comment]
Ah it published when I posted, it should be fixed if you try again https://github.com/babel/babel/releases/tag/v7.13.1

**Comment by erenbertr** [comment]
I made this change.

Removed node_modules, build and .cache folders also deleted package-lock.json too, after that run develop and still getting this error.

On package.json the version for babel/runtime is 7.13.1
![image](https://user-images.githubusercontent.com/3104911/108791310-0b8cb800-757f-11eb-93b8-b7d679a1c3a0.png)

**Comment by derrickmehaffy** [comment]
I can confirm the issue still exists on v7.13.1

**Comment by derrickmehaffy** [comment]
@hzoo might be a bit out of your scope, but if you want to test with your team you are welcome to spin up a strapi project.

`npx create-strapi-app@latest test-project --quickstart`

**Comment by nicolo-ribaudo** [comment]
@derrickmehaffy Thanks!
I'm trying to reproduce this on 7.13.1.

**Comment by derrickmehaffy** [comment]
Once you generate the project it will automatically start a browser tab to register a user, you'll see the error there.

**Comment by nicolo-ribaudo** [comment]
Ok I'm working on this.

**Comment by nicolo-ribaudo** [comment]
Will release the fix as soon as CI on babel/babel#12858 is green

**Comment by derrickmehaffy** [comment]
> Will release the fix as soon as CI on [babel/babel#12858](https://github.com/babel/babel/pull/12858) is green

Yup watching :) as soon as I see it hit the npm registry I'll do another test. Thank you!

**Comment by nicolo-ribaudo** [comment]
You can watch in real time at https://github.com/babel/babel/actions/runs/591130900 :smile:

**Comment by erenbertr** [comment]
03:00 AM and nothing else matters. 🎵

**Comment by nicolo-ribaudo** [comment]
03:00 AM for me too :musical_note: :joy:

**Comment by derrickmehaffy** [comment]
7pm here in Arizona :laughing:

**Comment by derrickmehaffy** [comment]
The rest of the Strapi team are in Paris fast asleep

**Comment by derrickmehaffy** [comment]
Btw @nicolo-ribaudo huge thank you to the babel team for pushing out a fix so fast <3

**Comment by derrickmehaffy** [comment]
Now to wait for the American NPM registry to sync.... :clock1:

**Comment by nicolo-ribaudo** [comment]
Well, sorry for breaking strapi!

`@babel/runtime` was just published as 7.13.2. I forgot to publish `@babel/runtime-corejs3` (doing it now), but it shouldn't affect you.

_Friendly reminder to all the companies whose build was broken by this bug: it's because you rely on strapi and Babel, so you could consider sponsoring us!_ :smile: 
(https://opencollective.com/strapi, https://github.com/sponsors/babel)

**Comment by derrickmehaffy** [comment]
I will absolutely talk to our team about supporting you guys <3

**Comment by derrickmehaffy** [comment]
Can confirm that `@babel/runtime` v7.13.2 fixed the issue. Marking as closed.

**Comment by nicolo-ribaudo** [comment]
Good, it's time to sleep for me then :joy:

**Comment by derrickmehaffy** [comment]
Have a good rest Nicolo and you too @hzoo

**Comment by ajohnson10209** [comment]
I created a duplicate of this issue and I can confirm everything is working now! You will see no issues after installing strapi. Thanks for your hard work guys!

**Comment by nicolo-ribaudo** [comment]
@derrickmehaffy Sorry to bump an old closed issue, but I just noticed that Strapi started sponsoring Babel and I wanted to thank you!

**Comment by derrickmehaffy** [comment]
Quite welcome @nicolo-ribaudo, I made the suggestion when we started talking about StrapiConf and who would contribute to. There will be a major announcement for it in our keynote in the [StrapiConf](https://conf.strapi.io/) on April 22nd ;)

cc @vcoisne / @pierreburgy
