### ISSUE TITLE
Cannot find module 'strapi-utils'

### ISSUE THREAD

**Issue by Aylay** [strapi/strapi#10488]
## Bug report
Same bug  here : #4672
But the fix doesn't work.

### Describe the bug
I have installed strapi with DO MarketPlace
I'm using strapi-utils into one of my controllers
It's working on local with the same version of Strapi and Strapi packages (3.6.3) but not on the DO server
```
"dependencies": {
    "knex": "0.21.18",
    "pg": "8.5.1",
    "strapi": "3.6.3",
    "strapi-admin": "3.6.3",
    "strapi-connector-bookshelf": "3.6.3",
    "strapi-plugin-content-manager": "3.6.3",
    "strapi-plugin-content-type-builder": "3.6.3",
    "strapi-plugin-email": "3.6.3",
    "strapi-plugin-graphql": "3.6.3",
    "strapi-plugin-i18n": "3.6.3",
    "strapi-plugin-upload": "3.6.3",
    "strapi-plugin-users-permissions": "3.6.3",
    "strapi-utils": "^3.6.3"
  },
```

I tried to clean cache, delete node_modules and reinstall

### Errors
```
0|strapi-development  | [2021-06-15T15:25:38.223Z] debug ⛔️ Server wasn't able to start properly.
0|strapi-development  | [2021-06-15T15:25:38.225Z] error Error: Cannot find module 'strapi-utils'
0|strapi-development  | Require stack:
0|strapi-development  | - /srv/strapi/preprod-admin/api/categorie/controllers/categorie.js
0|strapi-development  | - /srv/strapi/strapi-development/node_modules/strapi/lib/load/load-files.js
0|strapi-development  | - /srv/strapi/strapi-development/node_modules/strapi/lib/core/load-apis.js
0|strapi-development  | - /srv/strapi/strapi-development/node_modules/strapi/lib/core/load-modules.js
0|strapi-development  | - /srv/strapi/strapi-development/node_modules/strapi/lib/Strapi.js
0|strapi-development  | - /srv/strapi/strapi-development/node_modules/strapi/lib/index.js
0|strapi-development  | - /srv/strapi/strapi-development/node_modules/strapi/lib/commands/develop.js
0|strapi-development  | - /srv/strapi/strapi-development/node_modules/strapi/bin/strapi.js
0|strapi-development  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
0|strapi-development  |     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
0|strapi-development  |     at Module.require (internal/modules/cjs/loader.js:1025:19)
0|strapi-development  |     at require (internal/modules/cjs/helpers.js:72:18)
0|strapi-development  |     at Object.<anonymous> (/srv/strapi/preprod-admin/api/categorie/controllers/categorie.js:8:28)
0|strapi-development  |     at Module._compile (internal/modules/cjs/loader.js:1137:30)
0|strapi-development  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
0|strapi-development  |     at Module.load (internal/modules/cjs/loader.js:985:32)
0|strapi-development  |     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
0|strapi-development  |     at Module.require (internal/modules/cjs/loader.js:1025:19)
```

Please help me :)

**Comment by derrickmehaffy** [comment]
You do not need to specify that package directly in your package.json as it is a required depency of our own packages. Try removing it from your package.json, deleting your node_modules and any package-lock.json/yarn.lock then reinstall your modules and try again.

**Comment by Aylay** [comment]
@derrickmehaffy,
I deleted my node_modules, package-lock.json and yarn.lock.
I removed the line of strapi-utils in package.json
I reinstall my modules
I build the admin

And I have the same issue :'(

**Comment by Aylay** [comment]
So, I succeed ! 

BUT, it's not the solution !

I cloned my repo into my DO server
I create a symbolic link between the strapi-utils package on the node_module of the cloned repo into the /strapi-development/ folder and It's working :/

**Comment by gautamkrishnar** [comment]
@derrickmehaffy i just got this issue on one of our open source projects when we migrated from v3 to v4, we used `@strapi/codemods` to migrate. Here is the source code in which you can reproduce this issue: https://github.com/Kites-Foundation/hellomunnar-cms/tree/v4migration

I used ndoe js version 14.17.0

**Comment by genocideaon** [comment]
> 

I saw you still use `const { sanitizeEntity } = require('strapi-utils');`
Still response `Cannot find module 'strapi-utils'`

**Comment by gautamkrishnar** [comment]
@genocideaon thanks a lot for the suggestion. Will fix it and try to update it according to the latest docs.
