### ISSUE TITLE
Webpack module not found after updating to 4.0.5 from 4.0.4

### ISSUE THREAD

**Issue by Ramon404** [strapi/strapi#12258]
Good day,

After updating to 4.0.5 from 4.0.4 I'm getting the following error when trying to run the build command:

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

129 | Error: Cannot find module 'webpack'
130 | Require stack:
131 | - /codebuild/output/src473324480/src/node_modules/webpackbar/dist/webpackbar.js
132 | - /codebuild/output/src473324480/src/node_modules/@strapi/admin/webpack.config.js
133 | - /codebuild/output/src473324480/src/node_modules/@strapi/admin/index.js
134 | - /codebuild/output/src473324480/src/node_modules/@strapi/strapi/lib/commands/build.js
135 | - /codebuild/output/src473324480/src/node_modules/@strapi/strapi/bin/strapi.js
136 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
137 | at Function.Module._load (internal/modules/cjs/loader.js:667:27)
138 | at Module.require (internal/modules/cjs/loader.js:887:19)
139 | at require (internal/modules/cjs/helpers.js:74:18)
140 | at Object.<anonymous> (/codebuild/output/src473324480/src/node_modules/webpackbar/dist/webpackbar.js:3:17)
141 | at Module._compile (internal/modules/cjs/loader.js:999:30)
142 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
143 | at Module.load (internal/modules/cjs/loader.js:863:32)
144 | at Function.Module._load (internal/modules/cjs/loader.js:708:14)
145 | at Module.require (internal/modules/cjs/loader.js:887:19)
```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
