### ISSUE TITLE
Dynamic Zones: "map" as a field name causes script error

### ISSUE THREAD

**Issue by dacatchman** [strapi/strapi#15480]
### Required System information

- Node.js version: 16
- NPM version: 8.19
- Strapi version: 4.5.6
- Database: mysql
- Operating system: rhel 8

### Describe the bug

Since upgrading from 4.4.3, I cannot use the field name "map" in a dynamic zone.

### Steps to reproduce the behavior

1. Create a dynamic zone in the content-type editor.  Add it to some collection.
2. In my case, I my DZ component is a single relationship to some other collection called simply: "map"
3. Go back to content editor with your field/collection with the above DZ.  Try to open any record to edit it.  You should receive the generic "Whoops something went wrong" error
4. See error in console (map is not a function):

main.eb002160.js:951 TypeError: (0 , Y.get)(...).map is not a function
    at content-manager.2db90b74.chunk.js:70:15265
    at Object.useMemo (main.eb002160.js:949:60660)
    at a.useMemo (main.eb002160.js:974:5789)
    at Td (content-manager.2db90b74.chunk.js:70:15240)
    at content-manager.2db90b74.chunk.js:70:14879
    at Yu (main.eb002160.js:949:54503)
    at Ia (main.eb002160.js:953:9099)
    at St (main.eb002160.js:953:987)
    at ge (main.eb002160.js:953:915)
    at le (main.eb002160.js:953:767)

5. (optional) If you rename the field from map to something else, and the problem is resolved.

### Expected behavior

Well, this did not give the script error prior to 4.5.  I don't care in particular for the name "map," but you should at least add "map" to reserved words (like id is for content editor fields otherwise) when creating dynamic zones/components to avoid the error and confusion.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by jhoward1994** [comment]
Hi @dacatchman , I'm afraid I was unable to reproduce this issue but perhaps there's something I've missed (see video of my setup). Are you able to test the issue again and provide more information?


https://user-images.githubusercontent.com/48524071/223684614-ff0ff1d4-ec51-4d28-8496-1c8c1656deb9.mov


Thanks
