### ISSUE TITLE
v4.15.1 upgrade: Cannot find module esbuild after installing new deps

### ISSUE THREAD

**Issue by mirkonasato** [strapi/strapi#18656]
### Required System information

- Node.js version: `v20.9.0`
- NPM version: `10.2.2`
- Strapi version: `4.15.1`
- Database: sqlite
- Operating system: `macOS 14.1`
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

After upgrading an existing Strapi project to v4.15.1, trying to build it with `npm run build` stops at this prompt

```
[INFO] The Strapi admin needs to install the following dependencies: 
   - react@^18.0.0
  - react-dom@^18.0.0
  - react-router-dom@^5.0.0
  - styled-components@^5.0.0
? Would you like to install these dependencies now? These are not required but are recommended, from V5 these will be 
required.
```

Accepting the default _Yes_ then results in the following error:
```
[INFO] Running 'npm install --legacy-peer-deps --save react@^18.0.0 react-dom@^18.0.0 react-router-dom@^5.0.0 styled-components@^5.0.0'

added 6 packages, removed 3 packages, changed 2 packages, and audited 1315 packages in 2s

161 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module 'esbuild'
Require stack:
- /Users/mirko/Projects/my-project/node_modules/esbuild-register/dist/node.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/admin/dist/cli.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/admin/index.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/action.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/command.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/commands/index.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/cli.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/strapi/bin/strapi.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/mirko/Projects/my-project/node_modules/esbuild-register/dist/node.js:4653:16)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mirko/Projects/my-project/node_modules/esbuild-register/dist/node.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/admin/dist/cli.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/admin/index.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/action.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/command.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/commands/index.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/cli.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/strapi/bin/strapi.js'
  ]
}

Node.js v20.9.0
[ERROR] Command failed with exit code 1: /Users/mirko/.nvm/versions/node/v20.9.0/bin/node /Users/mirko/Projects/my-project/node_modules/.bin/strapi build
```

Same if trying to `npm run build` again.

### Steps to reproduce the behavior

1. Create an "old" Strapi v4.15.0 project with `npx create-strapi-app@4.15.0 my-project --quickstart`
2. Edit `package.json` and replace `4.15.0` with `4.15.1` for all `@strapi/*` dependencies
3. Run `npm install`. This works fine:
```added 48 packages, removed 138 packages, changed 29 packages, and audited 1312 packages in 1m```
4. Try building the project with `npm run build`. This fails with the problem described above.

### Expected behavior

It should be possible to upgrade an existing project from `4.15.0` to `4.15.1` and build it without errors.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by mirkonasato** [comment]
Additionally, because the new version automatically installs the new dependencies with `--legacy-peer-deps`, trying to run `npm install` without it will then fail as well
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @strapi/plugin-i18n@4.15.1
npm ERR! Found: styled-components@5.3.11
npm ERR! node_modules/styled-components
npm ERR!   styled-components@"^5.3.11" from the root project
npm ERR!   peer styled-components@"^5.2.1" from @strapi/design-system@1.13.0
npm ERR!   node_modules/@strapi/design-system
npm ERR!     @strapi/design-system@"1.13.0" from @strapi/admin@4.15.1
npm ERR!     node_modules/@strapi/admin
npm ERR!       @strapi/admin@"4.15.1" from @strapi/strapi@4.15.1
npm ERR!     peer @strapi/design-system@"1.13.0" from @strapi/helper-plugin@4.15.1
npm ERR!     node_modules/@strapi/helper-plugin
npm ERR!       @strapi/helper-plugin@"4.15.1" from @strapi/admin@4.15.1
npm ERR!       node_modules/@strapi/admin
npm ERR!         @strapi/admin@"4.15.1" from @strapi/strapi@4.15.1
npm ERR!       5 more (@strapi/plugin-content-type-builder, ...)
npm ERR!     5 more (@strapi/plugin-content-type-builder, ...)
npm ERR!   2 more (@strapi/helper-plugin, babel-plugin-styled-components)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer styled-components@"5.3.3" from @strapi/plugin-i18n@4.15.1
npm ERR! node_modules/@strapi/plugin-i18n
npm ERR!   @strapi/plugin-i18n@"4.15.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: styled-components@5.3.3
npm ERR! node_modules/styled-components
npm ERR!   peer styled-components@"5.3.3" from @strapi/plugin-i18n@4.15.1
npm ERR!   node_modules/@strapi/plugin-i18n
npm ERR!     @strapi/plugin-i18n@"4.15.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by ciriousjoker** [comment]
Everything works perfectly, when discard the changes done by strapi and install the dependencies manually without the dangerous `--legacy-peer-deps`. Only difference is I needed to take `"react-router-dom": "^5.3.4",`, earlier versions didn't install.

**Comment by ciriousjoker** [comment]
Nevermind, I was able to install it and "bypass" this error, but literally everything else is broken. How is that even possible, I went from 4.15.0 to 4.15.1, that's a single patch version.

**The following stuff broke:**
- calendar plugin
- notes plugin
- update static contents plugin
- app version plugin (how even??)
- CKEditor 5 (official version) crashed
- some routes crash

honestly, wtf, better not update guys

**Comment by LucaNerlich** [comment]
I had to delete `node_modules` and install again. However, I then get the error from this bug https://github.com/strapi/strapi/issues/18649 ...

**Comment by ciriousjoker** [comment]
> I had to delete `node_modules` and install again. However, I then get the error from this bug https://github.com/strapi/strapi/issues/18649 ...

You can fix that by removing env and importing it directly as mentioned in that issue. Let me know if you manage to get a working installation running with some plugins

**Comment by LucaNerlich** [comment]
> You can fix that by removing env and importing it directly as mentioned in that issue. Let me know if you manage to get a working installation running with some plugins

I do not. Now getting this error during strapi build for my custom plugin (in which I had to do a similar "fix" for the webpack import in `src/admin/webpack.config.js`

![image](https://github.com/strapi/strapi/assets/5942270/ef823be6-5a1a-4674-bf8d-402e6c704241)

However, I am now getting this issue:

![image](https://github.com/strapi/strapi/assets/5942270/5915d022-7661-46b1-b3f7-3c0aeae5298e)

Either the logged path is wrong, or strapi for some reason creates a path without slashes :/

**Comment by joshuaellis** [comment]
Thanks for the helpful reproduction steps @mirkonasato 👍🏼 I'll work on getting a fix out for the next release.

**Comment by joshuaellis** [comment]
We have an experimental I believe should solve this issue if you'd like to validate – `0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336`

**Comment by mirkonasato** [comment]
No issues when "upgrading" from `v4.15.0` to the `experimental` with `npm`.
