### PR TITLE
fix(admin): build pipeline & deps

### LINKED ISSUE #18652: create-strapi-app --quickstart fails with unable to resolve dependency tree
### Required System information

- Node.js version: `v20.9.0`
- NPM version: `10.2.2`
- Strapi version: `4.15.1`
- Database: sqlite
- Operating system: `macOS 14.1`
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

Creating a new Strapi project fails due to dependency issues.

### Steps to reproduce the behavior

1. Run `npx create-strapi-app@latest my-project --quickstart` as per [Quick Start Guide ](https://docs.strapi.io/dev-docs/quick-start)
2. There is no step 2. Step 1 fails with 
```
% npx create-strapi-app@latest my-project --quickstart
Creating a quickstart project.
Creating a new Strapi application at /Users/mirko/Projects/my-project.
Creating files.
Error while installing dependencies:
npm WARN config production Use `--omit=dev` instead.
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config 
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-project@0.1.0
npm ERR! Found: styled-components@5.3.3
npm ERR! node_modules/styled-components
npm ERR!   styled-components@"5.3.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer styled-components@"^5.3.6" from @strapi/plugin-cloud@4.15.1
npm ERR! node_modules/@strapi/plugin-cloud
npm ERR!   @strapi/plugin-cloud@"4.15.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Expected behavior

`npm install` should complete without errors.

### Code snippets

If applicable, add code samples to help explain your problem.

### LINKED ISSUE #18656: v4.15.1 upgrade: Cannot find module esbuild after installing new deps
### Required System information

- Node.js version: `v20.9.0`
- NPM version: `10.2.2`
- Strapi version: `4.15.1`
- Database: sqlite
- Operating system: `macOS 14.1`
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

After upgrading an existing Strapi project to v4.15.1, trying to build it with `npm run build` stops at this prompt

```
[INFO] The Strapi admin needs to install the following dependencies: 
   - react@^18.0.0
  - react-dom@^18.0.0
  - react-router-dom@^5.0.0
  - styled-components@^5.0.0
? Would you like to install these dependencies now? These are not required but are recommended, from V5 these will be 
required.
```

Accepting the default _Yes_ then results in the following error:
```
[INFO] Running 'npm install --legacy-peer-deps --save react@^18.0.0 react-dom@^18.0.0 react-router-dom@^5.0.0 styled-components@^5.0.0'

added 6 packages, removed 3 packages, changed 2 packages, and audited 1315 packages in 2s

161 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module 'esbuild'
Require stack:
- /Users/mirko/Projects/my-project/node_modules/esbuild-register/dist/node.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/admin/dist/cli.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/admin/index.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/action.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/command.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/commands/index.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/cli.js
- /Users/mirko/Projects/my-project/node_modules/@strapi/strapi/bin/strapi.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/mirko/Projects/my-project/node_modules/esbuild-register/dist/node.js:4653:16)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mirko/Projects/my-project/node_modules/esbuild-register/dist/node.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/admin/dist/_chunks/index-86dfbe3a.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/admin/dist/cli.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/admin/index.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/action.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/command.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/commands/index.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/strapi/dist/cli.js',
    '/Users/mirko/Projects/my-project/node_modules/@strapi/strapi/bin/strapi.js'
  ]
}

Node.js v20.9.0
[ERROR] Command failed with exit code 1: /Users/mirko/.nvm/versions/node/v20.9.0/bin/node /Users/mirko/Projects/my-project/node_modules/.bin/strapi build
```

Same if trying to `npm run build` again.

### Steps to reproduce the behavior

1. Create an "old" Strapi v4.15.0 project with `npx create-strapi-app@4.15.0 my-project --quickstart`
2. Edit `package.json` and replace `4.15.0` with `4.15.1` for all `@strapi/*` dependencies
3. Run `npm install`. This works fine:
```added 48 packages, removed 138 packages, changed 29 packages, and audited 1312 packages in 1m```
4. Try building the project with `npm run build`. This fails with the problem described above.

### Expected behavior

It should be possible to upgrade an existing project from `4.15.0` to `4.15.1` and build it without errors.

### Code snippets

If applicable, add code samples to help explain your problem.

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* adds `esbuild` as a dep to the `admin` package
* sets peerDeps to match the `design-system` which is lower than what we were targeting incl. on templates so all packages are aligned
* re-exports admin from the strapi package and no longer tries to include the core plugins on a user app level

### Why is it needed?

* upgrading projects couldn't resolve esbuild
* peer dep issues in npm projects
* it's NPM specific but the admin package is not at the same level in the node_modules so you can't import it. Because a user has `@strapi/strapi` declared, we might as well use that and re-export it. We can also import the core plugins there meaning we're another step closer to PNPM working.

### How to test it?

* install a project at `4.15.0`
* upgrade to experimental manually
* experimental build –> `0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336`
* should build sucessfully

### Related issue(s)/PR(s)

* resolves #18656
* resolves #18652

### CODE REVIEW

**Comment by joshuaellis** [comment]
I actually think this fixes #15992

**Review by alexandrebodin — APPROVED** [review]
