### ISSUE TITLE
Cannot read properties of undefined (reading 'tours')

### ISSUE THREAD

**Issue by piumikaDil** [strapi/strapi#25130]
Something went wrong
It seems like there is a bug in your instance, but we've got you covered. Please notify your technical team so they can investigate the source of the problem and report the issue to us by opening a bug report on 
[Strapi's GitHub](https://github.com/strapi/strapi/issues/new?assignees=&labels=&projects=&template=BUG_REPORT.md)
.
Cannot read properties of undefined (reading 'tours')

<img width="767" height="622" alt="Image" src="https://github.com/user-attachments/assets/da528329-08b1-466a-9212-47b1eea889da" />

**Comment by Nikerty** [comment]
I believe this is a bug with the new (5.33.0) version of Strapi. Rolling back to previous versions (I rolled back to 5.31.2) fixed this error for me

**Comment by PickleRick1** [comment]
The bug exists from 5.31 to 5.32 for sure. It can only be fixed if you change the version and don't push anything else.
If someone fixed it, please tell me how.

**Comment by english-ra** [comment]
Hi @piumikaDil @Dtower79 @shahid-greychain

Do you have any recreation steps for what caused this? What did you navigate to / click on for this to error?

**Comment by Exudev** [comment]
Hi team! 
I've been following this discussion and I'd like to help investigate and fix this issue. From the comments, it seems like this is affecting versions 5.31.x through 5.33.0.

What I'd like to do:
1. First, reproduce the error by testing the affected versions
2. Compare the codebase between 5.30.x (working) and 5.31.0 (broken) to identify what changed
3. Look specifically at tour-related code and how state is being managed
4. Propose a fix once I've identified the root cause

Could I be assigned to this issue?, I'm happy to coordinate with @english-ra and anyone else working on the related issues (#25158, #25207).

If anyone has additional reproduction steps or insights, that would be super helpful!

**Comment by markkaylor** [comment]
Hello, I've seen this bug reported before but never with a report that respects our issue template. Usually we close the issue if it doesn't respect the template. Could you please update your issue description to follow our template? I have tried to reproduce this issue before but I was unable to do so. Steps to reproduce are crucial to resolving bugs. 

You might also try clearing this local storage item `STRAPI_GUIDED_TOUR`

@Exudev a PR would be very welcome if you find the problem. You can ping me for a review.

**Comment by PickleRick1** [comment]
@Exudev 
Today the build also crashed with this error at a random moment. 
version 5.33.3. 
locally and local build are normal. 
Content Manager crashes into infinite loading. There are two errors in the console - Uncaught (in promise) TypeError: p is not a function and TypeError: Cannot read properties of undefined (reading 'tours'). 
content builder - Cannot read properties of undefined (reading 'tours')
media library - m is not a function
But the API itself works, it doesn't allow you to work specifically with the admin panel as a regular user.
Later it might crash again, and a new upgrade might not be released in time.
If you don't push anything, it works stably.

**Comment by karankarakoti** [comment]
Facing same issue, does anyone found a solution?
my dependecies are 
"dependencies": {
    "@strapi-community/cloudinary-media-library": "^1.0.3",
    "@strapi/plugin-cloud": "5.33.2",
    "@strapi/plugin-users-permissions": "5.33.2",
    "@strapi/provider-email-nodemailer": "^5.33.2",
    "@strapi/provider-upload-cloudinary": "^5.33.2",
    "@strapi/strapi": "5.33.2",
    "nodemailer": "^7.0.12",
    "pg": "8.8.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "strapi-v5-plugin-populate-deep": "^4.0.5",
    "styled-components": "^6.0.0"
  },

**Comment by KevinDanielDev** [comment]
Hi everyone,

I wanted to share how I managed to solve the common and frustrating errors like TypeError: p is not a function and Rollup build failures (e.g., "useAIAvailability" is not exported) while working with Strapi v5.33.3 in a Dockerized environment.

**_The Problem_**

These errors are usually not bugs in the code itself, but rather dependency tree conflicts. In Strapi 5, certain internal packages or peer dependencies (like React or Styled Components) might have slight version mismatches. When npm install fails to resolve these perfectly, it creates a "poisoned" node_modules. Subsequently, the bundler (Vite/Rollup) generates a corrupt JavaScript bundle where functions are undefined, leading to the "p is not a function" error in the browser.

_**The Solution**_

The solution is to force a clean installation by bypassing strict peer dependency checks. This ensures all Strapi 5 components are installed despite minor version conflicts.

**1. Perform a Deep Clean: Delete node_modules, package-lock.json, .cache, and the dist folder.**

**2. Force Installation: Use the --legacy-peer-deps flag to allow the installation to proceed.**

**npm install --legacy-peer-deps**

**_Current Work-in-Progress: Media Upload JSON Error_**

While the Admin Panel is now fully operational, I am currently debugging an issue when uploading media: Unexpected token '<', "<html>... is not valid JSON".

This indicates the server is returning an HTML error page (likely a 413 Payload Too Large from Nginx, or a 500 error regarding folder permissions) instead of the expected JSON. I am currently auditing my middlewares.js and checking the public/uploads folder permissions. I will post an update once I've cleared this final hurdle.

I hope this helps anyone stuck in the v5 migration process!

**Reference: My Configuration**

  "dependencies": {
        "@strapi/plugin-cloud": "5.33.3",
        "@strapi/plugin-users-permissions": "5.33.3",
        "@strapi/strapi": "5.33.3",
        "fs-extra": "^10.0.0",
        "mime-types": "^2.1.27",
        "pg": "8.8.0",
        "react": "^18.0.0",
        "react-dom": "^18.0.0",
        "react-router-dom": "^6.0.0",
        "styled-components": "^6.0.0"
      },


_DockerFile_

FROM node:22-alpine

RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/app

COPY package.json package-lock.json ./

RUN npm install -g node-gyp
RUN npm config set fetch-retry-maxtimeout 600000 && npm i --legacy-peer-deps

COPY . .

RUN chown -R node:node /opt/app

USER node

RUN npm run build

EXPOSE 1337

CMD [ "npm", "start" ]

**Comment by innerdvations** [comment]
Fixed by https://github.com/strapi/strapi/pull/25290

**Comment by enriqueaf** [comment]
Just adding my comment here, as I was following this same error, and for us the solution, is detailed here https://github.com/strapi/strapi/issues/24760#issuecomment-4005147813 but was mainly adding a direct dependency of @strapi/admin to our package.json, same version as @strapi/strapi

**Comment by tobatha** [comment]
it's still happening with the latest version @5.42.1

```
TypeError: Cannot read properties of undefined (reading 'tours')
    at EW (https://edu.nebulight.one/admin/index-DG7IN2Zp.js:608:2034)
    at UI (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:201:386)
    at Yht (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:217:10141)
    at rTe (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:219:12126)
    at yJ (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:236:2167)
    at BTe (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:232:22546)
    at bmt (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:232:22119)
    at P$ (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:232:21867)
    at mJ (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:232:18336)
    at DTe (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:232:17875)
```

also with Media library -> uploads

```
TypeError: Cannot read properties of undefined (reading 'sort')
    at https://edu.nebulight.one/admin/App-CBp9qKBw.js:110:5833
    at K1 (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:219:23308)
    at jpt (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:232:13204)
    at Upt (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:232:12950)
    at $pt (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:232:12856)
    at Bpt (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:232:12732)
    at Tmt (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:232:25246)
    at I_ (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:232:24900)
    at https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:232:23989
    at fe (https://edu.nebulight.one/admin/strapi-B2F_Jw63.js:120:2136)
```

**Comment by rodrigosebastiao** [comment]
**Fixed**.
I also had this issue 4 months ago with pure NPM but don't remember what I did to fix it.
Now I was just trying to fix inside Docker and was about to ask here. Then it worked.
Things like --force or --legacy-peer-deps changed to wrong deps and caused worse problems.
Made it several times ```rm -rf node_modules package-lock.json && npm install``` and started to edit dependencies.

Until my package.json:

```
"dependencies": {
    "@strapi/plugin-cloud": "5.45.1", // was behind @"5.45.0"
    "@strapi/plugin-users-permissions": "5.45.1", // was behind @"5.45.0"
    "@strapi/provider-upload-aws-s3": "5.45.1", // was already ahead @"5.45.1" causing problems
    "@strapi/strapi": "5.45.1", // was behind @"5.45.0"
    ...
}
```
