### PR TITLE
fix(admin): admin build errors

### LINKED ISSUE #18719: Local Plugin  in 14.15.2 got Module not found: Error: Can't resolve
### Required System information
- Node.js version: 18.18.2
- NPM version:  8.19.1 
- Strapi version: 14.15.2 and 14.14.6
- Database: sqlite
- Operating system: window 11
- Is your project Javascript or Typescript: javascript

### Describe the bug

app.js  generated wrong path for local plugin in ./strapi/client 

### Steps to reproduce the behavior

1. Create plugins via cli
2. Update pluigin.js 
image
3.. Run yarn build or strapi develop --watch-admin
5. Error
image
image
image

### Expected behavior
Plugin should load correctly

### LINKED ISSUE #18723: Build Error on upgrade from 4.15.0: TypeError: userConfig is not a function
- Node.js version: v18.14.2
- NPM version: 9.5.0
- Strapi version: 4.15.2
- Database: MySQL (MariaDB)
- Operating system: OS (Sonoma 14.1)
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Trying to upgrade a 4.15.0 project to 4.15.2 and get the following: 

```⠋ Building build context
⠙ Building build context[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (245.1411640010774ms)
⠋ Building admin panel
⠸ Building admin <MYPROJECT DIR>/node_modules/@strapi/admin/dist/_chunks/index-cce8ecb6.js:694
    return userConfig(config, webpack2);
           



TypeError: userConfig is not a function
    at mergeConfigWithUserConfig <MYPROJECT DIR>/node_modules/@strapi/admin/dist/_chunks/index-cce8ecb6.js:694:12)
    at async /<MYPROJECT DIR>/node_modules/@strapi/admin/dist/_chunks/index-cce8ecb6.js:721:23
```

### Steps to reproduce the behavior

1. update package.json from 4.15.0 to 4.15.2 (not sure what other starting points would cause this)
2. yarn install
3. yarn build

### Expected behavior

Installs and builds successfully

### Screenshots

N/A

### Code snippets

N/A

### LINKED ISSUE #18742: App.js with wrong path to plugin
## Bug report

App.js with wrong path to plugin, after upgrading to 4.15.2

Strapi Version: 4.15.2

### Describe the bug

When running the yarn build command I receive the following error:

Module not found: Error: Can't resolve '....srcpluginsvideo-uploader/strapi-admin'

The path to the plugin is always generated without any /

Note: the plugin is a auto generated by strapi generate

Import in the app.js:
import videoUploader from "....srcpluginsvideo-uploader/strapi-admin";

### LINKED ISSUE #18752: strapi Admin: /admin/me endpoint :  Interface language show available language list, and unknown http error
### Required System information
- Node.js version:  v18.16.0 and v20
- NPM version: 9.5.1
- Strapi version:4.15.4
- Database:  postgres/ sqlite
- Operating system:  Windows 10/ WSL ubuntu 18.04/ WSL ubuntu 20.04
- Is your project Javascript or Typescript: Javascript AND TypeScript

### Describe the bug

to be brief:  admin's interface language list error with 4.15.4,  but ok with 4.13.7 / 4.14.6

When I try to configure the interface language (zh-CN and fr-FR) of strapi admin panel, I've followed instructions on the official document, made modifications in src/admin/app.tsx, but the interface language list has always only one element "English".  
And the /admin/me endpoint does not works correctly when I try to modify my firstname and lastname by returning unknown error. 

I've checked the strapi forum and stackoverflow,  I've tried lot of combinaisons, javascript/ typescript, node 18 and 20 in windows and node 18 and 20 in WSL ubuntu 18 and 20.  

Finally, I've created a strapi app at v4.13.7 in cli,   the interface language shows up with a perfect list where I got all my expected languages, and interface language changed after selection of another language and save. 

### Steps to reproduce the behavior
1. create a strapi app at latest version (4.15.4)  with npm or yarn
    - any config will reproduce the error.   js or ts,  postgres or sqlite,  in windows 10 or in ubuntu linux
2.  create /src/admin/app.tsx  by modify the name of /src/admin/app.example.tsx   
    - in javascript case,   make a /src/admin/app.js
3. modify the above app.tsx / app.js with an array of languages you like  
    - in my case locales: ["fr", "zh-Hans", "zh"]
4. npm run build, or   yarn build
5. yarn develop    or  yarn develop  --watch-admin
6. open the admin panel at   http://localhost:1337/admin/me
    - you'll need to create a superadmin account before enter into this page. 
7. at the bottom of the /admin/me page,   in the "interface language",   there is only  "English"  available. 

### Expected behavior

I've configured 3 mores languages in /src/admin/app.tsx,  so I should have :  zh-CN,  zh-CN-Hans,  fr-FR in the list. 

### Screenshots

image

### Code snippets
in src/admin/app.tsx
```
export default {
  config: {
    locales: ["zh", "zh-CN", "zh-CN-Hans", "fr"],
  },
  bootstrap() {},
};
```

### Additional context

I've tested almost all combinaison: 
- js/ts,  windows/linux,   node 18/20,  linux 18/20, 
- add one more plugin with:  npm install @strapi/plugin-i18n
- build the tsx type by : npm run strapi ts:generate-types --debug
- rebuild with yarn build or npm run build
- rebuild after removing node_modules and .strapi
- start project with yarn develop  or  yarn develop --watch-admin

any of the above cant't resolve the situation.  

but by downgrading to v4.13.7,  it works well.   ┓( ´∀` )┏  
I've also tested  4.14.6,  it's also good.

### LINKED ISSUE #18758: Admin panel customization via config object in ./src/admin/app.js not working anymore
### Required System information
Environment: development
OS: win32-x64
Strapi Version: 4.15.4
Node/Yarn Version: npm/10.2.3 node/v20.9.0 win32 x64 workspaces/false
Edition: Community
Database: sqlite
- Is your project Javascript or Typescript: Javascript (started from npx create-strapi-app@latest my-project)

### Describe the bug

As described in https://docs.strapi.io/dev-docs/admin-panel-customization#extending-translations one can customize the Admin panel texts as well add locales, I had it working in a prior version of strapi, but now it doesn't anymore, so the text remain the same is the original ones, like a step of loading and using the config object has been skipped, or has this customization method changed and hasn't been documented yet?

### Steps to reproduce the behavior
Content app.js
const config = {
  locales: ["nl"],
  translations: {
    en: {
      "Auth.form.welcome.title": "Welcome to Company Back Office",
      "Auth.form.welcome.subtitle": "Log in to your Company account",
      "app.components.LeftMenu.navbrand.title": "Company ",
      "app.components.LeftMenu.navbrand.workplace": "Dashboard",
    },
    nl: {
      "Auth.form.welcome.title": "Welkom bij Company Back Office",
      "Auth.form.welcome.subtitle": "Inloggen met je Company account",      
      "app.components.LeftMenu.navbrand.title": "Company ",
      "app.components.LeftMenu.navbrand.workplace": "Dashboard",
    },
  },
};

const bootstrap = (app) => {
  console.log(app);
};

export default {
  config,
  bootstrap,
};

### Expected behavior

That the interface would show the texts in the config in stead of the strapi language.json files

Kind Regards
Bart

### LINKED ISSUE #18762: after update to strapi 4.15.4 -> i18n installed but no language except english is in the backend selectable
### Required System information

- Node.js version: v20.5.1
- NPM version: 9.8.0
- Strapi version: 4.15.4
- Database: mysql
- Operating system: Ubuntu Linux
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

Only english is in the personal profile selectable. In strapi 4.15.0 I installed the i18n package and uncommented under src/admin/app.js the wanted locales. But now, under 4.15.4 is only English selectable. If I select English, strapi shows also an error. 

### Steps to reproduce the behavior

1. Go to your personal profil on left side
2. Click on your name
3. Choose "Profile"
4. Click on "Interface Language"
5. Only English appears

### Expected behavior

Like in 4.15.0 I want to see the uncommented languages by src/admin/app.js

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* adds `app.js` as an import argument to the `renderAdmin` function
* checks that the user webpack config is a typeof function otherwise show an error explaining
* converts system paths to node_module paths so local plugins work on windows

### Why is it needed?

* App customisations were not applied to user apps
* users were reporting that their `webpack user config` was not a function but being called as such
* local plugin paths on windows were broken

### Related issue(s)/PR(s)

* resolves #18758
* resolves #18762
* resolves #18723
* resolves #18719
* resolves #18742
* resolves #18752

### CODE REVIEW

**Review by gu-stav — APPROVED** [review]

**Comment by derrickmehaffy** [comment]
@Boegie19 was testing alpha.2 on Windows and still hits the issue in #18719 

image
