### ISSUE TITLE
Or queries

### ISSUE THREAD

**Issue by Cedric-Lefebvre** [strapi/strapi#4293]
Hi, I'm trying to do a search on multiple columns but I cannot get it to work, and there is a big lack of documentation on the custom queries part.

Cannot do any OR queries on multi-columns.

I tried different way to adapt my query: 

```const results = await strapi.query(table).find({street_eq: 'example', number_eq: '55'});```
=> behave as a AND

```const results = strapi
      .query(function(qb) {
        qb
          .where('street', 'example');
          .orWhere('number','55');
      })
      .fetchAll();
```
=> doesn't work

Is there and actual way to create complex queries like that? And I think I've seen a `search` to use instead of the `find`, but could not see how to use it.

**System**
- Node.js version: 10.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.17.1
- Database: SQLite
- Operating system: Ubuntu

Thanks for you help.

**Comment by lauriejim** [comment]
Hello @Cedric-Lefebvre !
I found the documentation example pretty clear [here](https://strapi.io/documentation/3.0.0-beta.x/concepts/queries.html#custom-queries).

In your code snippet, you just forgot the `.model` before the query.
It was documented.

```
const data =await strapi.query('address').model.query(function(qb) {
    qb
      .where('street', 'example')
      .orWhere('number','55');
  })
  .fetchAll();

console.log('> data');
console.log(data.toJSON());
```

**Comment by sharmarahul17** [comment]
This code is not working in latest version of Strapi (3.1.4)

Getting error: api/controllers/module.searchTypeError: strapi.query(...).model.query is not a function

My Code:
await strapi
        .query("violation")
        .model.query((qb) => {
          qb.where(note_contains, searchText).orWhere(
            ticketNumber_contains,
            searchText
          );
        })
        .fetchAll();

**Comment by derrickmehaffy** [comment]
@sharmarahul17 you will want to refer to the bookshelf or mongoose documentation, per the custom queries doc: https://strapi.io/documentation/v3.x/concepts/queries.html#custom-queries

**Comment by sharmarahul17** [comment]
@derrickmehaffy , Thank you for the reply. I am already trying to refer the custom queries documentation.

Now I made the code more simpler but getting same error.

Code : 
`await strapi
        .query("violation")
        .model.query((qb) => {
          qb.where(note, searchText);
        })
        .fetch();`

Error : `api/controllers/module.searchTypeError: strapi.query(...).model.query is not a function`

**Comment by derrickmehaffy** [comment]
Can you open up a new [discussion thread](https://github.com/strapi/strapi/discussions) so we don't resurrect an old bug report from a year ago :pray:

**Comment by sharmarahul17** [comment]
Thank you @derrickmehaffy 

I have opened a new issue for this. https://github.com/strapi/strapi/issues/7677
