### ISSUE TITLE
Can't access admin UI after update to 3.6.0

### ISSUE THREAD

**Issue by d2kx** [strapi/strapi#10106]
### Describe the bug

I have upgraded our Strapi installation from 3.5.4 to 3.6.0, also adding the i18n plugin and setting

STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE=de

for the initial start. Building the UI didn't throw any errors and the instance seemed to start just fine, with the healthcheck at the / path also working just fine. However, after trying to login with my credentials at /admin, I get this (see screenshot below):

```
Uncaught (in promise) TypeError: o is not a function
    at main.e955958c.chunk.js:1

TypeError: Cannot read property 'userPermissions' of undefined
    at g (main.e955958c.chunk.js:1)

An error has occured
main.e955958c.chunk.js:1 TypeError: Cannot read property 'userPermissions' of undefined
    at g (main.e955958c.chunk.js:1)

Here is some infos
main.e955958c.chunk.js:1 
{componentStack: "↵    in f↵    in div↵    in styled.div↵    in vf↵ …IntlProvider↵    in n↵    in w↵    in Yh↵    in c"}
componentStack: "\n    in f\n    in div\n    in styled.div\n    in vf\n    in qt\n    in n\n    in w\n    in injectIntl(Connect(n))\n    in t\n    in d\n    in t\n    in div\n    in styled.div\n    in div\n    in styled.div\n    in Unknown\n    in s\n    in k\n    in w\n    in t\n    in t\n    in IntlProvider\n    in n\n    in w\n    in Yh\n    in c"
__proto__: Object
```

Removing the i18n plugin, rebuilding and restarting did not seem to work either. Unfortunately, due to us needing the installation for work, I have already rolled back to 3.5.4 which is working again.

### Steps to reproduce the behavior

- Upgrade Strapi installation from 3.5.4 to 3.6.0 while using the German language (in case that is relevant due to the i18n additions)
- try to login at /admin
- boom

### Expected behavior

Be able to access admin UI

### Screenshots

![image](https://user-images.githubusercontent.com/4834966/115764869-5b80d300-a3a6-11eb-80b7-566706ed8382.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 12 LTS
- NPM version: 6.14.12
- Strapi version: 3.6.0
- Database: Amazon Aurora MySQL 5.6
- Operating system: Ubuntu 20.04 LTS

### Additional context

I have upgraded Strapi from 3.0 onwards, following the migration guides and never had a problem like this.

**Comment by philliprognerud** [comment]
I also cant access admin console, trying to debug whats going on

**Comment by MattieBelt** [comment]
Any admin extensions that could conflict with the update?
https://strapi.io/documentation/developer-docs/latest/update-migration-guides/update-version.html#extensions

**Comment by soupette** [comment]
Hello!
I tried to reproduce your issue, did you make sure to :
1. Rebuild your admin panel
2. Followed the migration guide

@philliprognerud & @d2kx can you provide me with a github repository that I can check?
You can DM on Slack or our new discord server, my username is also Soupette on both medium.

**Comment by d2kx** [comment]
I am closing this for now as I have noticed some possible problems on our end in regards to overwriting content in /admin that might cause issues.

**Comment by MO-Lewis** [comment]
Hi,

Did you ever figure out the cause of this? I cloned the following repo: https://github.com/PaulBratslavsky/demoMigration

I seeded test data using the script within the repo, upgraded it to `3.6.11` (from `3.5.0`, so there was **no** migration guide), created an admin account, attempted to log in, and now I have this issue.

Would be great to hear if you ever solved this @d2kx !

**Comment by MO-Lewis** [comment]
After looking into this, I needed to also install the `"strapi-plugin-i18n": "3.6.11",` package. This changes my error to `TypeError: Cannot read properties of undefined (reading 'add')`; which is likely more related to the code in the `demoMigration` repo.
