### ISSUE TITLE
Can't get strapi to run on google cloud after updating to 3.0.0

### ISSUE THREAD

**Issue by FamilyMan** [strapi/strapi#6384]
**Describe the bug**
I have updated strapi from v3.0.0-beta.20.3 to v3.0.0. Strapi runs fine locally but I have the following issues when trying to get it to run on google cloud. It seems to be an issue with strapi-provider-upload-google-cloud-storage, even when I have removed this from package.json. I have done npm run build -- --clean before each deploy.
The logs are as follows:

Without strapi-provider-upload-google-cloud-storage in package.json I get:

"GET / HTTP/1.1" 500
error Error: Cannot find module 'strapi-provider-upload-google-cloud-storage'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:692:17)
at require (internal/modules/cjs/helpers.js:25:18)
at createProvider (/srv/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:35:30)
at module.exports (/srv/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:16:36)
at execBootstrap (/srv/node_modules/strapi/lib/Strapi.js:394:15)
at Object.keys.map.plugin (/srv/node_modules/strapi/lib/Strapi.js:401:14)
at Array.map (<anonymous>)
at Strapi.runBootstrapFunctions (/srv/node_modules/strapi/lib/Strapi.js:400:55)
at Strapi.load (/srv/node_modules/strapi/lib/Strapi.js:326:16)
error Bootstrap function in plugin "upload" failed
error Error: The provider package isn't installed. Please run `npm install strapi-provider-upload-google-cloud-storage`
at createProvider (/srv/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:40:11)
"GET /favicon.ico HTTP/1.1" 204

With strapi-provider-upload-google-cloud-storage in package.json I get:

"GET / HTTP/1.1" 500
error TypeError: Cannot read property 'gcs' of undefined
at mergeConfigs (/srv/node_modules/strapi-provider-upload-google-cloud-storage/lib/index.js:81:63)
at Object.init (/srv/node_modules/strapi-provider-upload-google-cloud-storage/lib/index.js:91:24)
at createProvider (/srv/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:35:76)
at module.exports (/srv/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:16:36)
at execBootstrap (/srv/node_modules/strapi/lib/Strapi.js:394:15)
at Object.keys.map.plugin (/srv/node_modules/strapi/lib/Strapi.js:401:14)
at Array.map (<anonymous>)
at Strapi.runBootstrapFunctions (/srv/node_modules/strapi/lib/Strapi.js:400:55)
at Strapi.load (/srv/node_modules/strapi/lib/Strapi.js:326:16)
error Bootstrap function in plugin "upload" failed
error Error: The provider package isn't installed. Please run `npm install strapi-provider-upload-google-cloud-storage`
at createProvider (/srv/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:40:11)
at module.exports (/srv/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:16:36)
"GET /favicon.ico HTTP/1.1" 204

**Steps to reproduce the behavior**

1. Upgrade to v3.0.0

**Expected behavior**
Server to start

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 12.16.3 
- NPM version: 6.14.4
- Strapi version: 3.0.0 
- Database: postgreSQL
- Operating system: Windows 10

**Additional context**

**Comment by derrickmehaffy** [comment]
`strapi-provider-upload-google-cloud-storage` this package is not maintained by Strapi please contact the author.

Whom I believe is @Lith .

Moving this to a discussion.
