### ISSUE TITLE
Unable to use migrations - db.getConnection(...).transaction is not a function

### ISSUE THREAD

**Issue by ziksuka** [strapi/strapi#13348]
**Describe the bug**
After Upgrading the application dependencies 4.1.9 to 4.1.10,  second step which is optional , adding 2022.05.10T00.00.00.fill-files-mime-type.js to database migration .  when i have run the develop,  it has started showing the below error.

db.getConnection(...).transaction is not a function

**Steps to reproduce the behavior**
add a  2022.05.10T00.00.00.fill-files-mime-type.js file in databases/migration
Run strapi
See error
Expected behavior
Migrations should work without error

**Screenshots**
![image](https://user-images.githubusercontent.com/54988624/169065468-77135fcc-576d-4faf-afb7-8510cbbf01b2.png)

**System**
Strapi version: 4.1.10
Database: Postgres

**Comment by ziksuka** [comment]
@petersg83 yes it is in windows.
 Strapi is running correctly without migration script.

**Comment by derrickmehaffy** [comment]
Tested on Windows 10 and Windows 11 with a fresh 4.1.8 project (made sure I add a media file and manually deleted it's mime type to reproduce the bug we fixed).

Can't reproduce, I added the script, booted the server and the mime type was fixed and there was no bug.

@ziksuka do you have any extensions, community plugins, patch-package patches?

For now I'll set this as closed until we have more information to reproduce.
