### ISSUE TITLE
Strapi v5.46.0 does not reliably update generated ContentType typings after creating/editing a content type (TS2345)

### ISSUE THREAD

**Issue by alexllao** [strapi/strapi#26348]
### Node Version

22

### Package Manager

pnpm

### Package Manager Version

10

### Strapi Version

5.45.1

### Operating System

Windows 11

### Database

PostgreSQL

### Javascript or Typescript

Typescript

### Bug Description

# Strapi v5.46.0 does not reliably update generated ContentType typings after creating/editing a content type (TS2345)

## Summary

After creating or editing a content type in Strapi (via Content-Type Builder), generated TypeScript typings are not reliably updated in types/generated/contentTypes.d.ts.

Because of this, createCoreController, createCoreRouter, and createCoreService fail with TS2345 for valid content type UIDs.

## Environment

- Strapi: 5.46.0 (issue started after upgrading from 5.45.1)
- Node.js: 22.22.2
- Package manager: pnpm
- OS: Windows
- Database: Postgres

## Reproduction Steps

1. Start Strapi in development mode.
2. Create a collection type Post from Content-Type Builder.
3. Strapi generates files under src/api/post:
   - src/api/post/controllers/post.ts
   - src/api/post/routes/post.ts
   - src/api/post/services/post.ts
   - src/api/post/content-types/post/schema.json
4. Strapi restarts and compiles TypeScript.

## Actual Result

Compilation fails with:

```ts
error TS2345: Argument of type '"api::post.post"' is not assignable to parameter of type 'ContentType'.

export default factories.createCoreController('api::post.post');
```

Same error appears in router and service.

Also, when editing Post attributes later (for example adding excerpt, seo, coverImage), generated typings do not stay in sync reliably.

## Expected Result

When a content type is created or updated from Content-Type Builder, Strapi should regenerate types/generated/contentTypes.d.ts consistently, including:

- ApiPostPost interface
- api::post.post entry in Public.ContentTypeSchemas
- newly added attributes

so TypeScript compilation succeeds without manual patching.

## Notes

- The issue appears unstable/intermittent: API files are generated, but typings may be missing or stale.
- Clearing .strapi and dist does not consistently fix it.
- Manual patching of generated typings unblocks compilation temporarily, but it is not maintainable.

## Temporary Workaround

Manually edit types/generated/contentTypes.d.ts to add missing ApiPostPost and api::post.post mapping.

## Impact

High for TypeScript workflows: schema changes via Content-Type Builder can break compilation and block development.

### Steps to Reproduce

Steps to Reproduce
Start a Strapi project with TypeScript on version 5.46.0.
Run Strapi in development mode.
Open Content-Type Builder and create a new collection type named Post.
Add fields:
title (string, required)
slug (uid, targetField: title, required)
Save the content type and wait for Strapi to restart/rebuild.
Observe TypeScript compilation of generated files:
src/api/post/controllers/post.ts
src/api/post/routes/post.ts
src/api/post/services/post.ts
(Optional) Edit Post again and add fields like excerpt, seo (component), coverImage (component), then save.

### Expected Behavior

After creating or editing a content type from Content-Type Builder, Strapi should regenerate TypeScript content-type definitions so the new UID is included in ContentType.
The generated Post controller/router/service should compile successfully without any manual edits to types/generated/contentTypes.d.ts.

### Logs

```shell
✔ Cleaning dist dir (180ms)
src/api/post/controllers/post.ts:7:47 - error TS2345: Argument of type '"api::post.post"' is not assignable to parameter of type 'ContentType'.

7 export default factories.createCoreController('api::post.post');
                                                ~~~~~~~~~~~~~~~~
src/api/post/routes/post.ts:7:43 - error TS2345: Argument of type '"api::post.post"' is not assignable to parameter of type 'ContentType'.

7 export default factories.createCoreRouter('api::post.post');
                                            ~~~~~~~~~~~~~~~~
src/api/post/services/post.ts:7:44 - error TS2345: Argument of type '"api::post.post"' is not assignable to parameter of type 'ContentType'.

7 export default factories.createCoreService('api::post.post');
                                             ~~~~~~~~~~~~~~~~

Found 3 error(s).
```

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

**Comment by jshaofa-ui** [comment]
## Root Cause Analysis

This is a **race condition between schema file writes and TypeScript type generation** during develop-mode restart.

### Code Flow

1. **Content-Type Builder** (`content-types.ts`): `createContentType()` → `builder.writeFiles()` → `Promise.all(schemas.map(s => s.flush()))` → emits `content-type.create` event
2. **Chokidar Watcher** (`develop.ts`): Detects schema.json file changes → triggers `restart()` → `strapiInstance.reload()`
3. **Primary Process**: Receives `reload` message → cleans dist → `tsUtils.compile()` → sends `kill` to worker
4. **Worker Process**: `tsUtils.generators.generate()` → regenerates `contentTypes.d.ts` → `tsUtils.compile()`

### The Race

The `Promise.all()` in `writeFiles()` writes multiple schema files concurrently. Chokidar fires `change` events for **each file individually** as they are written — not after all writes complete.

- **Scenario A (works)**: All schema files written → chokidar fires → restart → type generation with complete schemas → TS compilation succeeds
- **Scenario B (fails)**: First schema file written → chokidar fires → restart begins → type generation reads **partial** schema set → new content type UID missing from `contentTypes.d.ts` → TS2345

This explains the intermittent nature: "unstable/intermittent" — depends on whether chokidar detects the first file change before all `flush()` operations complete.

### Proposed Fix

**Option A (quickest)**: Add a debounce/gate to the chokidar watcher that delays restart for ~500ms after CTB operations complete:

```typescript
// In content-types.ts after builder.writeFiles():
ctbWriteCompleteTime = Date.now();

// In develop.ts restart():
if (Date.now() - ctbWriteCompleteTime < 500) return;
```

**Option B (robust)**: Make `writeFiles()` + `tsUtils.generators.generate()` atomic — regenerate types before the watcher can fire any restart.

**Option C (best long-term)**: Have CTB emit an event that triggers both type generation AND restart in the correct order, bypassing the file watcher entirely for CTB-triggered changes.

The key insight: type generation must complete **before** any restart is triggered, and the current architecture allows the watcher to fire mid-write.

**Comment by alexllao** [comment]
That’s why I don’t think this is only related to the develop watcher/restart flow.

I’m seeing the exact same issue in production after a clean deploy + build, where Chokidar and hot reload are not involved at all.

It feels more like contentTypes.d.ts sometimes gets out of sync with the actual schemas, or the type generation process is not fully atomic/reliable in some cases.

The reason I think that is because manually regenerating the types immediately fixes the issue.

**Comment by jshaofa-ui** [comment]
## 💡 Proposed Solution

### Root Cause
Strapi v5.46.0's Content-Type Builder may not reliably update generated content types due to caching or file watching issues in the build pipeline.

### Proposed Fix
1. Add explicit cache invalidation after content type changes
2. Ensure the generated files are properly watched for changes

```typescript
// In packages/core/content-type-builder/src/services/content-types.ts
// Add cache invalidation after update:

async updateContentType(uid: string, data: ContentTypeUpdateData) {
  const result = await this.updateContentTypeCore(uid, data);
  
  // Invalidate cache
  this.cache.delete(`content-type:${uid}`);
  
  // Trigger regeneration
  await this.regenerateGeneratedFiles(uid);
  
  return result;
}
```

### Investigation Needed
1. Confirm if the issue is cache-related or file-watching related
2. Check if the issue occurs on all platforms or specific OS
3. Verify the regeneration trigger is firing

### Impact
- Breaking change: No
- Backward compatible: Yes
- Effort: ~10-20 lines

**Comment by alexllao** [comment]
Hi!!!

Nothings work.
I can confirm this is still reproducible even with a manual type generation step.

I run:

$ strapi "ts:generate-types"

[INFO]  [2026-05-18T02:08:14.016Z] (Typegen) Starting the type generation process
[DEBUG] [2026-05-18T02:08:14.017Z] (Typegen) Enabled artifacts: contentTypes, components
[INFO]  [2026-05-18T02:08:14.017Z] (Typegen) Generating types for contentTypes
[DEBUG] [2026-05-18T02:08:14.041Z] (Typegen) Found 23 content-types.
[ERROR] [2026-05-18T02:08:14.586Z] (Typegen) Failed to generate types for contentTypes: e.charAt is not a function. Exiting
[INFO]  [2026-05-18T02:08:14.586Z] (Typegen) The task errored with 0 warning(s) and 1 error(s) in 0.57s.
[2026-05-18 04:08:14.587] info: Shutting down Strapi
[2026-05-18 04:08:14.591] info: Strapi has been shut down

This is crazy!!!!

**Comment by alexllao** [comment]
I’ve already solved it. Thnks @jshaofa-ui 

The failure was not caused by invalid Strapi content-type schemas.
The actual error happened during the formatting step after type generation.

What happens internally:

Strapi generates the TypeScript definitions successfully.
Then it runs Prettier to format the generated output.
In this monorepo, Prettier was loading the Tailwind plugin.
That plugin wraps the TypeScript parser, and it crashed with:
TypeError: e.charAt is not a function
So the error message appeared as “Failed to generate types for contentTypes”, but the root cause was Prettier/plugin interaction, not the content-type definitions themselves.

Evidence:

Running the generator directly showed the stack trace going through prettier-plugin-tailwindcss and then failing inside Prettier’s TypeScript parser.
Once a local Prettier config was added for be-strapi, type generation completed successfully.
Workaround / fix applied:

Added a local Prettier config in [prettier.config.cjs] so Strapi type generation does not inherit the root Prettier plugin chain.
After that, pnpm --filter be-strapi generate:types succeeds.
If needed, I can also give you a shorter “Root cause / Fix / Impact” version for maintainers.
