### PR TITLE
fix(typescript): prevent stale content-type typings during develop reload cycle

### LINKED ISSUE #26348: Strapi v5.46.0 does not reliably update generated ContentType typings after creating/editing a content type (TS2345)
### Node Version

22

### Package Manager

pnpm

### Package Manager Version

10

### Strapi Version

5.45.1

### Operating System

Windows 11

### Database

PostgreSQL

### Javascript or Typescript

Typescript

### Reproduction URL

_No response_

### Bug Description

# Strapi v5.46.0 does not reliably update generated ContentType typings after creating/editing a content type (TS2345)

## Summary

After creating or editing a content type in Strapi (via Content-Type Builder), generated TypeScript typings are not reliably updated in types/generated/contentTypes.d.ts.

Because of this, createCoreController, createCoreRouter, and createCoreService fail with TS2345 for valid content type UIDs.

## Environment

- Strapi: 5.46.0 (issue started after upgrading from 5.45.1)
- Node.js: 22.22.2
- Package manager: pnpm
- OS: Windows
- Database: Postgres

## Reproduction Steps

1. Start Strapi in development mode.
2. Create a collection type Post from Content-Type Builder.
3. Strapi generates files under src/api/post:
   - src/api/post/controllers/post.ts
   - src/api/post/routes/post.ts
   - src/api/post/services/post.ts
   - src/api/post/content-types/post/schema.json
4. Strapi restarts and compiles TypeScript.

## Actual Result

Compilation fails with:

```ts
error TS2345: Argument of type '"api::post.post"' is not assignable to parameter of type 'ContentType'.

export default factories.createCoreController('api::post.post');
```

Same error appears in router and service.

Also, when editing Post attributes later (for example adding excerpt, seo, coverImage), generated typings do not stay in sync reliably.

## Expected Result

When a content type is created or updated from Content-Type Builder, Strapi should regenerate types/generated/contentTypes.d.ts consistently, including:

- ApiPostPost interface
- api::post.post entry in Public.ContentTypeSchemas
- newly added attributes

so TypeScript compilation succeeds without manual patching.

## Notes

- The issue appears unstable/intermittent: API files are generated, but typings may be missing or stale.
- Clearing .strapi and dist does not consistently fix it.
- Manual patching of generated typings unblocks compilation temporarily, but it is not maintainable.

## Temporary Workaround

Manually edit types/generated/contentTypes.d.ts to add missing ApiPostPost and api::post.post mapping.

## Impact

High for TypeScript workflows: schema changes via Content-Type Builder can break compilation and block development.

### Steps to Reproduce

Steps to Reproduce
Start a Strapi project with TypeScript on version 5.46.0.
Run Strapi in development mode.
Open Content-Type Builder and create a new collection type named Post.
Add fields:
title (string, required)
slug (uid, targetField: title, required)
Save the content type and wait for Strapi to restart/rebuild.
Observe TypeScript compilation of generated files:
src/api/post/controllers/post.ts
src/api/post/routes/post.ts
src/api/post/services/post.ts
(Optional) Edit Post again and add fields like excerpt, seo (component), coverImage (component), then save.

### Expected Behavior

After creating or editing a content type from Content-Type Builder, Strapi should regenerate TypeScript content-type definitions so the new UID is included in ContentType.
The generated Post controller/router/service should compile successfully without any manual edits to types/generated/contentTypes.d.ts.

### Logs

```shell
✔ Cleaning dist dir (180ms)
src/api/post/controllers/post.ts:7:47 - error TS2345: Argument of type '"api::post.post"' is not assignable to parameter of type 'ContentType'.

7 export default factories.createCoreController('api::post.post');
                                                ~~~~~~~~~~~~~~~~
src/api/post/routes/post.ts:7:43 - error TS2345: Argument of type '"api::post.post"' is not assignable to parameter of type 'ContentType'.

7 export default factories.createCoreRouter('api::post.post');
                                            ~~~~~~~~~~~~~~~~
src/api/post/services/post.ts:7:44 - error TS2345: Argument of type '"api::post.post"' is not assignable to parameter of type 'ContentType'.

7 export default factories.createCoreService('api::post.post');
                                             ~~~~~~~~~~~~~~~~

Found 3 error(s).
```

### Code Snippets

_No response_

### Media

_No response_

### Additional information

_No response_

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by AdityaOP007**
# fix(strapi): ensure TypeScript content-type typings regenerate deterministically on reload

## Summary

This PR fixes an issue where TypeScript content-type typings were not reliably regenerated after creating, editing, or deleting content types through the Content-Type Builder.

In affected cases, Strapi correctly generated the API files under `src/api/*`, but the generated typings inside:

```txt
types/generated/contentTypes.d.ts
```

could become stale or incomplete during the reload cycle.

As a result, valid generated code such as:

```ts
export default factories.createCoreController('api::post.post');
```

would fail with:

```txt
TS2345: Argument of type '"api::post.post"' is not assignable to parameter of type 'ContentType'
```

This mainly affected TypeScript projects using the `develop` command and was especially reproducible on Windows environments.

Fixes strapi/strapi#26348.

---

# Root Cause

The issue came from a race condition during the development reload flow.

When a schema changed through the Content-Type Builder:

1. The worker process wrote the schema and triggered a reload
2. The primary process immediately compiled TypeScript
3. At this moment, regenerated typings were still stale because the new worker had not regenerated them yet
4. Since incremental TypeScript compilation was enabled by default, this compilation produced a `.tsbuildinfo` file containing stale type information
5. The new worker later regenerated correct typings, but the incremental compiler could still reuse the stale cache
6. On Windows, filesystem timestamp granularity (\~1 second) made this behavior much easier to reproduce

Additionally, if the primary process compilation failed during reload, the current implementation called:

```ts
process.exit(1)
```

which terminated the entire development server before the worker could recover with fresh types.

---

# What Changed

1. Disable incremental compilation during primary reload compile

---

File:

```txt
packages/core/strapi/src/node/develop.ts
```

The primary process reload compilation now runs with:

```ts
incremental: false,
tsBuildInfoFile: null
```

This prevents stale `.tsbuildinfo` files from being generated before fresh typings exist.

The primary compile is effectively treated as a temporary bootstrap compile instead of a cache-producing incremental build.

---

2. Make reload compilation non-fatal

---

Previously, any compilation error during reload caused the primary process to terminate immediately.

This PR changes the behavior so that reload compilation errors are logged as warnings and the reload cycle continues.

The worker process is then allowed to:

* regenerate typings
* perform a clean compilation
* recover successfully

This avoids unnecessary crashes caused by transient schema/type mismatches during regeneration.

---

3. Remove stale `.tsbuildinfo` before worker compilation

---

After the worker regenerates fresh typings, any existing `.tsbuildinfo` file is deleted before TypeScript compilation begins.

This guarantees that the worker compilation starts from a clean incremental state and does not reuse stale cached type metadata from earlier reload cycles.

---

4. Atomic writes for generated typings

---

File:

```txt
packages/utils/typescript/lib/generators/utils.js
```

Generated definition files now use a write-to-temp-then-rename strategy.

Instead of writing directly to:

```txt
contentTypes.d.ts
```

the generator now:

1. writes to a temporary file
2. renames it atomically

This prevents the TypeScript compiler from reading partially-written definition files during concurrent reload activity.

---

# Result

After this change:

* newly created content types appear reliably in generated typings
* edited attributes stay synchronized correctly
* deleted content types are removed properly
* generated controllers/routes/services compile successfully
* TS2345 errors caused by stale typings no longer occur
* reloads recover safely even when transient compilation mismatches happen

---

# Files Changed

File | Changes -- | -- packages/core/strapi/src/node/develop.ts | Improve reload compilation behavior and incremental cache handling packages/utils/typescript/lib/generators/utils.js | Add atomic writes for generated type definition files

---

# How To Test

## Reproduction

1. Create a TypeScript Strapi app:

```bash
npx create-strapi-app@latest my-app --ts
```

2. Start development mode:

```bash
yarn develop
```

3. Open the Content-Type Builder
4. Create a Collection Type named:

```txt
Post
```

with a field:

```txt
title (text)
```

5. Save the content type

---

### Generated typings are updated

Check:

```txt
types/generated/contentTypes.d.ts
```

and verify it contains:

```ts
'api::post.post'
```

---

### Generated APIs compile successfully

Verify there are no errors in:

```txt
src/api/post/controllers/post.ts
src/api/post/routes/post.ts
src/api/post/services/post.ts
```

Specifically, ensure no TS2345 errors occur.

---

### Modify schema

Add additional fields such as:

* description
* excerpt
* components
* dynamic zones

Verify typings update correctly.

---

### Delete schema

Delete the content type and verify the generated typings are removed correctly.

---

### Stress test

Perform rapid successive schema edits to verify reload consistency and ensure stale incremental caches are not reused.

---

# Notes

This PR intentionally keeps the current reload architecture intact and focuses on making the existing type generation + compilation pipeline deterministic and cache-safe rather than introducing a larger reload lifecycle refactor.

The fix is minimal, isolated, and targeted specifically at the stale typings regression introduced in recent reload behavior.

ISSUE solved

---

Fixes [CPR-346](https://linear.app/strapi/issue/CPR-346/pr-26350-fixtypescript-prevent-stale-content-type-typings-during)

### CODE REVIEW

**Comment by AdityaOP007** [comment]
Thanks!
I believe the failing Vercel check is related to workflow authorization for external contributors. The core TypeScript/lint checks passed locally during verification.

Please let me know if any additional changes or test coverage are needed.
