### ISSUE TITLE
Type '{}' has no call signatures error when call a service in Typescript

### ISSUE THREAD

**Issue by smoothdvd** [strapi/strapi#16993]
### Required System information

- Node.js version: 18.16.0
- NPM version: 
- Strapi version: 4.11.1
- Database: PostgreSQL
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

```
Starting the compilation for TypeScript files in /Users/alexgao/Dev/asiagames-app/apps/asiagames-strapi
src/api/game/controllers/game.ts:13:59 - error TS2349: This expression is not callable.
  Type '{}' has no call signatures.

13     const result = await strapi.service('api::game.game').findByUUID(uuid, sanitizedQueryParams);
                                                             ~~~~~~~~~~

Found 1 error(s).
```

### Expected behavior

Typescript compatible

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by cherring07** [comment]
Also experiencing this.

**Comment by ls-ramos** [comment]
Same here.

**Comment by alxnkt** [comment]
I've got absolutely the same problem )

**Comment by JayeClissold** [comment]
Not a great solution, but for anyone that needs to get their builds working, you can exclude the src directory in the tsconfig file.

**Comment by smoothdvd** [comment]
I can temporarily use <any> to solve.
const result = await strapi.service<any>('api::game.game').findByUUID(uuid, sanitizedQueryParams);

**Comment by sam4mation** [comment]
Getting this too...

**Comment by woodyjon** [comment]
Same here. Experiencing when updating from 4.11.0 to 4.11.1. Looks like a regression from the latest version.

**Comment by eucciferri** [comment]
I thinks this error is related to the new feature that was included in the last Strapi update (4.11.1):

Type System v1: https://github.com/strapi/strapi/pull/16917

**Comment by dzcpy** [comment]
Same problem. Strapi's TypeScript system has always got a lot of problems, it's almostly AnyScript :D, but now it's just got a bit more difficult to use...

**Comment by RhusferJohn** [comment]
> I think this error is related to the new feature that was included in the last Strapi update (4.11.1):
> 
> Type System v1: #16917

Downgrading to 4.11.0 solves the issue. Hopefully they will fix this for the latest versions.

**Comment by alxnkt** [comment]
Looks like adding `.entityService` solved the issue for me.
Try:
```javascript
const result = await strapi.entityService.service('api::game.game').findByUUID(uuid, sanitizedQueryParams);
```
See [docs](https://docs.strapi.io/dev-docs/api/entity-service/crud#example)

**Comment by eucciferri** [comment]
Hi @alxnkt! Unfortunately, as you said, it's only works with the standard entity services 😞. I realized this since it didn't work for me with the services of a basic API that I had generated from "strapi generate". It only works for standard entity services of Single and Collection Types.

**Comment by Convly** [comment]
Hello everyone, thanks for taking the time to write this issue.
We've been a bit slow to answer as the whole team was on vacation last week.
I'll take a look today and let you know (high chance it's related to the feature @eucciferri shared)
