### ISSUE TITLE
TS2688: Cannot find type definition file for 'bcryptjs' in Strapi v5.8.0

### ISSUE THREAD

**Issue by red-made** [strapi/strapi#24243]
### Node Version

20.0.0

### NPM/Yarn/PNPM Version

10.2.3

### Strapi Version

5.8.0

### Operating System

MacOS

### Database

MySQL

### Javascript or Typescript

Typescript

### Bug Description

Hello Strapi team,

I was working on my Strapi project (v5.8.0) yesterday without any issues. Today, after reopening my computer and starting the development server, I get the following TypeScript error:

```
error TS2688: Cannot find type definition file for 'bcryptjs'.
  The file is in the program because:
    Entry point for implicit type library 'bcryptjs'

Found 1 error(s).
```

The error happens even if I do not import bcryptjs in my code.

- @types/bcryptjs is installed.
- skipLibCheck is enabled in tsconfig.json.
- I have already cleaned dist and removed any .tsbuildinfo files.
- Everything was working fine yesterday; the project stopped working today without any changes to the code.

I’m looking for guidance on how to fix this and continue development.

Thank you! 

### Steps to Reproduce

- Open the Strapi project (v5.8.0) that was working previously.
- Ensure Node.js environment is the same as yesterday.
- Run the development server:
- Observe the TS2688 error regarding bcryptjs appearing immediately.

### Expected Behavior

To working fine like yesterday

### Logs

```shell

```

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

**Comment by red-made** [comment]
Solved by adding in compilerOptions:
```
  "types": []
```

However, I find this behavior strange because:
- I have not modified any code, dependencies, or installed anything since yesterday.
- The project was working perfectly yesterday and I only reopened my computer today.

Could the team help verify and explain why TypeScript suddenly starts looking for bcryptjs types in this scenario? I want to make sure the project hasn’t been silently corrupted and to understand the root cause.

Thank you!
