### ISSUE TITLE
error TS2339 - Strange type error after upgrading to 4.13.1

### ISSUE THREAD

**Issue by erinnovations** [strapi/strapi#17870]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.6.7
- Strapi version: 4.13.1
- Database: postgres
- Operating system: win
- Is your project Javascript or Typescript: TS

### Describe the bug

These type errors suddenly appeared after upgrading to 4.13.1.

### Expected behavior

Previously working codes in lifecycles.ts continue working.
Please help me to track it down. I am not really understand what I am doing wrong or changed. These codes works fine on 4.12.7.

### Screenshots

![Képernyőkép 2023-08-30 200906](https://github.com/strapi/strapi/assets/253455/2181d317-bebb-4678-9bc8-8595c80ada1c)
![Képernyőkép 2023-08-30 200930](https://github.com/strapi/strapi/assets/253455/50b98a97-2987-4281-83fd-cd3bfaba57fd)
![Képernyőkép 2023-08-30 201623](https://github.com/strapi/strapi/assets/253455/b55c6f2f-867b-48a1-b2b3-70f5e50c33f4)

**Comment by unsalted** [comment]
We also ran in to this issue.
