### ISSUE TITLE
Admin UI errors on deeply nested components with relation

### ISSUE THREAD

**Issue by aevarisak** [strapi/strapi#15038]
### Required System information

- Node.js version: v16.18.1
- NPM version: 8.19.2
- Strapi version: 4.5.2
- Database: Postgres 13
- Operating system: macOS 12.6 

### Describe the bug

Seems that the Admin UI fails to render components that are deeply nested with a relation at the end.

### Steps to reproduce the behavior

1. Create a component
2. Create another component that is repeatable on the previous component
3. Create another component that is not repeatable on the previous component
4. Finally create a component that is repeatable on the previous component and includes a relation
5. Attach the component as a field to a collection type
6. Open the collection type editor
7. Click on the first component
8. Click on the second component and you should get an error `arr.map is not a function`

### Expected behavior

UI should display the nested components

### Screenshots

![image](https://user-images.githubusercontent.com/2563139/204561866-59322af7-9212-49db-8ee6-871e0eb1ebb5.png)
![image](https://user-images.githubusercontent.com/2563139/204563546-d248da40-a1f2-4373-b55b-633b1eb0d55c.png)
![image](https://user-images.githubusercontent.com/2563139/204563704-79ed35c3-8af5-4acb-a109-3f1a77b87980.png)

### Additional context

This was working on 4.4.7 but fails on 4.5.2. My guess is from changes made in this #14659 PR. 

If the last component is not made repeatable this works just fine.

**Comment by aevarisak** [comment]
After more testing this fails as well

![image](https://user-images.githubusercontent.com/2563139/204568895-868a6035-92a4-44b0-b1a5-5f14380a2e03.png)
