### ISSUE TITLE
Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by nvispute** [strapi/strapi#24323]
While testing v5, I had to manually delete a table from `./tmp/data.db`, which stalled my plugin. The problem then was as follows

## Root Error that started a chain of events, 

```
[2025-09-06 03:39:39.522] info: Strapi started successfully
[2025-09-06 03:39:46.357] error: insert into `repos` (`created_at`, `document_id`, `published_at`, `updated_at`) values ('2025-09-06 03:39:46.350', 'fyavx0s7ng6ec0fgjcasys4w', '2025-09-06 03:39:46.352', '2025-09-06 03:39:46.350') returning `id` - no 
such table: repos
SqliteError: insert into `repos` (`created_at`, `document_id`, `published_at`, `updated_at`) values ('2025-09-06 03:39:46.350', 'fyavx0s7ng6ec0fgjcasys4w', '2025-09-06 03:39:46.352', '2025-09-06 03:39:46.350') returning `id` - no such table: repos   
    at Database.prepare (E:\strapi-course\strapi-basics\node_modules\better-sqlite3\lib\methods\wrappers.js:5:21)
    at Client_BetterSQLite3._query (E:\strapi-course\strapi-basics\node_modules\knex\lib\dialects\better-sqlite3\index.js:35:34)
    at executeQuery (E:\strapi-course\strapi-basics\node_modules\knex\lib\execution\internal\query-executioner.js:37:17)     
    at Client_BetterSQLite3.query (E:\strapi-course\strapi-basics\node_modules\knex\lib\client.js:154:12)
    at Runner.query (E:\strapi-course\strapi-basics\node_modules\knex\lib\execution\runner.js:141:36)
    at ensureConnectionCallback (E:\strapi-course\strapi-basics\node_modules\knex\lib\execution\internal\ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (E:\strapi-course\strapi-basics\node_modules\knex\lib\execution\runner.js:318:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Runner.run (E:\strapi-course\strapi-basics\node_modules\knex\lib\execution\runner.js:30:19)
    at async Object.execute (E:\strapi-course\strapi-basics\node_modules\@strapi\database\dist\query\query-builder.js:471:30)[2025-09-06 03:39:46.363] http: GET /api/github-projects/repos/ (824 ms) 500
```
So, to fix this issue, I was suggested by the community **[Google, StackOverflow as well as Gemini]** to delete the node_modules, package-lock and reinstall the packages. after the reinstall was done, 

1. I create a fresh super admin account, 
2. The content manager went into an infinite loop of loading 
3. i started getting multiple error in various top navigations such 

    a. **Media Library gave `checkUserHasPermissions is not a function`**
```
TypeError: checkUserHasPermissions is not a function
    at http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-KB27YQQU.js?v=7a848339:85:7
    at commitHookEffectListMount (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:16915:34)
    at commitPassiveMountOnFiber (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:18156:19)
    at commitPassiveMountEffects_complete (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:18129:17)
    at commitPassiveMountEffects_begin (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:18119:15)
    at commitPassiveMountEffects (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:18109:11)
    at flushPassiveEffectsImpl (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:19490:11)
    at flushPassiveEffects (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:19447:22)
    at performSyncWorkOnRoot (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:18868:11)
    at flushSyncCallbacks (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:9119:30)
```
**[Sreenshot]** 
<img width="1360" height="685" alt="Image" src="https://github.com/user-attachments/assets/ecbfbfe8-ba45-4eb8-b751-fec910e09343" />

    b.  **Content Type Builder gave `Cannot read properties of undefined (reading 'filter')`** 

```
TypeError: Cannot read properties of undefined (reading 'filter')
    at Protect (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-7U64JNRQ.js?v=7a848339:286:47)
    at renderWithHooks (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:11548:26)
    at mountIndeterminateComponent (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:14926:21)
    at beginWork (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:15914:22)
    at beginWork$1 (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:19753:22)
    at performUnitOfWork (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:19198:20)
    at workLoopSync (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:19137:13)
    at renderRootSync (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:19116:15)
    at recoverFromConcurrentError (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:18736:28)
    at performConcurrentWorkOnRoot (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:18684:30)
```

    **3c. Content Releases gave `Cannot read properties of undefined (reading 'filter')` **

```
TypeError: Cannot read properties of undefined (reading 'filter')
    at Protect (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-7U64JNRQ.js?v=7a848339:286:47)
    at renderWithHooks (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:11548:26)
    at mountIndeterminateComponent (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:14926:21)
    at beginWork (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:15914:22)
    at beginWork$1 (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:19753:22)
    at performUnitOfWork (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:19198:20)
    at workLoopSync (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:19137:13)
    at renderRootSync (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:19116:15)
    at recoverFromConcurrentError (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:18736:28)
    at performConcurrentWorkOnRoot (http://localhost:1337/admin/node_modules/.strapi/vite/deps/chunk-FOD4ENRR.js?v=7a848339:18684:30)
```

I am not going to list all the locations where I got errors, but from the gist of these 3 errors, I assumed the errors were related to userPermission, but as a super admin, i believed that 100% permission is set by default, still i checked the user 
It was as expected, but for some reason, the exemption was my custom plugin.

Here is the screenshot attached

<img width="1347" height="617" alt="Image" src="https://github.com/user-attachments/assets/305d0fe9-59a8-43d2-90f8-077a7ba025fe" />

i think by reinstalling the `node_modules` I accidentally broke something in the data.db or its schema. I say this because I copied all the custom content data into the newer data.db and exempted the system-generated tables, such as Strapi.*

Here is a copy of the data; for upload purposes, I have renamed the file to data.jpg. Please rename it back to .rar to extract both the New and old Data.db 

![Image](https://github.com/user-attachments/assets/6fd5d034-308d-4973-955d-b1647b59e598)

# Troubleshooting Steps performed before raising the request
1. Comment out the custom controller logic [build and then develop]
2. Import custom data from the old DB to the newly created DB after freshly installing the node_modules [build and then develop]
3. Did not run strapi generate to create new middlewares/controllers, as I think i copied most of the at the DB level, and there were 0 changes in the underlying code itself
4. Delete the .strapi cache file [build and then develop]
[build and then develop] ref to rebuilding the plugin as well as the Strapi, and they were performed after every step.

**Comment by OcneanuVlad** [comment]
Hello,

While we continue investigating the problem, could you please try running the following command to upgrade your app to the latest version and see if it resolves the issue?
`npx @strapi/upgrade latest`

Additionally, please remember to follow the issue template when reporting problems. This helps us gather all the necessary information and makes it easier to resolve issues more quickly.

**Comment by nvispute** [comment]
Upgrading to the latest version didn't work in my case. After upgrading, I restarted and repeated the steps I mentioned in my original post, with no success. I think I broke the DB by messing with permissions. 

Is there a command to reset the DB and fill it with default permissions? 

I simply followed the link that was given in the Error page; there was no template given in there. However, before I ran the upgrade command, I captured the information that is expected while submitting a new issue

#Node Version
v22.17.0

#Npm version
9.6.6

#Strapi version
5.23.0

#OS
Windows 10 Pro

#DataBase
SQLite

#JS/TS
JS

After the upgrade command, the Strapi version is `5.23.4`

**Comment by OcneanuVlad** [comment]
There is no command to reset the DB and fill it with default permissions, however you could run some migrations, or delete the table entirely (empty it, do not delete the table itself) and let Strapi regenerate it, if you think the problems resides there.

**Comment by garrylachman** [comment]
same here, after installing https://market.strapi.io/plugins/strapi-import-export

**Comment by ertugrulemrecihan** [comment]
I'm getting this error too. Has anyone found a solution?

**Comment by AliasSCM** [comment]
I had a similar issue 

`TypeError: checkUserHasPermissions is not a function`

This meant that my content manager kept loading and never really opened. 

I managed to resolve it trying downgrading of the strapi version and it seems to work. Here are the versions im using

```
   "@strapi/plugin-cloud": "5.10.3",
   "@strapi/plugin-documentation": "5.10.3",
    "@strapi/plugin-users-permissions": "5.10.3",
    "@strapi/provider-email-nodemailer": "5.10.3",
    "@strapi/provider-email-sendgrid": "5.10.3",
    "@strapi/provider-upload-aws-s3": "5.10.3",
    "@strapi/strapi": "5.10.3",
    "@strapi/utils": "5.10.3",
```

I did the following steps:
1. Updated package.json (downgrade strapi version)
2. rm -rf node_modules package-lock.json .cache build dist
3. rm -rf .strapi .cache dist .tmp
4. install->build->run

And this seemed to have resolved issue. I can see my content-manager load properly now

**Comment by Mohammad-y-abbass** [comment]
This happens to me everytime i add a content type

**Comment by Callm3thebreeze** [comment]
Same error here, it is not working even moving to branchs that were stable.

**Comment by Mohammad-y-abbass** [comment]
I was able to fix it by updating strapi version if possible then run the build command this fixed it for me.

**Comment by Callm3thebreeze** [comment]
@Mohammad-y-abbass update to which versión?

**Comment by nastewart-aeg** [comment]
We experienced several of these issues when upgrading from version 5.23.5 to 5.28.0, but they seem to be resolved by upgrading to 5.29.0.

It might be worth trying to upgrade to 5.29.0, deleting any node_module folders, any node_cache folders (if configured), all package_lock.json files and npm install.

It may also be worth executing npm install @strapi/strapi@5.29.0 in your plugin folders, if applicable.

**Comment by zm1060** [comment]
I suspect the issue was caused by data corruption in the ”admin_permissions“ and ”admin_permissions_role_lnk“ tables. To resolve this, I replaced the server's tables with clean data from a working local instance. Access to the admin panel has now been successfully restored.
