### ISSUE TITLE
Strapi 5.37.0 build fails: Rollup cannot resolve @radix-ui/react-tooltip from @strapi/design-system

### ISSUE THREAD

**Issue by thematrixdev** [strapi/strapi#25567]
## Node Version
24.0.0 (Docker image: `node:24-alpine`)

## NPM/Yarn/PNPM Version
PNPM 10.28.0

## Strapi Version
5.37.0

## Operating System
Docker/Podman/LXC

## Database
MariaDB

## Javascript or Typescript
Javascript

## Reproduction URL
N/A (can provide a minimal repo if needed)

## Bug Description
After upgrading to Strapi `5.37.0`, `strapi build` fails while building the admin panel.

Vite/Rollup fails to resolve `@radix-ui/react-tooltip` imported by `@strapi/design-system/dist/index.mjs`.

This happens in a Dockerized environment using pnpm (`--frozen-lockfile`).

## Steps to Reproduce
1. Start from an existing Strapi v5 project using pnpm and Docker.
2. Upgrade Strapi packages to `5.37.0`.
3. Run `pnpm install --frozen-lockfile`.
4. Run `pnpm run build` (or Docker build stage running `strapi build`).
5. Observe admin build failure with unresolved import from `@strapi/design-system`.

## Expected Behavior
`strapi build` should complete successfully without requiring app-level direct installation of `@radix-ui/react-tooltip`.

## Logs
```shell
[vite]: Rollup failed to resolve import "@radix-ui/react-tooltip" from "/opt/node_modules/.pnpm/@strapi+design-system@2.1.2.../node_modules/@strapi/design-system/dist/index.mjs".
This is most likely unintended because it can break your application at runtime.
```

## Code Snippets
Project dependencies include:

```json
"@strapi/design-system": "^2.1.2",
"@strapi/icons": "^2.1.2",
"@strapi/strapi": "^5.37.0"
```

Workaround that makes build pass:

```json
"@radix-ui/react-tooltip": "^1.0.7"
```

## Media
N/A

## Additional information
- Build command used in Docker stage:
  - `pnpm install --frozen-lockfile`
  - `pnpm run build`
- The issue appears to be a dependency resolution/packaging mismatch surfacing under pnpm + Vite strict resolution.

## Confirmation Checklist
- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

**Comment by ozbek** [comment]
```
Failed to resolve dependency: @strapi/design-system, present in 'optimizeDeps.include'
Failed to resolve dependency: @radix-ui/react-tooltip, present in 'optimizeDeps.include'
```

**Comment by LucaNerlich** [comment]
yep, can confirm here as well.

If you add them manually to your dependency array, build will work again (even though this is not ideal).

**Comment by climba03003** [comment]
I believe https://github.com/strapi/strapi/pull/25435 is the PR raising the problem.
I see https://github.com/strapi/strapi/pull/25530 in fixing it.

**Comment by Adzouz** [comment]
Hi there,
I'm so sorry about the inconvenience and I tried to look for a solution as soon as possible. I pushed a fix to an [existing PR](https://github.com/strapi/strapi/pull/25530) that is supposed to fix the local linking of the design-system with the Strapi repo.
As @climba03003 mentioned, the issue was introduced in v5.37.0 by [this PR](https://github.com/strapi/strapi/pull/25435) 🙏
We'll try to have it merged asap, sorry again for the troubles 😢

**Comment by Adzouz** [comment]
Hi again!
I'm glad to tell you that the fix was merged and will be part of today's release (v5.38.0).
Closing the issue and sorry again for the inconvenience 🙏

**Comment by climba03003** [comment]
I can confirm the issue resolved with latest release (5.38.0).

**Comment by tewson** [comment]
I also ran into this issue even after running `npx @strapi/upgrade minor`.

~It turned out that at some point in my project's history, my `package-lock.json` was updated so that `@radix-ui/react-tooltip` wouldn't be hoisted to the top `node_modules/` path. I had to delete `package-lock.json` and rebuilt it with `npm install`.~

~If anyone runs into the same issue, try `rm package-lock.json && npm install`.~

Actually it appears to be the `npx @strapi/upgrade minor` command that caused the issue. I'll find time to collect the steps to reproduce the issue.

**Comment by pointout** [comment]
I made an upgrade from 15.37.1 to 5.42.1 with `npx @strapi/upgrade minor` and get the same error: `Error: Cannot find module '@radix-ui/react-tooltip' `

**Comment by pointout** [comment]
Removing `npm remove @radix-ui/react-tooltip` and installing again with flag to accept incorrect dependency resolution `npm i @radix-ui/react-tooltip --legacy-peer-deps` seams to work. After that I got an `zod` error, but installing zod `npm i zod` helped.

**Comment by nguyenchauhuyen** [comment]
i got the same issue after upgrade from 5.31 to 5.43

**Comment by cloakedninjas** [comment]
Still an issue - I went from 5.39.0 -> 5.52.0 using `npx @strapi/upgrade minor`
