### ISSUE TITLE
Update to 4.14.2 breaks import of utils

### ISSUE THREAD

**Issue by willempie96** [strapi/strapi#18265]
### Required System information

- Node.js version: 16
- NPM version: 9.8
- Strapi version: 4.14.2
- Database: mysql
- Operating system: mac
- Is your project Javascript or Typescript: JS

### Describe the bug

In our project we have extended the user-permissions plugin with some custom logic. 
In that custom logic we are using the getPaginationInfo function from the strapi core api library. 
Which we import like this:

`const { getPaginationInfo } = require('@strapi/strapi/lib/core-api/service/pagination');`

After updating to 4.14.2 strapi throws an error when trying to start:

`Error: Cannot find module '@strapi/strapi/lib/core-api/service/pagination'`

Do i need to change the way we import this?

### Steps to reproduce the behavior

Extend the user-permissions plugin by creating  extensions/users-permissions/strapi-server.js like in the documentation.
Import the getPaginationInfo function like:
`const { getPaginationInfo } = require('@strapi/strapi/lib/core-api/service/pagination');`
Try to startup strapi.

### Expected behavior

It works like in earlier versions

**Comment by willempie96** [comment]
@joshuaellis 

Thanks for your answer. I get the idea.
Is there some documentation about what utility functions i can import from the @strapi/strapi api?

**Comment by Arrig0** [comment]
@joshuaellis 

I faced the same problem.
So, there are any public API regarding pagination without reinventing the wheel?
I have to admit that functions like getPaginationInfo, transformPaginationResponse, convertPagedToStartLimit, even if they were designed for internal use, were very useful.

**Comment by davidkcyip** [comment]
@joshuaellis is there an alternative to getPaginationInfo and transformPaginationResponse? I was on 4.12.7 and added pagination to user-permissions as it never had any. I want to upgrade to 4.16.0 but this is a stumbling block.
