### ISSUE TITLE
Build Error on upgrade from 4.15.0: TypeError: userConfig is not a function

### ISSUE THREAD

**Issue by jumptrnr** [strapi/strapi#18723]
- Node.js version: v18.14.2
- NPM version: 9.5.0
- Strapi version: 4.15.2
- Database: MySQL (MariaDB)
- Operating system: OS (Sonoma 14.1)
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Trying to upgrade a 4.15.0 project to 4.15.2 and get the following: 

```⠋ Building build context
⠙ Building build context[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (245.1411640010774ms)
⠋ Building admin panel
⠸ Building admin <MYPROJECT DIR>/node_modules/@strapi/admin/dist/_chunks/index-cce8ecb6.js:694
    return userConfig(config, webpack2);
           



TypeError: userConfig is not a function
    at mergeConfigWithUserConfig <MYPROJECT DIR>/node_modules/@strapi/admin/dist/_chunks/index-cce8ecb6.js:694:12)
    at async /<MYPROJECT DIR>/node_modules/@strapi/admin/dist/_chunks/index-cce8ecb6.js:721:23
```

### Steps to reproduce the behavior

1. update package.json from 4.15.0 to 4.15.2 (not sure what other starting points would cause this)
2. yarn install
3. yarn build

### Expected behavior

Installs and builds successfully

### Screenshots

N/A

### Code snippets

N/A

**Comment by derrickmehaffy** [comment]
Please delete your package-lock.json and/or yarn.lock file

Ensure all @strapi/* packages do not have the ^ symbol before the version (they should be pinned)

Reinstall your node modules

And rebuild your Admin panel, this issue was fixed in v4.15.2 but your lock file is most likely using an outdated cached version.

**Comment by jumptrnr** [comment]
> Please delete your package-lock.json and/or yarn.lock file
> 
> Ensure all @strapi/* packages do not have the ^ symbol before the version (they should be pinned)
> 
> Reinstall your node modules
> 
> And rebuild your Admin panel, this issue was fixed in v4.15.2 but your lock file is most likely using an outdated cached version.

Thanks for such a quick response!  Did the above and still seems to exist.

``` "@strapi/plugin-graphql": "4.15.2",
    "@strapi/plugin-i18n": "4.15.2",
    "@strapi/plugin-users-permissions": "4.15.2",
    "@strapi/provider-email-sendgrid": "4.15.2",
    "@strapi/strapi": `"4.15.2",
```
and 

``` rm yarn.lock
❯ rm -fr node_modules
❯ yarn install
yarn install v1.22.19
warning ../package.json: No license field
info No lockfile found.
```
then
```
$ strapi build
⠋ Building build context
⠙ Building build context[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (172.61924999952316ms)
⠋ Building admin panel
⠸ Building admin panel/Users/al/Development/freshtracksback_s4/node_modules/@strapi/admin/dist/_chunks/index-cce8ecb6.js:694
    return userConfig(config, webpack2);
           ^

TypeError: userConfig is not a function
    at mergeConfigWithUserConfig (/Users/al/Development/freshtracksback_s4/node_modules/@strapi/admin/dist/_chunks/index-cce8ecb6.js:694:12)
    at async /Users/al/Development/freshtracksback_s4/node_modules/@strapi/admin/dist/_chunks/index-cce8ecb6.js:721:23
```

**Comment by umair-me** [comment]
> Please delete your package-lock.json and/or yarn.lock file
> 
> Ensure all @strapi/* packages do not have the ^ symbol before the version (they should be pinned)
> 
> Reinstall your node modules
> 
> And rebuild your Admin panel, this issue was fixed in v4.15.2 but your lock file is most likely using an outdated cached version.

Fixed the issue for me when upgrading to 4.15.0 by completing all the mentioned steps here

**Comment by jumptrnr** [comment]
no luck for me.  installing 4.15.0 was fine all along- just upgrading to 4.15.2, 3, and 4 still an issue.

**Comment by derrickmehaffy** [comment]
> still no luck for me.  installing 4.15.0 was fine all along- just upgrading to 4.15.2, 3, and 4 still an issue.
> Have also cloned my 4.15.0 version, updated to 4.15.4 installed and built - same issue so doesn't seem like a cache issue.

I can confirm this was fixed in v4.15.2 and v4.15.4

It has to be a cache issue for you as the env function is properly being passed now.

**Comment by derrickmehaffy** [comment]
Was fixed in this PR, go find that line in your node modules and check the package version in there as well: https://github.com/strapi/strapi/pull/18657

**Comment by jumptrnr** [comment]
Maybe I'm missing something but how can this be a cache issue if I:

1. clone my working 4.15.0 project into a new directory
2. delete yarn.lock
3. update the package.json to 4.15.4 for all related strapi items
```
"dependencies": {
   ...
    "@strapi-community/strapi-provider-upload-google-cloud-storage": "^4.10.5",
    "@strapi/plugin-graphql": "4.15.4",
    "@strapi/plugin-i18n": "4.15.4",
    "@strapi/plugin-users-permissions": "4.15.4",
    "@strapi/provider-email-sendgrid": "4.15.4",
    "@strapi/strapi": "4.15.4",
    "strapi-plugin-transformer": "^3.1.2",
   ...
  },
```
4. install and agree to the default to add:

```  - react@^18.0.0
  - react-dom@^18.0.0
  - react-router-dom@^5.2.0
  - styled-components@^5.2.1
 ```
5. still observe the error

Re the PR - if i search my project including node_modules - the only place I see:
```    
if (configFile) {
      return typeof configFile === "function" ? configFile({ env }) : configFile;
    }
```

Is in: 
```
node_modules/@strapi/admin/dist/_chunks/index-44360544.mjs:736:7
```
