### ISSUE TITLE
Cannot save content after upgrading to 4.5.0

### ISSUE THREAD

**Issue by francescob** [strapi/strapi#14832]
### Required System information

- Node.js version: 16.15.0
- Yarn version: 1.22.19
- Strapi version: 4.5.0
- Database: Postgres
- Operating system: MacOs

### Describe the bug

When saving any record of certain content types, I get the following error:

```
TypeError: db.getConnection(...).raw is not a function
    at cleanOrderColumns (/Users/francesco/projects/cpo-strapi/node_modules/@strapi/database/lib/entity-manager/regular-relations.js:248:10)
    at deleteRelations (/Users/francesco/projects/cpo-strapi/node_modules/@strapi/database/lib/entity-manager/regular-relations.js:166:13)
```

Other content types work as expected

Everything was working just fine with previous version (4.4.3)

### Steps to reproduce the behavior

Edit content and try to save it

### Expected behavior

Record should be saved

**Comment by felipe-balloni** [comment]
Same behavior here!.

I've tested and I get this error when upgrade from 4.4.1 to 4.4.2 and try build/start. More info is about Navigation plugin (I guess)

I'm thinking it`s related to other system related or postgres. 

My system is a MAC OS Ventura 13.1
![Captura de Tela 2022-11-10 às 11 17 22](https://user-images.githubusercontent.com/19998735/201115413-09e22683-d0d2-4f9d-9f56-74b9353fa96d.png)

**Comment by rb-ami** [comment]
I’m also seeing this problem when I try to save a content type whose relations I’ve modified.

**Comment by mrossi-rankworks** [comment]
I am also experience this issue.

**Comment by derrickmehaffy** [comment]
Can all of you with this issue please share your package.json?

If any of you are open to sharing your project codebase please also link to that.

**Comment by Brocy** [comment]
I’m also seeing this problem when I try to save a content type whose relations I’ve modified.

`{
  "name": "citiesabc-cms-strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.1.2",
    "@strapi/plugin-documentation": "4.5.0",
    "@strapi/plugin-graphql": "4.5.0",
    "@strapi/plugin-i18n": "4.5.0",
    "@strapi/plugin-seo": "^1.7.7",
    "@strapi/plugin-users-permissions": "4.5.0",
    "@strapi/provider-upload-aws-s3": "^4.5.0",
    "@strapi/provider-upload-cloudinary": "^4.5.0",
    "@strapi/strapi": "4.5.0",
    "csv-string": "^4.1.1",
    "mysql": "2.18.1",
    "parse-database-url": "^0.3.0",
    "strapi-plugin-sitemap": "^2.0.8"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "221b2350-44fb-4d9d-a88b-299b93f468f7"
  },
  "engines": {
    "node": ">=14.19.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}`

**Comment by grdevd** [comment]
```json
{
  "name": "server",
  "private": true,
  "engines": {
    "node": "16.x.x",
    "npm": "8.x.x"
  },
  "strapi": {
    "uuid": "e2fad1dc-8fb6-4847-8f36-02089a63a23e"
  },
  "scripts": {
    "dev": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@strapi/plugin-graphql": "4.5.0",
    "@strapi/plugin-sentry": "4.5.0",
    "@strapi/plugin-users-permissions": "4.5.0",
    "@strapi/provider-email-sendgrid": "4.5.0",
    "@strapi/provider-upload-aws-s3": "4.5.0",
    "@strapi/strapi": "4.5.0",
    "decimal.js": "^10.4.2",
    "dotenv": "^16.0.3",
    "lodash": "^4.17.21",
    "luxon": "^3.1.0",
    "patch-package": "^6.5.0",
    "pg": "8.8.0",
    "shared": "^0.0.0",
    "opml": "^0.5.1",
    "jsdom": "^20.0.2"
  }
}
```

**Comment by Marc-Roig** [comment]
Thank you all for raising this issue, we are working on it.

In relations reordering we introduced a [knex raw query ](https://github.com/strapi/strapi/blob/relations-reordering/fractional-orderer/packages/core/database/lib/entity-manager/regular-relations.js#L229)

My guess is it has something to do with that. What version of postgress (or other database) are you using?

**Comment by francescob** [comment]
I'm on Postgres 13.8, and here's my package.json

`{
  "name": "cpo-strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "dev": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.1.2",
    "@mattie-bundle/strapi-plugin-search": "^1.0.0-alpha.3",
    "@mattie-bundle/strapi-provider-search-algolia": "^1.0.0-alpha.3",
    "@notum-cz/strapi-plugin-content-versioning": "^0.4.4",
    "@strapi/plugin-i18n": "4.5.0",
    "@strapi/plugin-users-permissions": "4.5.0",
    "@strapi/strapi": "4.5.0",
    "marked": "^4.0.0",
    "pg": "8.6.0",
    "sharp": "^0.30.4",
    "shipit-cli": "^5.3.0",
    "shipit-deploy": "^5.3.0",
    "shipit-shared": "^4.4.2",
    "showdown": "^2.1.0",
    "strapi-plugin-config-sync": "^1.0.4",
    "strapi-plugin-preview-button": "^0.3.6",
    "strapi-plugin-slugify": "^2.2.3",
    "strapi-plugin-transformer": "^2.1.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "2341e410-572e-4990-b7fa-9defd99fdd50"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}`

**Comment by rb-ami** [comment]
Here’s mine:

{
  "name": "strapi",
  "version": "1.0.0",
  "description": "Strapi CMS for AMI Website",
  "main": "app.js",
  "author": "AMI",
  "license": "UNLICENSED",
  "private": true,
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/admin": "4.5.0",
    "@strapi/plugin-content-manager": "4.5.0",
    "@strapi/plugin-content-type-builder": "4.5.0",
    "@strapi/plugin-email": "4.5.0",
    "@strapi/plugin-graphql": "4.5.0",
    "@strapi/plugin-i18n": "4.5.0",
    "@strapi/plugin-seo": "1.7.7",
    "@strapi/plugin-upload": "4.5.0",
    "@strapi/plugin-users-permissions": "4.5.0",
    "@strapi/strapi": "4.5.0",
    "@strapi/utils": "4.5.0",
    "knex": "2.3.0",
    "pg": "8.8.0",
    "strapi-plugin-entity-relationship-chart": "4.1.0",
    "strapi-plugin-import-export-entries": "1.18.0",
    "strapi-plugin-meilisearch": "0.8.0"
  },
  "strapi": {
    "uuid": "2397008e-d69d-4d78-ae57-2d8b5f8e7af8"
  }
}

**Comment by jhoward1994** [comment]
Hi all,

Thanks for raising the issue and all your info.

The issue is indeed related to the new raw query we introduced. [knex raw query](https://github.com/strapi/strapi/blob/relations-reordering/fractional-orderer/packages/core/database/lib/entity-manager/regular-relations.js#L229)

When you have a postgres schema defined in `config/database.js` we are using `connection.withSchema(schemaName).raw()` from knex. The connection returned from `withSchema` contains no raw function.

I am working on a fix for this and will aim to get this reviewed and merged next week.

**Comment by felipe-balloni** [comment]
Hi everone,

Works for me commenting the lines from `config/database.js`. And use npm instead yarn.

```javascript
module.exports = ({env}) => ({
  connection: {
    client: 'postgres',
    connection: {
      host: env('DATABASE_HOST', '127.0.0.1'),
      port: env.int('DATABASE_PORT', 5432),
      database: env('DATABASE_NAME', 'strapi'),
      user: env('DATABASE_USERNAME', 'strapi'),
      password: env('DATABASE_PASSWORD', 'strapi')
      // schema: env('DATABASE_SCHEMA', 'public') // Not required
      // ssl: {
      //   rejectUnauthorized: env.bool('DATABASE_SSL_SELF', false) // For self-signed certificates
      // }
    }
    // debug: false
  }
});
```

![Captura de Tela 2022-11-11 às 09 22 56](https://user-images.githubusercontent.com/19998735/201339669-ff904603-12da-43f0-b49a-c590098439b4.png)

I hope it`s helps, until patch.

**Comment by rb-ami** [comment]
Or rather it fixes it for relations defined on a content type directly, but not for relations defined in a component. Here’s an example:

{
  "collectionName": "components_calls_to_action",
  "info": {
    "displayName": "Call to Action",
    "icon": "skiing"
  },
  "options": {},
  "attributes": {
    "name": {
      "type": "string",
      "required": false
    },
    "callToAction": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::call-to-action.call-to-action",
      "required": true
    }
  }
}

**Comment by iamfrisbee** [comment]
So the issue didn't appear right away. I had to delete node_modules and package-lock.json in order to get Strapi to start after updating the packages to 4.5 I was adding new content for a good 15 to 20 minutes before it happened. But commenting out the schema in the database config fixed it for me as well.

Postgres: 15.0
node: v16.18.0
npm: 8.19.2

**package.json**

```
{
  "name": "app",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.1.2",
    "@strapi/plugin-graphql": "^4.5.0",
    "@strapi/plugin-i18n": "4.5.0",
    "@strapi/plugin-users-permissions": "4.5.0",
    "@strapi/strapi": "4.5.0",
    "pg": "8.6.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "5ca1ab8b-7900-4f76-bef5-2d6ca09d2023"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by jooler** [comment]
mysql have some trouble

**Comment by jhoward1994** [comment]
Thank you all. @felipe-balloni's solution seems like a good work around for now as long as you are not making use of the schema setting in `config/database.js`

We are working on a fix that will be merged soon

**Comment by zodman** [comment]
For me this patch is working  https://github.com/strapi/strapi/pull/14887
