### ISSUE TITLE
Can't manage administrators after upgrade from 3.0.0-beta.20 to 3.1.4

### ISSUE THREAD

**Issue by Zeruk** [strapi/strapi#7541]
Hello! After reading instructions about migrating I did upgrade from 3.0.0 beta up to 3.0.0 and then up to 3.1.4.

After that all is working quite fine except the administrators management, now there just **no such field** in admin panel!

I don't know exactly what happened but believe that it is permission issue while migrating. Should I update some relations in DB?

_BTW it will be so cool to have auto upgrade tool, like all "adult" CMS' have had :)_

**Steps to reproduce the behavior**

1. Initialize strapi with version 3.0.0-beta.20
2. Create multiple admins
3. Update strapi packets to 3.0.0
4. Update strapi packets to 3.1.4
5. Rebuild admin panel with deleting of .cache, build folders
6. Can't see admin panel with logged in by first (id=1) admin

**Expected behavior**
"Manage administrators" button appears in admin panel

**Screenshots**
V3.0.0-beta.20 (BEFORE)
<img width="304" alt="Screenshot 2020-08-20 at 21 13 21" src="https://user-images.githubusercontent.com/25231381/90809574-5c9ac580-e32a-11ea-92c8-5f34aa7d48f2.png">

V3.1.4 (AFTER)
<img width="304" alt="Screenshot 2020-08-20 at 21 14 37" src="https://user-images.githubusercontent.com/25231381/90809606-67555a80-e32a-11ea-8556-2f2cf8887e32.png">

**System**

- Node.js version: v12.16.1
- NPM version: 6.13.4
- Yarn version: 1.21.1 <- I use this
- Strapi version: 3.0.0-beta.20, 3.0.0, 3.1.4
- Database: sqlite
- Operating system: MacOS

**Comment by dalbitresb12** [comment]
Hi! First of all, I should mention that I'm not a member of the Strapi team.

Administrators are no longer accesible via the dropdown menu. They are now accesible from the settings menu. This is because of the new Role-Based Access Control feature added in v3.1.

![image](https://user-images.githubusercontent.com/7624090/90813029-9baa2600-e2ec-11ea-91ac-147f9e487bed.jpg)

Hope this helps.

**Comment by derrickmehaffy** [comment]
@Zeruk As mentioned by @dalbitresb12 the admins (and the admin panel roles) have been moved to the settings area. I'm going to mark this as closed but please let us know if you need more help finding it.

(Thank you @dalbitresb12 ^_^ )

**Comment by Zeruk** [comment]
Thank you very much! I didn't expect this :D 

Sorry for unnecessary issue

**Comment by derrickmehaffy** [comment]
No problem :)

**Comment by enzzoperez** [comment]
Hi @Zeruk , did you migrate using this https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html#_3-update-username-constraint-for-administrators ?, I need make the same migration (from 3.0.0-beta.20 to 3.1.4) but with that post I get error when run `npm run develop` ..

**Comment by dalbitresb12** [comment]
Hi @enzzoperez, what error error are you getting?

**Comment by enzzoperez** [comment]
Hi @dalbitresb12 , thanks for response, I think dont matter the error because I was trying make the migration directly from `3.0.0-beta.20` to `3.1.4`, but I read that first I have to migrate to `3.0.0` (https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html) and then to `3.1.4`, so I'm still in the step  `3.0.0-beta.20` -->  `3.0.0-beta.20`

**Comment by dalbitresb12** [comment]
@enzzoperez I believe that's right. Have you tried it? Did it work?

**Comment by enzzoperez** [comment]
@dalbitresb12 Vi que sos de peru asi que te contesto en español :smile: ,  no te puedo decir si funciono porque hice un par de pasos pero lo deje a medias porque el cliente pidio otras features y a esta parte le quito prioridad, asi que en unos dias la vuelvo a retomar

**Comment by derrickmehaffy** [comment]
Hello!

To be inclusive of everyone in the community and to provide the best possible answer that everyone can refer to, we require that everyone uses English on all of our respective platforms. 

Thank you and have a wonderful day!

**Comment by dalbitresb12** [comment]
> Vi que sos de Peru asi que te contesto en español 😄 , no te puedo decir si funciono porque hice un par de pasos pero lo deje a medias porque el cliente pidio otras features y a esta parte le quito prioridad, asi que en unos dias la vuelvo a retomar

@enzzoperez Sí, soy de Perú 😄, pero ya que todos aquí hablan inglés (incluido el equipo de Strapi) consideré que sería mejor así. Al final del todo, así como dice @derrickmehaffy, tenemos que ser inclusivos con todos en la comunidad. Además, podrá ayudar a cualquier otra persona que pueda tener el mismo problema que tú.

Respecto a tu problema, lo que diga la consola es de gran ayuda para saber cuál es el problema que estás teniendo. Si envias lo que dice la consola, yo podré ayudarte o también alguien del equipo de Strapi podrá hacerlo.

---

_(Here is the translation of everything for the Strapi team and everyone else.)_

> I saw you were from Peru so I'll reply in spanish 😄 , I can't tell if it worked because I made a couple of things and then I didn't continue with it because the client asked for another features and this one lost some priority, so later I'll continue with it.

@enzzoperez Yes, I'm from Peru 😄 but since everyone here speaks English (including the Strapi team) I thought it should be like that. In the end, just as @derrickmehaffy said, we need to be inclusive with everyone in the community. Also, it will help everyone else that may have problems like this one.

About the problem you had, the console's output is really helpful to understand the problem you have. If you send that output me or someone in the Strapi team might be able to help you.

**Comment by derrickmehaffy** [comment]
Indeed, out of the Strapi team only myself is from the United States (and has english as a first language) Most of the Strapi team are French and likewise speak that natively (we also have one from Spain and another in Africa) but as a whole, the Strapi team and our community we prefer everyone uses english to ensure the maximum inclusion of everyone around the world.

Thank you for understanding and please feel free to keep the conversation going :hugs:

**Comment by enzzoperez** [comment]
oh sorry, my bad, and thank you for recommendations! :rocket:

**Comment by dalbitresb12** [comment]
@enzzoperez No worries :). Do you still need any help with the migration?
