### ISSUE TITLE
AWS S3 Upload Provider (with ACL = private) incompatible with latest versions @aws-sdk/client-s3

### ISSUE THREAD

**Issue by tomosdevans** [strapi/strapi#23153]
### Node Version

20.18.3

### NPM/Yarn/PNPM Version

10.8.2

### Strapi Version

4.25.13

### Operating System

MacOS

### Database

PostgreSQL

### Javascript or Typescript

Typescript

### Bug Description

When the Strapi instance is configured to use the AWS S3 upload provider, and the application has a defined dependency on @aws-sdk/client-s3, then uploads to the media library fail with an error message.

The upload provider works with v3.726.1 of @aws-sdk/client-s3, but fails for every later version of @aws-sdk/client-s3 (at the time of writing).

When uploading a file to the Media Library:

`error: config.requestChecksumCalculation is not a function` is listed in the logs, and a UI error is displayed.

![Image](https://github.com/user-attachments/assets/4d172681-7f27-410f-a66b-8c9ed524902e)

### Steps to Reproduce

1. Configure the Strapi instance to use the AWS S3 upload provider (as per https://market.strapi.io/providers/@strapi-provider-upload-aws-s3).
2. Set `ACL: 'private'` in the provder's params in config.
3. Add @aws-sdk/client-s3 v3.726.1 (or later) to the package.json.
4. Start Strapi.
5. Go to the Media Library.
6. Add new asset.
7. Upload a file.

### Expected Behavior

File is uploaded as expected

### Logs

```shell

```

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

**Comment by Namstel** [comment]
We're running into this issue as well. We're fixing the AWS SDK version to 3.726.1 for now to circumvent this.

**Comment by MabeyC** [comment]
+1 

I am running into this same issue. Pinning the dependency fixed it:
"@aws-sdk/client-s3": "3.726.1"

Node Version
20.19

NPM/Yarn/PNPM Version
10.8.2

Strapi Version
4.25.20

Operating System
Digital Ocean App Platform (Linux)

Database
PostgreSQL

Javascript or Typescript
Javascript

**Comment by gregauger** [comment]
I believe this has now been fixed via https://github.com/strapi/strapi/pull/25263 included in [v5.36.0](https://github.com/strapi/strapi/releases/tag/v5.36.0)
