### ISSUE TITLE
Middleware "custom": middlewareFactory is not a function when creating a custom middleware

### ISSUE THREAD

**Issue by imfrostii8** [strapi/strapi#16897]
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.5.1
- Strapi version: 4.10.7
- Database: Postgresql
- Operating system: MacOS
- Both javascript and typescript projects show the same issue

### Describe the bug

When creating a new custom middleware it shows the error: middlewareFactory is not a function

### Steps to reproduce the behavior

1. Create a new strapi project with a postgresql db 
2. Create a new custom middleware in src/middlewares/custom.js
```
    module.exports = (config, { strapi })=> {
      return (context, next) => {};
    };
```
3. Add this custom middleware to the config/middlewares.js 
```
module.exports = [
...
{
  resolve: "./src/middlewares/custom",
  config: {
    enabled: true,
    conf: {},
  },
},
];
```
### Expected behavior

Load the middleware 

### Error Message

Error: Middleware "custom": middlewareFactory is not a function
    at instantiateMiddleware

**Comment by imfrostii8** [comment]
Your suggestions solves the issue for js projects. For ts projects the error is still the same.

Error: Middleware "global::custom": middlewareFactory is not a function.

I think this is a duplicate of this one: 
https://github.com/strapi/strapi/issues/14146

But I also thought this was solved

**Comment by Boegie19** [comment]
Seems to me like the middleware you want is not registed properly

**Comment by TweededBadger** [comment]
https://github.com/strapi/strapi/blob/f7babb775ed9a7e18d8351cb7f74c63e016323c4/packages/core/strapi/lib/core/loaders/middlewares.js#L30C8-L30C8

```
   if (fd.isFile() && extname(name) === '.js') {
      const key = basename(name, '.js');
      middlewares[key] = importDefault(fullPath);
    }
```

Looking at loadLocalMiddlewares only *.js extension seems to be supported?

**Comment by VivekGupta011** [comment]
![image](https://github.com/strapi/strapi/assets/103882180/5e3737a1-e2ab-409d-9e0a-bc3802aceaa2)
Is this problem solved or not? please let me know

**Comment by imfrostii8** [comment]
> ![image](https://private-user-images.githubusercontent.com/103882180/288375647-5e3737a1-e2ab-409d-9e0a-bc3802aceaa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NjkzNjgsIm5iZiI6MTcwMTg2OTA2OCwicGF0aCI6Ii8xMDM4ODIxODAvMjg4Mzc1NjQ3LTVlMzczN2ExLWUyYWItNDA5ZC05ZTBhLWJjMzgwMmFjZWFhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxMzI0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGE3Y2FhOWRhODRmMDc0M2U1MDNjMzk3NDljN2YxMGI1MjA0NTM2ZDJiZmFmNjM3MDY2NGVhY2U3OGMxOTU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dgpjcfepI0CA1-QrbcRSE6hcpLzYH5Xh7bioDyrabTg) Is this problem solved or not? please let me know

If you are using js you can follow the earlier response. 
For ts projects as far as I know there is still the issue but I went for a completely different solution.

**Comment by ORESoftware** [comment]
guys this is a problem, need help:
```

  {
    name: 'custom::circuitBreaker',
     // name: 'global::circuitBreaker',
    // resolve: './src/middlewares/circuitBreaker',
    config: {
      enabled: false,
    },
  },
  {
    name: 'custom::rateLimiter',
     // name: 'global::rateLimiter',
    // resolve: './src/middlewares/rateLimiter',
    config: {
      enabled: true,
    },
  },
```

none of these work

**Comment by gwu929** [comment]
I have exactly same issue (typescript):

│   Error: Middleware "staticIndex": middlewareFactory is not a function                                                                                                             │
│       at instantiateMiddleware (/Users/personnal/path/info/replaced/node_modules/@strapi/strapi/dist/services/server/middleware.js:13:13)                      │
│       at Module.resolveMiddlewares (/Users/personnal/path/info/replaced/node_modules/@strapi/strapi/dist/services/server/middleware.js:53:20)                  │
│       at registerApplicationMiddlewares (/Users/personnal/path/info/replaced/node_modules/@strapi/strapi/dist/services/server/register-middlewares.js:44:40)   │
│       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                                │
│       at async Object.initMiddlewares (/Users/personnal/path/info/replaced/node_modules/@strapi/strapi/dist/services/server/index.js:69:7)                     │
│       at async Strapi.bootstrap (/Users/personnal/path/info/replaced/node_modules/@strapi/strapi/dist/Strapi.js:417:5)                                         │
│       at async Strapi.load (/Users/personnal/path/info/replaced/node_modules/@strapi/strapi/dist/Strapi.js:426:5)                                              │
│       at async Object.develop (/Users/personnal/path/info/replaced/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js:837:28)                           │
│       at async develop (/Users/personnal/path/info/replaced/node_modules/@strapi/admin/dist/_chunks/develop-YNTGWKMC.js:61:5)                                  │
│       at async Command.parseAsync (/Users/personnal/path/info/replaced/node_modules/commander/lib/command.js:923:5)

**Comment by peterbrowse** [comment]
Would you happen to know if this issue was ever investigated?

I'm on version 5.18^, and I can't for the life of me get a custom middleware to work.

It's either saying it can't find it or throwing the middlewareFactory is not a function business.

I'm following the documentation to the letter... no hope.

**Comment by BleddP** [comment]
I had the same issue but got it working. I'm on Strapi 5.20.0
In my case I wanted to filter out the duplicate entries that Strapi has decided to enter into my database after upgrading from v4 to v5, so this middleware only returns entries with a published date.

In my `config/middlewares.ts`: 

```typescript
export default [
 ...your basic strapi middlewares,
  "global::published-only", // Custom middleware
];

```

And then in `src/middlewares/published-only.ts`:

```typescript
export default () => {
  return async (ctx: any, next: any) => {
    await next();

    // Only apply to API routes, not admin
    if (ctx.request.url.startsWith("/api/") && ctx.response.body) {
      const body = ctx.response.body;

      // Handle single entry response
      if (body && !Array.isArray(body)) {
        if (body.publishedAt === null) {
          ctx.response.status = 404;
          ctx.response.body = { error: "Not Found" };
          return;
        }
      }

      // Handle collection response
      if (body && Array.isArray(body)) {
        ctx.response.body = body.filter(
          (item: any) => item.publishedAt !== null,
        );
      }
    }
  };
};


```

In the docs here: https://docs.strapi.io/cms/configurations/middlewares#naming-conventions it is mentioned that custom middleware needs to sit in the `src/middlewares` directory

**Comment by jonloh** [comment]
In v5.23.4, it works for me if I use resolve instead:

 ```
export default [
  {
    resolve: './src/middlewares/custom-middleware',
  },
];
```
